/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { EntityStatus, Permission, Role } from '@zenstackhq/runtime/models';
import { EntityStatusSchema } from '../enums/EntityStatus.schema';
import { UserSettingsSchema } from './UserSettings.schema';
import { GooglePlacesAutocompleteSchema } from './GooglePlacesAutocomplete.schema';
const baseSchema = z
  .object({
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
    createdBy: z.string().nullish(),
    updatedBy: z.string().nullish(),
    id: z.string(),
    name: z.string().min(1).max(100).regex(new RegExp('^[\\w\\s-]+$')),
    description: z.string().max(500).nullish(),
    logoUrl: z.string().nullish(),
    status: EntityStatusSchema,
    settings: z.lazy(() => UserSettingsSchema).nullish(),
    address: z.lazy(() => GooglePlacesAutocompleteSchema).nullish(),
    maxPatrols: z.number().lte(1000).nullish()
  })
  .strict();
const relationSchema = z.object({
  workspace: z.record(z.unknown()),
  patrols: z.array(z.unknown()).optional(),
  incidents: z.array(z.unknown()).optional(),
  members: z.array(z.unknown()).optional()
});
const fkSchema = z.object({
  workspaceId: z.string()
});

/**
 * `Client` schema excluding foreign keys and relations.
 */
export const ClientScalarSchema = baseSchema;

/**
 * `Client` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const ClientSchema = ClientScalarSchema.merge(fkSchema).merge(
  relationSchema.partial()
);

/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const ClientPrismaCreateSchema = baseSchema.partial().passthrough();

/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const ClientPrismaUpdateSchema = z
  .object({
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
    createdBy: z.string().nullish(),
    updatedBy: z.string().nullish(),
    id: z.string(),
    name: z.string().min(1).max(100).regex(new RegExp('^[\\w\\s-]+$')),
    description: z.string().max(500).nullish(),
    logoUrl: z.string().nullish(),
    status: EntityStatusSchema,
    settings: z.lazy(() => UserSettingsSchema).nullish(),
    address: z.lazy(() => GooglePlacesAutocompleteSchema).nullish(),
    maxPatrols: z.union([z.number().lte(1000).nullish(), z.record(z.unknown())])
  })
  .partial()
  .passthrough();

/**
 * `Client` schema for create operations excluding foreign keys and relations.
 */
export const ClientCreateScalarSchema = baseSchema.partial({
  createdAt: true,
  updatedAt: true,
  id: true,
  status: true
});

/**
 * `Client` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const ClientCreateSchema = ClientCreateScalarSchema.merge(fkSchema);

/**
 * `Client` schema for update operations excluding foreign keys and relations.
 */
export const ClientUpdateScalarSchema = baseSchema.partial();

/**
 * `Client` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const ClientUpdateSchema = ClientUpdateScalarSchema.merge(
  fkSchema.partial()
);
