/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z
  .object({
    deviceId: z.string().min(1).max(100).nullish(),
    ipv4Address: z
      .string()
      .regex(
        new RegExp(
          '^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
        )
      )
      .nullish(),
    ipv6Address: z
      .string()
      .regex(new RegExp('^([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}$'))
      .nullish(),
    deviceType: z
      .string()
      .regex(new RegExp('^(desktop|mobile|tablet|unknown)$'))
      .nullish(),
    browser: z.string().min(1).max(50).nullish(),
    browserVersion: z.string().min(1).max(20).nullish(),
    os: z.string().min(1).max(50).nullish(),
    osVersion: z.string().min(1).max(20).nullish(),
    geoLocation: z.any().nullish()
  })
  .strict();
export const DeviceInfoSchema = baseSchema;
