/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z
  .object({
    name: z.string(),
    relationship: z.string(),
    phoneNumber: z.string(),
    emailAddress: z.string().email().nullish(),
    address: z.any().nullish()
  })
  .strict();
export const EmergencyContactInfoSchema = baseSchema;
