/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import {
  IncidentStatus,
  IncidentSeverity,
  IncidentCategory,
  EntityStatus,
  Permission,
  Role
} from '@zenstackhq/runtime/models';
import { IncidentStatusSchema } from '../enums/IncidentStatus.schema';
import { IncidentSeveritySchema } from '../enums/IncidentSeverity.schema';
import { IncidentCategorySchema } from '../enums/IncidentCategory.schema';
import { GooglePlacesAutocompleteSchema } from './GooglePlacesAutocomplete.schema';
const baseSchema = z
  .object({
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
    createdBy: z.string().nullish(),
    updatedBy: z.string().nullish(),
    id: z.string(),
    title: z.string().min(1).max(200),
    description: z.string().max(2000).nullish(),
    status: IncidentStatusSchema,
    occurredAt: z.coerce.date(),
    address: z.lazy(() => GooglePlacesAutocompleteSchema).nullish(),
    severity: IncidentSeveritySchema,
    category: IncidentCategorySchema,
    responseTime: z.number().nullish(),
    resolutionTime: z.number().nullish(),
    assignedAt: z.coerce.date().nullish(),
    priority: z.number().gte(1).lte(5).nullish(),
    dueDate: z.coerce.date().nullish(),
    tags: z.array(z.string())
  })
  .strict();
const relationSchema = z.object({
  attachments: z.array(z.unknown()).optional(),
  relatedIncidents: z.array(z.unknown()).optional(),
  relatedToIncidents: z.array(z.unknown()).optional(),
  client: z.record(z.unknown()),
  patrol: z.record(z.unknown())
});
const fkSchema = z.object({
  clientId: z.string(),
  patrolId: z.string()
});

/**
 * `Incident` schema excluding foreign keys and relations.
 */
export const IncidentScalarSchema = baseSchema;

/**
 * `Incident` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const IncidentSchema = IncidentScalarSchema.merge(fkSchema).merge(
  relationSchema.partial()
);

/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const IncidentPrismaCreateSchema = baseSchema.partial().passthrough();

/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const IncidentPrismaUpdateSchema = z
  .object({
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
    createdBy: z.string().nullish(),
    updatedBy: z.string().nullish(),
    id: z.string(),
    title: z.string().min(1).max(200),
    description: z.string().max(2000).nullish(),
    status: IncidentStatusSchema,
    occurredAt: z.coerce.date(),
    address: z.lazy(() => GooglePlacesAutocompleteSchema).nullish(),
    severity: IncidentSeveritySchema,
    category: IncidentCategorySchema,
    responseTime: z.union([z.number().nullish(), z.record(z.unknown())]),
    resolutionTime: z.union([z.number().nullish(), z.record(z.unknown())]),
    assignedAt: z.coerce.date().nullish(),
    priority: z.union([
      z.number().gte(1).lte(5).nullish(),
      z.record(z.unknown())
    ]),
    dueDate: z.coerce.date().nullish(),
    tags: z.array(z.string())
  })
  .partial()
  .passthrough();

/**
 * `Incident` schema for create operations excluding foreign keys and relations.
 */
export const IncidentCreateScalarSchema = baseSchema.partial({
  createdAt: true,
  updatedAt: true,
  id: true,
  status: true,
  severity: true,
  category: true,
  tags: true
});

/**
 * `Incident` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const IncidentCreateSchema = IncidentCreateScalarSchema.merge(fkSchema);

/**
 * `Incident` schema for update operations excluding foreign keys and relations.
 */
export const IncidentUpdateScalarSchema = baseSchema.partial();

/**
 * `Incident` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const IncidentUpdateSchema = IncidentUpdateScalarSchema.merge(
  fkSchema.partial()
);
