/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { EntityStatus } from '@zenstackhq/runtime/models';
const baseSchema = z
  .object({
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
    createdBy: z.string().nullish(),
    updatedBy: z.string().nullish(),
    id: z.string(),
    objectKey: z.string(),
    objectBucket: z.string(),
    sizeInBytes: z.number(),
    mimeType: z.string(),
    metadata: z.any().nullish()
  })
  .strict();
const relationSchema = z.object({
  incidents: z.array(z.unknown()).optional(),
  profilePictureUser: z.record(z.unknown()).optional()
});

/**
 * `ObjectStorageFile` schema excluding foreign keys and relations.
 */
export const ObjectStorageFileScalarSchema = baseSchema;

/**
 * `ObjectStorageFile` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const ObjectStorageFileSchema = ObjectStorageFileScalarSchema.merge(
  relationSchema.partial()
);

/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const ObjectStorageFilePrismaCreateSchema = baseSchema
  .partial()
  .passthrough();

/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const ObjectStorageFilePrismaUpdateSchema = z
  .object({
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
    createdBy: z.string().nullish(),
    updatedBy: z.string().nullish(),
    id: z.string(),
    objectKey: z.string(),
    objectBucket: z.string(),
    sizeInBytes: z.union([z.number(), z.record(z.unknown())]),
    mimeType: z.string(),
    metadata: z.any().nullish()
  })
  .partial()
  .passthrough();

/**
 * `ObjectStorageFile` schema for create operations excluding foreign keys and relations.
 */
export const ObjectStorageFileCreateScalarSchema = baseSchema.partial({
  createdAt: true,
  updatedAt: true,
  id: true
});

/**
 * `ObjectStorageFile` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const ObjectStorageFileCreateSchema = baseSchema.partial({
  createdAt: true,
  updatedAt: true,
  id: true
});

/**
 * `ObjectStorageFile` schema for update operations excluding foreign keys and relations.
 */
export const ObjectStorageFileUpdateScalarSchema = baseSchema.partial();

/**
 * `ObjectStorageFile` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const ObjectStorageFileUpdateSchema =
  ObjectStorageFileUpdateScalarSchema;
