/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { EntityStatus, Permission, Role } from '@zenstackhq/runtime/models';
import { EntityStatusSchema } from '../enums/EntityStatus.schema';
import { GooglePlacesAutocompleteSchema } from './GooglePlacesAutocomplete.schema';
const baseSchema = z
  .object({
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
    createdBy: z.string().nullish(),
    updatedBy: z.string().nullish(),
    id: z.string(),
    name: z.string().min(1).max(100),
    description: z.string().max(500).nullish(),
    status: EntityStatusSchema,
    address: z.lazy(() => GooglePlacesAutocompleteSchema).nullish(),
    patrolSettings: z.any().nullish()
  })
  .strict();
const relationSchema = z.object({
  client: z.record(z.unknown()),
  incidents: z.array(z.unknown()).optional(),
  members: z.array(z.unknown()).optional()
});
const fkSchema = z.object({
  clientId: z.string()
});

/**
 * `Patrol` schema excluding foreign keys and relations.
 */
export const PatrolScalarSchema = baseSchema;

/**
 * `Patrol` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const PatrolSchema = PatrolScalarSchema.merge(fkSchema).merge(
  relationSchema.partial()
);

/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const PatrolPrismaCreateSchema = baseSchema.partial().passthrough();

/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const PatrolPrismaUpdateSchema = z
  .object({
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
    createdBy: z.string().nullish(),
    updatedBy: z.string().nullish(),
    id: z.string(),
    name: z.string().min(1).max(100),
    description: z.string().max(500).nullish(),
    status: EntityStatusSchema,
    address: z.lazy(() => GooglePlacesAutocompleteSchema).nullish(),
    patrolSettings: z.any().nullish()
  })
  .partial()
  .passthrough();

/**
 * `Patrol` schema for create operations excluding foreign keys and relations.
 */
export const PatrolCreateScalarSchema = baseSchema.partial({
  createdAt: true,
  updatedAt: true,
  id: true,
  status: true
});

/**
 * `Patrol` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const PatrolCreateSchema = PatrolCreateScalarSchema.merge(fkSchema);

/**
 * `Patrol` schema for update operations excluding foreign keys and relations.
 */
export const PatrolUpdateScalarSchema = baseSchema.partial();

/**
 * `Patrol` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const PatrolUpdateSchema = PatrolUpdateScalarSchema.merge(
  fkSchema.partial()
);
