/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z
  .object({
    platform: z.string().nullish(),
    browser: z.string().nullish(),
    os: z.string().nullish()
  })
  .strict();
export const SessionMetadataSchema = baseSchema;
