/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z
  .object({
    theme: z
      .string()
      .regex(new RegExp('^(light|dark|system)$'))
      .default('system'),
    locale: z
      .string()
      .regex(new RegExp('^[a-z]{2}-[A-Z]{2}$'))
      .default('en-US'),
    timezone: z.string().default('UTC'),
    dateFormat: z
      .string()
      .regex(new RegExp('^(YYYY-MM-DD|MM/DD/YYYY|DD/MM/YYYY)$'))
      .default('YYYY-MM-DD'),
    tablePageSize: z.number().gte(5).lte(100).default(10),
    navigationCollapsed: z.boolean().default(false),
    navigationFavorites: z.array(z.string())
  })
  .strict();
export const UserSettingsSchema = baseSchema;
