/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z
  .object({
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
    createdBy: z.string().nullish(),
    updatedBy: z.string().nullish(),
    id: z.string(),
    firstName: z.string(),
    lastName: z.string().nullish()
  })
  .strict();
const relationSchema = z.object({
  user: z.record(z.unknown()).optional()
});
const fkSchema = z.object({
  userId: z.string().nullish()
});

/**
 * `UserProfile` schema excluding foreign keys and relations.
 */
export const UserProfileScalarSchema = baseSchema;

/**
 * `UserProfile` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const UserProfileSchema = UserProfileScalarSchema.merge(fkSchema).merge(
  relationSchema.partial()
);

/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const UserProfilePrismaCreateSchema = baseSchema.partial().passthrough();

/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const UserProfilePrismaUpdateSchema = z
  .object({
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
    createdBy: z.string().nullish(),
    updatedBy: z.string().nullish(),
    id: z.string(),
    firstName: z.string(),
    lastName: z.string().nullish()
  })
  .partial()
  .passthrough();

/**
 * `UserProfile` schema for create operations excluding foreign keys and relations.
 */
export const UserProfileCreateScalarSchema = baseSchema.partial({
  createdAt: true,
  updatedAt: true,
  id: true
});

/**
 * `UserProfile` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const UserProfileCreateSchema =
  UserProfileCreateScalarSchema.merge(fkSchema);

/**
 * `UserProfile` schema for update operations excluding foreign keys and relations.
 */
export const UserProfileUpdateScalarSchema = baseSchema.partial();

/**
 * `UserProfile` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const UserProfileUpdateSchema = UserProfileUpdateScalarSchema.merge(
  fkSchema.partial()
);
