/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z
  .object({
    dashboard: z.any(),
    communication: z.any(),
    accessibility: z.any()
  })
  .strict();
export const UserPreferencesSchema = baseSchema;
