/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import {
  UserStatus,
  EntityStatus,
  Permission,
  Role
} from '@zenstackhq/runtime/models';
import { UserStatusSchema } from '../enums/UserStatus.schema';
import { AuthenticationMethodSchema } from '../enums/AuthenticationMethod.schema';
const baseSchema = z
  .object({
    deletedAt: z.coerce.date().nullish(),
    deletedBy: z.string().nullish(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
    createdBy: z.string().nullish(),
    updatedBy: z.string().nullish(),
    id: z.string(),
    email: z.string(),
    emailVerified: z.coerce.date().nullish(),
    password: z.string().nullish(),
    phoneNumber: z.string().nullish(),
    phoneVerified: z.coerce.date().nullish(),
    mfaEnabled: z.boolean().default(false),
    mfaSecret: z.string().nullish(),
    backupCodes: z.array(z.string()),
    lastLoginAt: z.coerce.date().nullish(),
    status: UserStatusSchema,
    authenticationMethods: z.array(AuthenticationMethodSchema),
    failedLoginAttempts: z.number().default(0),
    lockoutUntil: z.coerce.date().nullish(),
    isPlatformAdmin: z.boolean().default(false),
    requirePasswordChange: z.boolean().default(false),
    passwordLastChanged: z.coerce.date().nullish(),
    passwordResetAttempts: z.number().default(0),
    name: z.string().nullish(),
    image: z.string().nullish()
  })
  .strict();
const relationSchema = z.object({
  userProfile: z.record(z.unknown()).optional(),
  verificationTokens: z.array(z.unknown()).optional(),
  sessions: z.array(z.unknown()).optional(),
  ownedWorkspaces: z.array(z.unknown()).optional(),
  profilePicture: z.record(z.unknown()).optional(),
  memberships: z.array(z.unknown()).optional(),
  oauthAccounts: z.array(z.unknown()).optional()
});
const fkSchema = z.object({
  profilePictureId: z.string().nullish()
});

/**
 * `User` schema excluding foreign keys and relations.
 */
export const UserScalarSchema = baseSchema.omit({
  password: true,
  mfaSecret: true,
  backupCodes: true
});

/**
 * `User` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const UserSchema = UserScalarSchema.merge(fkSchema).merge(
  relationSchema.partial()
);

/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const UserPrismaCreateSchema = baseSchema.partial().passthrough();

/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const UserPrismaUpdateSchema = z
  .object({
    deletedAt: z.coerce.date().nullish(),
    deletedBy: z.string().nullish(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
    createdBy: z.string().nullish(),
    updatedBy: z.string().nullish(),
    id: z.string(),
    email: z.string(),
    emailVerified: z.coerce.date().nullish(),
    password: z.string().nullish(),
    phoneNumber: z.string().nullish(),
    phoneVerified: z.coerce.date().nullish(),
    mfaEnabled: z.boolean().default(false),
    mfaSecret: z.string().nullish(),
    backupCodes: z.array(z.string()),
    lastLoginAt: z.coerce.date().nullish(),
    status: UserStatusSchema,
    authenticationMethods: z.array(AuthenticationMethodSchema),
    failedLoginAttempts: z.union([
      z.number().default(0),
      z.record(z.unknown())
    ]),
    lockoutUntil: z.coerce.date().nullish(),
    isPlatformAdmin: z.boolean().default(false),
    requirePasswordChange: z.boolean().default(false),
    passwordLastChanged: z.coerce.date().nullish(),
    passwordResetAttempts: z.union([
      z.number().default(0),
      z.record(z.unknown())
    ]),
    name: z.string().nullish(),
    image: z.string().nullish()
  })
  .partial()
  .passthrough();

/**
 * `User` schema for create operations excluding foreign keys and relations.
 */
export const UserCreateScalarSchema = baseSchema.partial({
  createdAt: true,
  updatedAt: true,
  id: true,
  mfaEnabled: true,
  backupCodes: true,
  status: true,
  authenticationMethods: true,
  failedLoginAttempts: true,
  isPlatformAdmin: true,
  requirePasswordChange: true,
  passwordResetAttempts: true
});

/**
 * `User` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const UserCreateSchema = UserCreateScalarSchema.merge(fkSchema);

/**
 * `User` schema for update operations excluding foreign keys and relations.
 */
export const UserUpdateScalarSchema = baseSchema.partial();

/**
 * `User` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const UserUpdateSchema = UserUpdateScalarSchema.merge(
  fkSchema.partial()
);
