/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { VerificationTokenTypeSchema } from '../enums/VerificationTokenType.schema';
const baseSchema = z
  .object({
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
    createdBy: z.string().nullish(),
    updatedBy: z.string().nullish(),
    id: z.string(),
    identifier: z.string(),
    token: z.string(),
    type: VerificationTokenTypeSchema,
    expiresAt: z.coerce.date(),
    usedAt: z.coerce.date().nullish(),
    phoneNumber: z.string().nullish(),
    code: z.string().nullish(),
    attempts: z.number().default(0)
  })
  .strict();
const relationSchema = z.object({
  user: z.record(z.unknown())
});
const fkSchema = z.object({
  userId: z.string()
});

/**
 * `VerificationToken` schema excluding foreign keys and relations.
 */
export const VerificationTokenScalarSchema = baseSchema;

/**
 * `VerificationToken` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const VerificationTokenSchema = VerificationTokenScalarSchema.merge(
  fkSchema
).merge(relationSchema.partial());

/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const VerificationTokenPrismaCreateSchema = baseSchema
  .partial()
  .passthrough();

/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const VerificationTokenPrismaUpdateSchema = z
  .object({
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
    createdBy: z.string().nullish(),
    updatedBy: z.string().nullish(),
    id: z.string(),
    identifier: z.string(),
    token: z.string(),
    type: VerificationTokenTypeSchema,
    expiresAt: z.coerce.date(),
    usedAt: z.coerce.date().nullish(),
    phoneNumber: z.string().nullish(),
    code: z.string().nullish(),
    attempts: z.union([z.number().default(0), z.record(z.unknown())])
  })
  .partial()
  .passthrough();

/**
 * `VerificationToken` schema for create operations excluding foreign keys and relations.
 */
export const VerificationTokenCreateScalarSchema = baseSchema.partial({
  createdAt: true,
  updatedAt: true,
  id: true,
  attempts: true
});

/**
 * `VerificationToken` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const VerificationTokenCreateSchema =
  VerificationTokenCreateScalarSchema.merge(fkSchema);

/**
 * `VerificationToken` schema for update operations excluding foreign keys and relations.
 */
export const VerificationTokenUpdateScalarSchema = baseSchema.partial();

/**
 * `VerificationToken` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const VerificationTokenUpdateSchema =
  VerificationTokenUpdateScalarSchema.merge(fkSchema.partial());
