/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { EntityStatus, Permission, Role } from '@zenstackhq/runtime/models';
import { EntityStatusSchema } from '../enums/EntityStatus.schema';
import { UserSettingsSchema } from './UserSettings.schema';
import { GooglePlacesAutocompleteSchema } from './GooglePlacesAutocomplete.schema';
const baseSchema = z
  .object({
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
    createdBy: z.string().nullish(),
    updatedBy: z.string().nullish(),
    id: z.string(),
    name: z.string().min(1).max(100).regex(new RegExp('^[\\w\\s-]+$')),
    slug: z.string().regex(new RegExp('^[a-z0-9_-]+$')).min(3).max(50),
    logoUrl: z.string().nullish(),
    description: z.string().max(500).nullish(),
    status: EntityStatusSchema,
    settings: z.lazy(() => UserSettingsSchema).nullish(),
    address: z.lazy(() => GooglePlacesAutocompleteSchema).nullish(),
    features: z.array(z.string())
  })
  .strict();
const relationSchema = z.object({
  members: z.array(z.unknown()).optional(),
  clients: z.array(z.unknown()).optional(),
  owner: z.record(z.unknown()).optional()
});
const fkSchema = z.object({
  ownerId: z.string()
});

/**
 * `Workspace` schema excluding foreign keys and relations.
 */
export const WorkspaceScalarSchema = baseSchema;

/**
 * `Workspace` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const WorkspaceSchema = WorkspaceScalarSchema.merge(fkSchema).merge(
  relationSchema.partial()
);

/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const WorkspacePrismaCreateSchema = baseSchema.partial().passthrough();

/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const WorkspacePrismaUpdateSchema = z
  .object({
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
    createdBy: z.string().nullish(),
    updatedBy: z.string().nullish(),
    id: z.string(),
    name: z.string().min(1).max(100).regex(new RegExp('^[\\w\\s-]+$')),
    slug: z.string().regex(new RegExp('^[a-z0-9_-]+$')).min(3).max(50),
    logoUrl: z.string().nullish(),
    description: z.string().max(500).nullish(),
    status: EntityStatusSchema,
    settings: z.lazy(() => UserSettingsSchema).nullish(),
    address: z.lazy(() => GooglePlacesAutocompleteSchema).nullish(),
    features: z.array(z.string())
  })
  .partial()
  .passthrough();

/**
 * `Workspace` schema for create operations excluding foreign keys and relations.
 */
export const WorkspaceCreateScalarSchema = baseSchema.partial({
  createdAt: true,
  updatedAt: true,
  id: true,
  status: true,
  features: true
});

/**
 * `Workspace` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const WorkspaceCreateSchema =
  WorkspaceCreateScalarSchema.merge(fkSchema);

/**
 * `Workspace` schema for update operations excluding foreign keys and relations.
 */
export const WorkspaceUpdateScalarSchema = baseSchema.partial();

/**
 * `Workspace` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const WorkspaceUpdateSchema = WorkspaceUpdateScalarSchema.merge(
  fkSchema.partial()
);
