/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import type { Prisma } from '@zenstackhq/runtime/models';

import { OAuthAccountSelectObjectSchema } from '../objects/OAuthAccountSelect.schema';
import { OAuthAccountIncludeObjectSchema } from '../objects/OAuthAccountInclude.schema';
import { OAuthAccountWhereUniqueInputObjectSchema } from '../objects/OAuthAccountWhereUniqueInput.schema';
import { OAuthAccountWhereInputObjectSchema } from '../objects/OAuthAccountWhereInput.schema';
import { OAuthAccountOrderByWithRelationInputObjectSchema } from '../objects/OAuthAccountOrderByWithRelationInput.schema';
import { OAuthAccountScalarFieldEnumSchema } from '../enums/OAuthAccountScalarFieldEnum.schema';
import { OAuthAccountCreateInputObjectSchema } from '../objects/OAuthAccountCreateInput.schema';
import { OAuthAccountUncheckedCreateInputObjectSchema } from '../objects/OAuthAccountUncheckedCreateInput.schema';
import { OAuthAccountCreateManyInputObjectSchema } from '../objects/OAuthAccountCreateManyInput.schema';
import { OAuthAccountUpdateInputObjectSchema } from '../objects/OAuthAccountUpdateInput.schema';
import { OAuthAccountUncheckedUpdateInputObjectSchema } from '../objects/OAuthAccountUncheckedUpdateInput.schema';
import { OAuthAccountUpdateManyMutationInputObjectSchema } from '../objects/OAuthAccountUpdateManyMutationInput.schema';
import { OAuthAccountUncheckedUpdateManyInputObjectSchema } from '../objects/OAuthAccountUncheckedUpdateManyInput.schema';
import { OAuthAccountCountAggregateInputObjectSchema } from '../objects/OAuthAccountCountAggregateInput.schema';
import { OAuthAccountMinAggregateInputObjectSchema } from '../objects/OAuthAccountMinAggregateInput.schema';
import { OAuthAccountMaxAggregateInputObjectSchema } from '../objects/OAuthAccountMaxAggregateInput.schema';
import { OAuthAccountOrderByWithAggregationInputObjectSchema } from '../objects/OAuthAccountOrderByWithAggregationInput.schema';
import { OAuthAccountScalarWhereWithAggregatesInputObjectSchema } from '../objects/OAuthAccountScalarWhereWithAggregatesInput.schema';

type OAuthAccountInputSchemaType = {
  findUnique: z.ZodType<Prisma.OAuthAccountFindUniqueArgs>;
  findFirst: z.ZodType<Prisma.OAuthAccountFindFirstArgs>;
  findMany: z.ZodType<Prisma.OAuthAccountFindManyArgs>;
  create: z.ZodType<Prisma.OAuthAccountCreateArgs>;
  createMany: z.ZodType<Prisma.OAuthAccountCreateManyArgs>;
  delete: z.ZodType<Prisma.OAuthAccountDeleteArgs>;
  deleteMany: z.ZodType<Prisma.OAuthAccountDeleteManyArgs>;
  update: z.ZodType<Prisma.OAuthAccountUpdateArgs>;
  updateMany: z.ZodType<Prisma.OAuthAccountUpdateManyArgs>;
  upsert: z.ZodType<Prisma.OAuthAccountUpsertArgs>;
  aggregate: z.ZodType<Prisma.OAuthAccountAggregateArgs>;
  groupBy: z.ZodType<Prisma.OAuthAccountGroupByArgs>;
  count: z.ZodType<Prisma.OAuthAccountCountArgs>;
};

export const OAuthAccountInputSchema = {
  findUnique: z
    .object({
      select: z.lazy(() => OAuthAccountSelectObjectSchema.optional()),
      include: z.lazy(() => OAuthAccountIncludeObjectSchema.optional()),
      where: OAuthAccountWhereUniqueInputObjectSchema
    })
    .strict(),
  findFirst: z
    .object({
      select: z.lazy(() => OAuthAccountSelectObjectSchema.optional()),
      include: z.lazy(() => OAuthAccountIncludeObjectSchema.optional()),
      where: OAuthAccountWhereInputObjectSchema.optional(),
      orderBy: z
        .union([
          OAuthAccountOrderByWithRelationInputObjectSchema,
          OAuthAccountOrderByWithRelationInputObjectSchema.array()
        ])
        .optional(),
      cursor: OAuthAccountWhereUniqueInputObjectSchema.optional(),
      take: z.number().optional(),
      skip: z.number().optional(),
      distinct: z.array(OAuthAccountScalarFieldEnumSchema).optional()
    })
    .strict(),
  findMany: z
    .object({
      select: z.lazy(() => OAuthAccountSelectObjectSchema.optional()),
      include: z.lazy(() => OAuthAccountIncludeObjectSchema.optional()),
      where: OAuthAccountWhereInputObjectSchema.optional(),
      orderBy: z
        .union([
          OAuthAccountOrderByWithRelationInputObjectSchema,
          OAuthAccountOrderByWithRelationInputObjectSchema.array()
        ])
        .optional(),
      cursor: OAuthAccountWhereUniqueInputObjectSchema.optional(),
      take: z.number().optional(),
      skip: z.number().optional(),
      distinct: z.array(OAuthAccountScalarFieldEnumSchema).optional()
    })
    .strict(),
  create: z
    .object({
      select: z.lazy(() => OAuthAccountSelectObjectSchema.optional()),
      include: z.lazy(() => OAuthAccountIncludeObjectSchema.optional()),
      data: z.union([
        OAuthAccountCreateInputObjectSchema,
        OAuthAccountUncheckedCreateInputObjectSchema
      ])
    })
    .strict(),
  createMany: z
    .object({
      data: z.union([
        OAuthAccountCreateManyInputObjectSchema,
        z.array(OAuthAccountCreateManyInputObjectSchema)
      ]),
      skipDuplicates: z.boolean().optional()
    })
    .strict(),
  delete: z
    .object({
      select: z.lazy(() => OAuthAccountSelectObjectSchema.optional()),
      include: z.lazy(() => OAuthAccountIncludeObjectSchema.optional()),
      where: OAuthAccountWhereUniqueInputObjectSchema
    })
    .strict(),
  deleteMany: z
    .object({
      where: OAuthAccountWhereInputObjectSchema.optional()
    })
    .strict(),
  update: z
    .object({
      select: z.lazy(() => OAuthAccountSelectObjectSchema.optional()),
      include: z.lazy(() => OAuthAccountIncludeObjectSchema.optional()),
      data: z.union([
        OAuthAccountUpdateInputObjectSchema,
        OAuthAccountUncheckedUpdateInputObjectSchema
      ]),
      where: OAuthAccountWhereUniqueInputObjectSchema
    })
    .strict(),
  updateMany: z
    .object({
      data: z.union([
        OAuthAccountUpdateManyMutationInputObjectSchema,
        OAuthAccountUncheckedUpdateManyInputObjectSchema
      ]),
      where: OAuthAccountWhereInputObjectSchema.optional()
    })
    .strict(),
  upsert: z
    .object({
      select: z.lazy(() => OAuthAccountSelectObjectSchema.optional()),
      include: z.lazy(() => OAuthAccountIncludeObjectSchema.optional()),
      where: OAuthAccountWhereUniqueInputObjectSchema,
      create: z.union([
        OAuthAccountCreateInputObjectSchema,
        OAuthAccountUncheckedCreateInputObjectSchema
      ]),
      update: z.union([
        OAuthAccountUpdateInputObjectSchema,
        OAuthAccountUncheckedUpdateInputObjectSchema
      ])
    })
    .strict(),
  aggregate: z
    .object({
      where: OAuthAccountWhereInputObjectSchema.optional(),
      orderBy: z
        .union([
          OAuthAccountOrderByWithRelationInputObjectSchema,
          OAuthAccountOrderByWithRelationInputObjectSchema.array()
        ])
        .optional(),
      cursor: OAuthAccountWhereUniqueInputObjectSchema.optional(),
      take: z.number().optional(),
      skip: z.number().optional(),
      _count: z
        .union([z.literal(true), OAuthAccountCountAggregateInputObjectSchema])
        .optional(),
      _min: OAuthAccountMinAggregateInputObjectSchema.optional(),
      _max: OAuthAccountMaxAggregateInputObjectSchema.optional()
    })
    .strict(),
  groupBy: z
    .object({
      where: OAuthAccountWhereInputObjectSchema.optional(),
      orderBy: z
        .union([
          OAuthAccountOrderByWithAggregationInputObjectSchema,
          OAuthAccountOrderByWithAggregationInputObjectSchema.array()
        ])
        .optional(),
      having: OAuthAccountScalarWhereWithAggregatesInputObjectSchema.optional(),
      take: z.number().optional(),
      skip: z.number().optional(),
      by: z.array(OAuthAccountScalarFieldEnumSchema),
      _count: z
        .union([z.literal(true), OAuthAccountCountAggregateInputObjectSchema])
        .optional(),
      _min: OAuthAccountMinAggregateInputObjectSchema.optional(),
      _max: OAuthAccountMaxAggregateInputObjectSchema.optional()
    })
    .strict(),
  count: z
    .object({
      where: OAuthAccountWhereInputObjectSchema.optional(),
      orderBy: z
        .union([
          OAuthAccountOrderByWithRelationInputObjectSchema,
          OAuthAccountOrderByWithRelationInputObjectSchema.array()
        ])
        .optional(),
      cursor: OAuthAccountWhereUniqueInputObjectSchema.optional(),
      take: z.number().optional(),
      skip: z.number().optional(),
      distinct: z.array(OAuthAccountScalarFieldEnumSchema).optional(),
      select: z
        .union([z.literal(true), OAuthAccountCountAggregateInputObjectSchema])
        .optional()
    })
    .strict()
} as OAuthAccountInputSchemaType;
