/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import type { Prisma } from '@zenstackhq/runtime/models';

import { ObjectStorageFileSelectObjectSchema } from '../objects/ObjectStorageFileSelect.schema';
import { ObjectStorageFileIncludeObjectSchema } from '../objects/ObjectStorageFileInclude.schema';
import { ObjectStorageFileWhereUniqueInputObjectSchema } from '../objects/ObjectStorageFileWhereUniqueInput.schema';
import { ObjectStorageFileWhereInputObjectSchema } from '../objects/ObjectStorageFileWhereInput.schema';
import { ObjectStorageFileOrderByWithRelationInputObjectSchema } from '../objects/ObjectStorageFileOrderByWithRelationInput.schema';
import { ObjectStorageFileScalarFieldEnumSchema } from '../enums/ObjectStorageFileScalarFieldEnum.schema';
import { ObjectStorageFileCreateInputObjectSchema } from '../objects/ObjectStorageFileCreateInput.schema';
import { ObjectStorageFileUncheckedCreateInputObjectSchema } from '../objects/ObjectStorageFileUncheckedCreateInput.schema';
import { ObjectStorageFileCreateManyInputObjectSchema } from '../objects/ObjectStorageFileCreateManyInput.schema';
import { ObjectStorageFileUpdateInputObjectSchema } from '../objects/ObjectStorageFileUpdateInput.schema';
import { ObjectStorageFileUncheckedUpdateInputObjectSchema } from '../objects/ObjectStorageFileUncheckedUpdateInput.schema';
import { ObjectStorageFileUpdateManyMutationInputObjectSchema } from '../objects/ObjectStorageFileUpdateManyMutationInput.schema';
import { ObjectStorageFileUncheckedUpdateManyInputObjectSchema } from '../objects/ObjectStorageFileUncheckedUpdateManyInput.schema';
import { ObjectStorageFileCountAggregateInputObjectSchema } from '../objects/ObjectStorageFileCountAggregateInput.schema';
import { ObjectStorageFileMinAggregateInputObjectSchema } from '../objects/ObjectStorageFileMinAggregateInput.schema';
import { ObjectStorageFileMaxAggregateInputObjectSchema } from '../objects/ObjectStorageFileMaxAggregateInput.schema';
import { ObjectStorageFileAvgAggregateInputObjectSchema } from '../objects/ObjectStorageFileAvgAggregateInput.schema';
import { ObjectStorageFileSumAggregateInputObjectSchema } from '../objects/ObjectStorageFileSumAggregateInput.schema';
import { ObjectStorageFileOrderByWithAggregationInputObjectSchema } from '../objects/ObjectStorageFileOrderByWithAggregationInput.schema';
import { ObjectStorageFileScalarWhereWithAggregatesInputObjectSchema } from '../objects/ObjectStorageFileScalarWhereWithAggregatesInput.schema';

type ObjectStorageFileInputSchemaType = {
  findUnique: z.ZodType<Prisma.ObjectStorageFileFindUniqueArgs>;
  findFirst: z.ZodType<Prisma.ObjectStorageFileFindFirstArgs>;
  findMany: z.ZodType<Prisma.ObjectStorageFileFindManyArgs>;
  create: z.ZodType<Prisma.ObjectStorageFileCreateArgs>;
  createMany: z.ZodType<Prisma.ObjectStorageFileCreateManyArgs>;
  delete: z.ZodType<Prisma.ObjectStorageFileDeleteArgs>;
  deleteMany: z.ZodType<Prisma.ObjectStorageFileDeleteManyArgs>;
  update: z.ZodType<Prisma.ObjectStorageFileUpdateArgs>;
  updateMany: z.ZodType<Prisma.ObjectStorageFileUpdateManyArgs>;
  upsert: z.ZodType<Prisma.ObjectStorageFileUpsertArgs>;
  aggregate: z.ZodType<Prisma.ObjectStorageFileAggregateArgs>;
  groupBy: z.ZodType<Prisma.ObjectStorageFileGroupByArgs>;
  count: z.ZodType<Prisma.ObjectStorageFileCountArgs>;
};

export const ObjectStorageFileInputSchema = {
  findUnique: z
    .object({
      select: z.lazy(() => ObjectStorageFileSelectObjectSchema.optional()),
      include: z.lazy(() => ObjectStorageFileIncludeObjectSchema.optional()),
      where: ObjectStorageFileWhereUniqueInputObjectSchema
    })
    .strict(),
  findFirst: z
    .object({
      select: z.lazy(() => ObjectStorageFileSelectObjectSchema.optional()),
      include: z.lazy(() => ObjectStorageFileIncludeObjectSchema.optional()),
      where: ObjectStorageFileWhereInputObjectSchema.optional(),
      orderBy: z
        .union([
          ObjectStorageFileOrderByWithRelationInputObjectSchema,
          ObjectStorageFileOrderByWithRelationInputObjectSchema.array()
        ])
        .optional(),
      cursor: ObjectStorageFileWhereUniqueInputObjectSchema.optional(),
      take: z.number().optional(),
      skip: z.number().optional(),
      distinct: z.array(ObjectStorageFileScalarFieldEnumSchema).optional()
    })
    .strict(),
  findMany: z
    .object({
      select: z.lazy(() => ObjectStorageFileSelectObjectSchema.optional()),
      include: z.lazy(() => ObjectStorageFileIncludeObjectSchema.optional()),
      where: ObjectStorageFileWhereInputObjectSchema.optional(),
      orderBy: z
        .union([
          ObjectStorageFileOrderByWithRelationInputObjectSchema,
          ObjectStorageFileOrderByWithRelationInputObjectSchema.array()
        ])
        .optional(),
      cursor: ObjectStorageFileWhereUniqueInputObjectSchema.optional(),
      take: z.number().optional(),
      skip: z.number().optional(),
      distinct: z.array(ObjectStorageFileScalarFieldEnumSchema).optional()
    })
    .strict(),
  create: z
    .object({
      select: z.lazy(() => ObjectStorageFileSelectObjectSchema.optional()),
      include: z.lazy(() => ObjectStorageFileIncludeObjectSchema.optional()),
      data: z.union([
        ObjectStorageFileCreateInputObjectSchema,
        ObjectStorageFileUncheckedCreateInputObjectSchema
      ])
    })
    .strict(),
  createMany: z
    .object({
      data: z.union([
        ObjectStorageFileCreateManyInputObjectSchema,
        z.array(ObjectStorageFileCreateManyInputObjectSchema)
      ]),
      skipDuplicates: z.boolean().optional()
    })
    .strict(),
  delete: z
    .object({
      select: z.lazy(() => ObjectStorageFileSelectObjectSchema.optional()),
      include: z.lazy(() => ObjectStorageFileIncludeObjectSchema.optional()),
      where: ObjectStorageFileWhereUniqueInputObjectSchema
    })
    .strict(),
  deleteMany: z
    .object({
      where: ObjectStorageFileWhereInputObjectSchema.optional()
    })
    .strict(),
  update: z
    .object({
      select: z.lazy(() => ObjectStorageFileSelectObjectSchema.optional()),
      include: z.lazy(() => ObjectStorageFileIncludeObjectSchema.optional()),
      data: z.union([
        ObjectStorageFileUpdateInputObjectSchema,
        ObjectStorageFileUncheckedUpdateInputObjectSchema
      ]),
      where: ObjectStorageFileWhereUniqueInputObjectSchema
    })
    .strict(),
  updateMany: z
    .object({
      data: z.union([
        ObjectStorageFileUpdateManyMutationInputObjectSchema,
        ObjectStorageFileUncheckedUpdateManyInputObjectSchema
      ]),
      where: ObjectStorageFileWhereInputObjectSchema.optional()
    })
    .strict(),
  upsert: z
    .object({
      select: z.lazy(() => ObjectStorageFileSelectObjectSchema.optional()),
      include: z.lazy(() => ObjectStorageFileIncludeObjectSchema.optional()),
      where: ObjectStorageFileWhereUniqueInputObjectSchema,
      create: z.union([
        ObjectStorageFileCreateInputObjectSchema,
        ObjectStorageFileUncheckedCreateInputObjectSchema
      ]),
      update: z.union([
        ObjectStorageFileUpdateInputObjectSchema,
        ObjectStorageFileUncheckedUpdateInputObjectSchema
      ])
    })
    .strict(),
  aggregate: z
    .object({
      where: ObjectStorageFileWhereInputObjectSchema.optional(),
      orderBy: z
        .union([
          ObjectStorageFileOrderByWithRelationInputObjectSchema,
          ObjectStorageFileOrderByWithRelationInputObjectSchema.array()
        ])
        .optional(),
      cursor: ObjectStorageFileWhereUniqueInputObjectSchema.optional(),
      take: z.number().optional(),
      skip: z.number().optional(),
      _count: z
        .union([
          z.literal(true),
          ObjectStorageFileCountAggregateInputObjectSchema
        ])
        .optional(),
      _min: ObjectStorageFileMinAggregateInputObjectSchema.optional(),
      _max: ObjectStorageFileMaxAggregateInputObjectSchema.optional(),
      _avg: ObjectStorageFileAvgAggregateInputObjectSchema.optional(),
      _sum: ObjectStorageFileSumAggregateInputObjectSchema.optional()
    })
    .strict(),
  groupBy: z
    .object({
      where: ObjectStorageFileWhereInputObjectSchema.optional(),
      orderBy: z
        .union([
          ObjectStorageFileOrderByWithAggregationInputObjectSchema,
          ObjectStorageFileOrderByWithAggregationInputObjectSchema.array()
        ])
        .optional(),
      having:
        ObjectStorageFileScalarWhereWithAggregatesInputObjectSchema.optional(),
      take: z.number().optional(),
      skip: z.number().optional(),
      by: z.array(ObjectStorageFileScalarFieldEnumSchema),
      _count: z
        .union([
          z.literal(true),
          ObjectStorageFileCountAggregateInputObjectSchema
        ])
        .optional(),
      _min: ObjectStorageFileMinAggregateInputObjectSchema.optional(),
      _max: ObjectStorageFileMaxAggregateInputObjectSchema.optional(),
      _avg: ObjectStorageFileAvgAggregateInputObjectSchema.optional(),
      _sum: ObjectStorageFileSumAggregateInputObjectSchema.optional()
    })
    .strict(),
  count: z
    .object({
      where: ObjectStorageFileWhereInputObjectSchema.optional(),
      orderBy: z
        .union([
          ObjectStorageFileOrderByWithRelationInputObjectSchema,
          ObjectStorageFileOrderByWithRelationInputObjectSchema.array()
        ])
        .optional(),
      cursor: ObjectStorageFileWhereUniqueInputObjectSchema.optional(),
      take: z.number().optional(),
      skip: z.number().optional(),
      distinct: z.array(ObjectStorageFileScalarFieldEnumSchema).optional(),
      select: z
        .union([
          z.literal(true),
          ObjectStorageFileCountAggregateInputObjectSchema
        ])
        .optional()
    })
    .strict()
} as ObjectStorageFileInputSchemaType;
