/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import type { Prisma } from '@zenstackhq/runtime/models';

import { PatrolSelectObjectSchema } from '../objects/PatrolSelect.schema';
import { PatrolIncludeObjectSchema } from '../objects/PatrolInclude.schema';
import { PatrolWhereUniqueInputObjectSchema } from '../objects/PatrolWhereUniqueInput.schema';
import { PatrolWhereInputObjectSchema } from '../objects/PatrolWhereInput.schema';
import { PatrolOrderByWithRelationInputObjectSchema } from '../objects/PatrolOrderByWithRelationInput.schema';
import { PatrolScalarFieldEnumSchema } from '../enums/PatrolScalarFieldEnum.schema';
import { PatrolCreateInputObjectSchema } from '../objects/PatrolCreateInput.schema';
import { PatrolUncheckedCreateInputObjectSchema } from '../objects/PatrolUncheckedCreateInput.schema';
import { PatrolCreateManyInputObjectSchema } from '../objects/PatrolCreateManyInput.schema';
import { PatrolUpdateInputObjectSchema } from '../objects/PatrolUpdateInput.schema';
import { PatrolUncheckedUpdateInputObjectSchema } from '../objects/PatrolUncheckedUpdateInput.schema';
import { PatrolUpdateManyMutationInputObjectSchema } from '../objects/PatrolUpdateManyMutationInput.schema';
import { PatrolUncheckedUpdateManyInputObjectSchema } from '../objects/PatrolUncheckedUpdateManyInput.schema';
import { PatrolCountAggregateInputObjectSchema } from '../objects/PatrolCountAggregateInput.schema';
import { PatrolMinAggregateInputObjectSchema } from '../objects/PatrolMinAggregateInput.schema';
import { PatrolMaxAggregateInputObjectSchema } from '../objects/PatrolMaxAggregateInput.schema';
import { PatrolOrderByWithAggregationInputObjectSchema } from '../objects/PatrolOrderByWithAggregationInput.schema';
import { PatrolScalarWhereWithAggregatesInputObjectSchema } from '../objects/PatrolScalarWhereWithAggregatesInput.schema';

type PatrolInputSchemaType = {
  findUnique: z.ZodType<Prisma.PatrolFindUniqueArgs>;
  findFirst: z.ZodType<Prisma.PatrolFindFirstArgs>;
  findMany: z.ZodType<Prisma.PatrolFindManyArgs>;
  create: z.ZodType<Prisma.PatrolCreateArgs>;
  createMany: z.ZodType<Prisma.PatrolCreateManyArgs>;
  delete: z.ZodType<Prisma.PatrolDeleteArgs>;
  deleteMany: z.ZodType<Prisma.PatrolDeleteManyArgs>;
  update: z.ZodType<Prisma.PatrolUpdateArgs>;
  updateMany: z.ZodType<Prisma.PatrolUpdateManyArgs>;
  upsert: z.ZodType<Prisma.PatrolUpsertArgs>;
  aggregate: z.ZodType<Prisma.PatrolAggregateArgs>;
  groupBy: z.ZodType<Prisma.PatrolGroupByArgs>;
  count: z.ZodType<Prisma.PatrolCountArgs>;
};

export const PatrolInputSchema = {
  findUnique: z
    .object({
      select: z.lazy(() => PatrolSelectObjectSchema.optional()),
      include: z.lazy(() => PatrolIncludeObjectSchema.optional()),
      where: PatrolWhereUniqueInputObjectSchema
    })
    .strict(),
  findFirst: z
    .object({
      select: z.lazy(() => PatrolSelectObjectSchema.optional()),
      include: z.lazy(() => PatrolIncludeObjectSchema.optional()),
      where: PatrolWhereInputObjectSchema.optional(),
      orderBy: z
        .union([
          PatrolOrderByWithRelationInputObjectSchema,
          PatrolOrderByWithRelationInputObjectSchema.array()
        ])
        .optional(),
      cursor: PatrolWhereUniqueInputObjectSchema.optional(),
      take: z.number().optional(),
      skip: z.number().optional(),
      distinct: z.array(PatrolScalarFieldEnumSchema).optional()
    })
    .strict(),
  findMany: z
    .object({
      select: z.lazy(() => PatrolSelectObjectSchema.optional()),
      include: z.lazy(() => PatrolIncludeObjectSchema.optional()),
      where: PatrolWhereInputObjectSchema.optional(),
      orderBy: z
        .union([
          PatrolOrderByWithRelationInputObjectSchema,
          PatrolOrderByWithRelationInputObjectSchema.array()
        ])
        .optional(),
      cursor: PatrolWhereUniqueInputObjectSchema.optional(),
      take: z.number().optional(),
      skip: z.number().optional(),
      distinct: z.array(PatrolScalarFieldEnumSchema).optional()
    })
    .strict(),
  create: z
    .object({
      select: z.lazy(() => PatrolSelectObjectSchema.optional()),
      include: z.lazy(() => PatrolIncludeObjectSchema.optional()),
      data: z.union([
        PatrolCreateInputObjectSchema,
        PatrolUncheckedCreateInputObjectSchema
      ])
    })
    .strict(),
  createMany: z
    .object({
      data: z.union([
        PatrolCreateManyInputObjectSchema,
        z.array(PatrolCreateManyInputObjectSchema)
      ]),
      skipDuplicates: z.boolean().optional()
    })
    .strict(),
  delete: z
    .object({
      select: z.lazy(() => PatrolSelectObjectSchema.optional()),
      include: z.lazy(() => PatrolIncludeObjectSchema.optional()),
      where: PatrolWhereUniqueInputObjectSchema
    })
    .strict(),
  deleteMany: z
    .object({
      where: PatrolWhereInputObjectSchema.optional()
    })
    .strict(),
  update: z
    .object({
      select: z.lazy(() => PatrolSelectObjectSchema.optional()),
      include: z.lazy(() => PatrolIncludeObjectSchema.optional()),
      data: z.union([
        PatrolUpdateInputObjectSchema,
        PatrolUncheckedUpdateInputObjectSchema
      ]),
      where: PatrolWhereUniqueInputObjectSchema
    })
    .strict(),
  updateMany: z
    .object({
      data: z.union([
        PatrolUpdateManyMutationInputObjectSchema,
        PatrolUncheckedUpdateManyInputObjectSchema
      ]),
      where: PatrolWhereInputObjectSchema.optional()
    })
    .strict(),
  upsert: z
    .object({
      select: z.lazy(() => PatrolSelectObjectSchema.optional()),
      include: z.lazy(() => PatrolIncludeObjectSchema.optional()),
      where: PatrolWhereUniqueInputObjectSchema,
      create: z.union([
        PatrolCreateInputObjectSchema,
        PatrolUncheckedCreateInputObjectSchema
      ]),
      update: z.union([
        PatrolUpdateInputObjectSchema,
        PatrolUncheckedUpdateInputObjectSchema
      ])
    })
    .strict(),
  aggregate: z
    .object({
      where: PatrolWhereInputObjectSchema.optional(),
      orderBy: z
        .union([
          PatrolOrderByWithRelationInputObjectSchema,
          PatrolOrderByWithRelationInputObjectSchema.array()
        ])
        .optional(),
      cursor: PatrolWhereUniqueInputObjectSchema.optional(),
      take: z.number().optional(),
      skip: z.number().optional(),
      _count: z
        .union([z.literal(true), PatrolCountAggregateInputObjectSchema])
        .optional(),
      _min: PatrolMinAggregateInputObjectSchema.optional(),
      _max: PatrolMaxAggregateInputObjectSchema.optional()
    })
    .strict(),
  groupBy: z
    .object({
      where: PatrolWhereInputObjectSchema.optional(),
      orderBy: z
        .union([
          PatrolOrderByWithAggregationInputObjectSchema,
          PatrolOrderByWithAggregationInputObjectSchema.array()
        ])
        .optional(),
      having: PatrolScalarWhereWithAggregatesInputObjectSchema.optional(),
      take: z.number().optional(),
      skip: z.number().optional(),
      by: z.array(PatrolScalarFieldEnumSchema),
      _count: z
        .union([z.literal(true), PatrolCountAggregateInputObjectSchema])
        .optional(),
      _min: PatrolMinAggregateInputObjectSchema.optional(),
      _max: PatrolMaxAggregateInputObjectSchema.optional()
    })
    .strict(),
  count: z
    .object({
      where: PatrolWhereInputObjectSchema.optional(),
      orderBy: z
        .union([
          PatrolOrderByWithRelationInputObjectSchema,
          PatrolOrderByWithRelationInputObjectSchema.array()
        ])
        .optional(),
      cursor: PatrolWhereUniqueInputObjectSchema.optional(),
      take: z.number().optional(),
      skip: z.number().optional(),
      distinct: z.array(PatrolScalarFieldEnumSchema).optional(),
      select: z
        .union([z.literal(true), PatrolCountAggregateInputObjectSchema])
        .optional()
    })
    .strict()
} as PatrolInputSchemaType;
