/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import type { Prisma } from '@zenstackhq/runtime/models';

import { ResourceMemberSelectObjectSchema } from '../objects/ResourceMemberSelect.schema';
import { ResourceMemberIncludeObjectSchema } from '../objects/ResourceMemberInclude.schema';
import { ResourceMemberWhereUniqueInputObjectSchema } from '../objects/ResourceMemberWhereUniqueInput.schema';
import { ResourceMemberWhereInputObjectSchema } from '../objects/ResourceMemberWhereInput.schema';
import { ResourceMemberOrderByWithRelationInputObjectSchema } from '../objects/ResourceMemberOrderByWithRelationInput.schema';
import { ResourceMemberScalarFieldEnumSchema } from '../enums/ResourceMemberScalarFieldEnum.schema';
import { ResourceMemberCreateInputObjectSchema } from '../objects/ResourceMemberCreateInput.schema';
import { ResourceMemberUncheckedCreateInputObjectSchema } from '../objects/ResourceMemberUncheckedCreateInput.schema';
import { ResourceMemberCreateManyInputObjectSchema } from '../objects/ResourceMemberCreateManyInput.schema';
import { ResourceMemberUpdateInputObjectSchema } from '../objects/ResourceMemberUpdateInput.schema';
import { ResourceMemberUncheckedUpdateInputObjectSchema } from '../objects/ResourceMemberUncheckedUpdateInput.schema';
import { ResourceMemberUpdateManyMutationInputObjectSchema } from '../objects/ResourceMemberUpdateManyMutationInput.schema';
import { ResourceMemberUncheckedUpdateManyInputObjectSchema } from '../objects/ResourceMemberUncheckedUpdateManyInput.schema';
import { ResourceMemberCountAggregateInputObjectSchema } from '../objects/ResourceMemberCountAggregateInput.schema';
import { ResourceMemberMinAggregateInputObjectSchema } from '../objects/ResourceMemberMinAggregateInput.schema';
import { ResourceMemberMaxAggregateInputObjectSchema } from '../objects/ResourceMemberMaxAggregateInput.schema';
import { ResourceMemberOrderByWithAggregationInputObjectSchema } from '../objects/ResourceMemberOrderByWithAggregationInput.schema';
import { ResourceMemberScalarWhereWithAggregatesInputObjectSchema } from '../objects/ResourceMemberScalarWhereWithAggregatesInput.schema';

type ResourceMemberInputSchemaType = {
  findUnique: z.ZodType<Prisma.ResourceMemberFindUniqueArgs>;
  findFirst: z.ZodType<Prisma.ResourceMemberFindFirstArgs>;
  findMany: z.ZodType<Prisma.ResourceMemberFindManyArgs>;
  create: z.ZodType<Prisma.ResourceMemberCreateArgs>;
  createMany: z.ZodType<Prisma.ResourceMemberCreateManyArgs>;
  delete: z.ZodType<Prisma.ResourceMemberDeleteArgs>;
  deleteMany: z.ZodType<Prisma.ResourceMemberDeleteManyArgs>;
  update: z.ZodType<Prisma.ResourceMemberUpdateArgs>;
  updateMany: z.ZodType<Prisma.ResourceMemberUpdateManyArgs>;
  upsert: z.ZodType<Prisma.ResourceMemberUpsertArgs>;
  aggregate: z.ZodType<Prisma.ResourceMemberAggregateArgs>;
  groupBy: z.ZodType<Prisma.ResourceMemberGroupByArgs>;
  count: z.ZodType<Prisma.ResourceMemberCountArgs>;
};

export const ResourceMemberInputSchema = {
  findUnique: z
    .object({
      select: z.lazy(() => ResourceMemberSelectObjectSchema.optional()),
      include: z.lazy(() => ResourceMemberIncludeObjectSchema.optional()),
      where: ResourceMemberWhereUniqueInputObjectSchema
    })
    .strict(),
  findFirst: z
    .object({
      select: z.lazy(() => ResourceMemberSelectObjectSchema.optional()),
      include: z.lazy(() => ResourceMemberIncludeObjectSchema.optional()),
      where: ResourceMemberWhereInputObjectSchema.optional(),
      orderBy: z
        .union([
          ResourceMemberOrderByWithRelationInputObjectSchema,
          ResourceMemberOrderByWithRelationInputObjectSchema.array()
        ])
        .optional(),
      cursor: ResourceMemberWhereUniqueInputObjectSchema.optional(),
      take: z.number().optional(),
      skip: z.number().optional(),
      distinct: z.array(ResourceMemberScalarFieldEnumSchema).optional()
    })
    .strict(),
  findMany: z
    .object({
      select: z.lazy(() => ResourceMemberSelectObjectSchema.optional()),
      include: z.lazy(() => ResourceMemberIncludeObjectSchema.optional()),
      where: ResourceMemberWhereInputObjectSchema.optional(),
      orderBy: z
        .union([
          ResourceMemberOrderByWithRelationInputObjectSchema,
          ResourceMemberOrderByWithRelationInputObjectSchema.array()
        ])
        .optional(),
      cursor: ResourceMemberWhereUniqueInputObjectSchema.optional(),
      take: z.number().optional(),
      skip: z.number().optional(),
      distinct: z.array(ResourceMemberScalarFieldEnumSchema).optional()
    })
    .strict(),
  create: z
    .object({
      select: z.lazy(() => ResourceMemberSelectObjectSchema.optional()),
      include: z.lazy(() => ResourceMemberIncludeObjectSchema.optional()),
      data: z.union([
        ResourceMemberCreateInputObjectSchema,
        ResourceMemberUncheckedCreateInputObjectSchema
      ])
    })
    .strict(),
  createMany: z
    .object({
      data: z.union([
        ResourceMemberCreateManyInputObjectSchema,
        z.array(ResourceMemberCreateManyInputObjectSchema)
      ]),
      skipDuplicates: z.boolean().optional()
    })
    .strict(),
  delete: z
    .object({
      select: z.lazy(() => ResourceMemberSelectObjectSchema.optional()),
      include: z.lazy(() => ResourceMemberIncludeObjectSchema.optional()),
      where: ResourceMemberWhereUniqueInputObjectSchema
    })
    .strict(),
  deleteMany: z
    .object({
      where: ResourceMemberWhereInputObjectSchema.optional()
    })
    .strict(),
  update: z
    .object({
      select: z.lazy(() => ResourceMemberSelectObjectSchema.optional()),
      include: z.lazy(() => ResourceMemberIncludeObjectSchema.optional()),
      data: z.union([
        ResourceMemberUpdateInputObjectSchema,
        ResourceMemberUncheckedUpdateInputObjectSchema
      ]),
      where: ResourceMemberWhereUniqueInputObjectSchema
    })
    .strict(),
  updateMany: z
    .object({
      data: z.union([
        ResourceMemberUpdateManyMutationInputObjectSchema,
        ResourceMemberUncheckedUpdateManyInputObjectSchema
      ]),
      where: ResourceMemberWhereInputObjectSchema.optional()
    })
    .strict(),
  upsert: z
    .object({
      select: z.lazy(() => ResourceMemberSelectObjectSchema.optional()),
      include: z.lazy(() => ResourceMemberIncludeObjectSchema.optional()),
      where: ResourceMemberWhereUniqueInputObjectSchema,
      create: z.union([
        ResourceMemberCreateInputObjectSchema,
        ResourceMemberUncheckedCreateInputObjectSchema
      ]),
      update: z.union([
        ResourceMemberUpdateInputObjectSchema,
        ResourceMemberUncheckedUpdateInputObjectSchema
      ])
    })
    .strict(),
  aggregate: z
    .object({
      where: ResourceMemberWhereInputObjectSchema.optional(),
      orderBy: z
        .union([
          ResourceMemberOrderByWithRelationInputObjectSchema,
          ResourceMemberOrderByWithRelationInputObjectSchema.array()
        ])
        .optional(),
      cursor: ResourceMemberWhereUniqueInputObjectSchema.optional(),
      take: z.number().optional(),
      skip: z.number().optional(),
      _count: z
        .union([z.literal(true), ResourceMemberCountAggregateInputObjectSchema])
        .optional(),
      _min: ResourceMemberMinAggregateInputObjectSchema.optional(),
      _max: ResourceMemberMaxAggregateInputObjectSchema.optional()
    })
    .strict(),
  groupBy: z
    .object({
      where: ResourceMemberWhereInputObjectSchema.optional(),
      orderBy: z
        .union([
          ResourceMemberOrderByWithAggregationInputObjectSchema,
          ResourceMemberOrderByWithAggregationInputObjectSchema.array()
        ])
        .optional(),
      having:
        ResourceMemberScalarWhereWithAggregatesInputObjectSchema.optional(),
      take: z.number().optional(),
      skip: z.number().optional(),
      by: z.array(ResourceMemberScalarFieldEnumSchema),
      _count: z
        .union([z.literal(true), ResourceMemberCountAggregateInputObjectSchema])
        .optional(),
      _min: ResourceMemberMinAggregateInputObjectSchema.optional(),
      _max: ResourceMemberMaxAggregateInputObjectSchema.optional()
    })
    .strict(),
  count: z
    .object({
      where: ResourceMemberWhereInputObjectSchema.optional(),
      orderBy: z
        .union([
          ResourceMemberOrderByWithRelationInputObjectSchema,
          ResourceMemberOrderByWithRelationInputObjectSchema.array()
        ])
        .optional(),
      cursor: ResourceMemberWhereUniqueInputObjectSchema.optional(),
      take: z.number().optional(),
      skip: z.number().optional(),
      distinct: z.array(ResourceMemberScalarFieldEnumSchema).optional(),
      select: z
        .union([z.literal(true), ResourceMemberCountAggregateInputObjectSchema])
        .optional()
    })
    .strict()
} as ResourceMemberInputSchemaType;
