/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import type { Prisma } from '@zenstackhq/runtime/models';

import { UserProfileSelectObjectSchema } from '../objects/UserProfileSelect.schema';
import { UserProfileIncludeObjectSchema } from '../objects/UserProfileInclude.schema';
import { UserProfileWhereUniqueInputObjectSchema } from '../objects/UserProfileWhereUniqueInput.schema';
import { UserProfileWhereInputObjectSchema } from '../objects/UserProfileWhereInput.schema';
import { UserProfileOrderByWithRelationInputObjectSchema } from '../objects/UserProfileOrderByWithRelationInput.schema';
import { UserProfileScalarFieldEnumSchema } from '../enums/UserProfileScalarFieldEnum.schema';
import { UserProfileCreateInputObjectSchema } from '../objects/UserProfileCreateInput.schema';
import { UserProfileUncheckedCreateInputObjectSchema } from '../objects/UserProfileUncheckedCreateInput.schema';
import { UserProfileCreateManyInputObjectSchema } from '../objects/UserProfileCreateManyInput.schema';
import { UserProfileUpdateInputObjectSchema } from '../objects/UserProfileUpdateInput.schema';
import { UserProfileUncheckedUpdateInputObjectSchema } from '../objects/UserProfileUncheckedUpdateInput.schema';
import { UserProfileUpdateManyMutationInputObjectSchema } from '../objects/UserProfileUpdateManyMutationInput.schema';
import { UserProfileUncheckedUpdateManyInputObjectSchema } from '../objects/UserProfileUncheckedUpdateManyInput.schema';
import { UserProfileCountAggregateInputObjectSchema } from '../objects/UserProfileCountAggregateInput.schema';
import { UserProfileMinAggregateInputObjectSchema } from '../objects/UserProfileMinAggregateInput.schema';
import { UserProfileMaxAggregateInputObjectSchema } from '../objects/UserProfileMaxAggregateInput.schema';
import { UserProfileOrderByWithAggregationInputObjectSchema } from '../objects/UserProfileOrderByWithAggregationInput.schema';
import { UserProfileScalarWhereWithAggregatesInputObjectSchema } from '../objects/UserProfileScalarWhereWithAggregatesInput.schema';

type UserProfileInputSchemaType = {
  findUnique: z.ZodType<Prisma.UserProfileFindUniqueArgs>;
  findFirst: z.ZodType<Prisma.UserProfileFindFirstArgs>;
  findMany: z.ZodType<Prisma.UserProfileFindManyArgs>;
  create: z.ZodType<Prisma.UserProfileCreateArgs>;
  createMany: z.ZodType<Prisma.UserProfileCreateManyArgs>;
  delete: z.ZodType<Prisma.UserProfileDeleteArgs>;
  deleteMany: z.ZodType<Prisma.UserProfileDeleteManyArgs>;
  update: z.ZodType<Prisma.UserProfileUpdateArgs>;
  updateMany: z.ZodType<Prisma.UserProfileUpdateManyArgs>;
  upsert: z.ZodType<Prisma.UserProfileUpsertArgs>;
  aggregate: z.ZodType<Prisma.UserProfileAggregateArgs>;
  groupBy: z.ZodType<Prisma.UserProfileGroupByArgs>;
  count: z.ZodType<Prisma.UserProfileCountArgs>;
};

export const UserProfileInputSchema = {
  findUnique: z
    .object({
      select: z.lazy(() => UserProfileSelectObjectSchema.optional()),
      include: z.lazy(() => UserProfileIncludeObjectSchema.optional()),
      where: UserProfileWhereUniqueInputObjectSchema
    })
    .strict(),
  findFirst: z
    .object({
      select: z.lazy(() => UserProfileSelectObjectSchema.optional()),
      include: z.lazy(() => UserProfileIncludeObjectSchema.optional()),
      where: UserProfileWhereInputObjectSchema.optional(),
      orderBy: z
        .union([
          UserProfileOrderByWithRelationInputObjectSchema,
          UserProfileOrderByWithRelationInputObjectSchema.array()
        ])
        .optional(),
      cursor: UserProfileWhereUniqueInputObjectSchema.optional(),
      take: z.number().optional(),
      skip: z.number().optional(),
      distinct: z.array(UserProfileScalarFieldEnumSchema).optional()
    })
    .strict(),
  findMany: z
    .object({
      select: z.lazy(() => UserProfileSelectObjectSchema.optional()),
      include: z.lazy(() => UserProfileIncludeObjectSchema.optional()),
      where: UserProfileWhereInputObjectSchema.optional(),
      orderBy: z
        .union([
          UserProfileOrderByWithRelationInputObjectSchema,
          UserProfileOrderByWithRelationInputObjectSchema.array()
        ])
        .optional(),
      cursor: UserProfileWhereUniqueInputObjectSchema.optional(),
      take: z.number().optional(),
      skip: z.number().optional(),
      distinct: z.array(UserProfileScalarFieldEnumSchema).optional()
    })
    .strict(),
  create: z
    .object({
      select: z.lazy(() => UserProfileSelectObjectSchema.optional()),
      include: z.lazy(() => UserProfileIncludeObjectSchema.optional()),
      data: z.union([
        UserProfileCreateInputObjectSchema,
        UserProfileUncheckedCreateInputObjectSchema
      ])
    })
    .strict(),
  createMany: z
    .object({
      data: z.union([
        UserProfileCreateManyInputObjectSchema,
        z.array(UserProfileCreateManyInputObjectSchema)
      ]),
      skipDuplicates: z.boolean().optional()
    })
    .strict(),
  delete: z
    .object({
      select: z.lazy(() => UserProfileSelectObjectSchema.optional()),
      include: z.lazy(() => UserProfileIncludeObjectSchema.optional()),
      where: UserProfileWhereUniqueInputObjectSchema
    })
    .strict(),
  deleteMany: z
    .object({
      where: UserProfileWhereInputObjectSchema.optional()
    })
    .strict(),
  update: z
    .object({
      select: z.lazy(() => UserProfileSelectObjectSchema.optional()),
      include: z.lazy(() => UserProfileIncludeObjectSchema.optional()),
      data: z.union([
        UserProfileUpdateInputObjectSchema,
        UserProfileUncheckedUpdateInputObjectSchema
      ]),
      where: UserProfileWhereUniqueInputObjectSchema
    })
    .strict(),
  updateMany: z
    .object({
      data: z.union([
        UserProfileUpdateManyMutationInputObjectSchema,
        UserProfileUncheckedUpdateManyInputObjectSchema
      ]),
      where: UserProfileWhereInputObjectSchema.optional()
    })
    .strict(),
  upsert: z
    .object({
      select: z.lazy(() => UserProfileSelectObjectSchema.optional()),
      include: z.lazy(() => UserProfileIncludeObjectSchema.optional()),
      where: UserProfileWhereUniqueInputObjectSchema,
      create: z.union([
        UserProfileCreateInputObjectSchema,
        UserProfileUncheckedCreateInputObjectSchema
      ]),
      update: z.union([
        UserProfileUpdateInputObjectSchema,
        UserProfileUncheckedUpdateInputObjectSchema
      ])
    })
    .strict(),
  aggregate: z
    .object({
      where: UserProfileWhereInputObjectSchema.optional(),
      orderBy: z
        .union([
          UserProfileOrderByWithRelationInputObjectSchema,
          UserProfileOrderByWithRelationInputObjectSchema.array()
        ])
        .optional(),
      cursor: UserProfileWhereUniqueInputObjectSchema.optional(),
      take: z.number().optional(),
      skip: z.number().optional(),
      _count: z
        .union([z.literal(true), UserProfileCountAggregateInputObjectSchema])
        .optional(),
      _min: UserProfileMinAggregateInputObjectSchema.optional(),
      _max: UserProfileMaxAggregateInputObjectSchema.optional()
    })
    .strict(),
  groupBy: z
    .object({
      where: UserProfileWhereInputObjectSchema.optional(),
      orderBy: z
        .union([
          UserProfileOrderByWithAggregationInputObjectSchema,
          UserProfileOrderByWithAggregationInputObjectSchema.array()
        ])
        .optional(),
      having: UserProfileScalarWhereWithAggregatesInputObjectSchema.optional(),
      take: z.number().optional(),
      skip: z.number().optional(),
      by: z.array(UserProfileScalarFieldEnumSchema),
      _count: z
        .union([z.literal(true), UserProfileCountAggregateInputObjectSchema])
        .optional(),
      _min: UserProfileMinAggregateInputObjectSchema.optional(),
      _max: UserProfileMaxAggregateInputObjectSchema.optional()
    })
    .strict(),
  count: z
    .object({
      where: UserProfileWhereInputObjectSchema.optional(),
      orderBy: z
        .union([
          UserProfileOrderByWithRelationInputObjectSchema,
          UserProfileOrderByWithRelationInputObjectSchema.array()
        ])
        .optional(),
      cursor: UserProfileWhereUniqueInputObjectSchema.optional(),
      take: z.number().optional(),
      skip: z.number().optional(),
      distinct: z.array(UserProfileScalarFieldEnumSchema).optional(),
      select: z
        .union([z.literal(true), UserProfileCountAggregateInputObjectSchema])
        .optional()
    })
    .strict()
} as UserProfileInputSchemaType;
