export enum AuthErrorCode {
  // Authentication
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  SESSION_REQUIRED = 'SESSION_REQUIRED',
  INVALID_SESSION_DATA = 'INVALID_SESSION_DATA',

  // User
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_USER_DATA = 'INVALID_USER_DATA',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',

  // Verification
  VERIFICATION_ERROR = 'VERIFICATION_ERROR',
  VERIFICATION_FAILED = 'VERIFICATION_FAILED',
  VERIFICATION_EXPIRED = 'VERIFICATION_EXPIRED',
  INVALID_CODE = 'INVALID_CODE',
  CODE_EXPIRED = 'CODE_EXPIRED',

  // Token
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND',
  TOKEN_ALREADY_USED = 'TOKEN_ALREADY_USED',
  INVALID_TOKEN_TYPE = 'INVALID_TOKEN_TYPE',
  TOKEN_GENERATION_FAILED = 'TOKEN_GENERATION_FAILED',

  // Rate Limiting
  RATE_LIMITED = 'RATE_LIMITED',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  TOO_MANY_ATTEMPTS = 'TOO_MANY_ATTEMPTS',

  // Workspace
  WORKSPACE_ACCESS_DENIED = 'WORKSPACE_ACCESS_DENIED',
  WORKSPACE_STATE_ERROR = 'WORKSPACE_STATE_ERROR',
  INVALID_WORKSPACE = 'INVALID_WORKSPACE',

  // Permissions
  PERMISSION_DENIED = 'PERMISSION_DENIED',

  // Validation
  INVALID_EMAIL = 'INVALID_EMAIL',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INVALID_IDENTIFIER = 'INVALID_IDENTIFIER',

  // Service
  SERVICE_INITIALIZATION_FAILED = 'SERVICE_INITIALIZATION_FAILED',
  DATABASE_ERROR = 'DATABASE_ERROR'
}
