export type PermissionType =
  | 'PLATFORM_ADMIN'
  | 'PLATFORM_USER'
  | 'WORKSPACE_ADMIN'
  | 'WORKSPACE_EDITOR'
  | 'WORKSPACE_VIEWER'
  | 'CLIENT_ADMIN'
  | 'CLIENT_EDITOR'
  | 'CLIENT_VIEWER'
  | 'LOCATION_ADMIN'
  | 'LOCATION_EDITOR'
  | 'LOCATION_VIEWER';
