/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const AuditLogScalarFieldEnumSchema = z.enum([
  'createdAt',
  'updatedAt',
  'createdBy',
  'updatedBy',
  'id',
  'eventType',
  'resourceType',
  'resourceId',
  'userId',
  'severity',
  'description',
  'metadata',
  'success'
]);
