/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const AuthenticationMethodSchema = z.enum([
  'PASSWORD',
  'PHONE_OTP',
  'MAGIC_LINK',
  'OAUTH',
  'WEBAUTHN'
]);
