/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const IncidentStatusSchema = z.enum([
  'REPORTED',
  'INVESTIGATING',
  'IN_PROGRESS',
  'RESOLVED',
  'CLOSED'
]);
