/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const OAuthScopeSchema = z.enum([
  'EMAIL',
  'PROFILE',
  'OPENID',
  'CALENDAR',
  'DRIVE'
]);
