/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const OAuthProviderSchema = z.enum([
  'GOOGLE',
  'GITHUB',
  'MICROSOFT',
  'APPLE'
]);
