/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const UserProfileScalarFieldEnumSchema = z.enum([
  'createdAt',
  'updatedAt',
  'createdBy',
  'updatedBy',
  'id',
  'firstName',
  'lastName',
  'userId'
]);
