/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const WorkspaceScalarFieldEnumSchema = z.enum([
  'createdAt',
  'updatedAt',
  'createdBy',
  'updatedBy',
  'id',
  'name',
  'slug',
  'logoUrl',
  'description',
  'status',
  'settings',
  'address',
  'features',
  'ownerId'
]);
