/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { AuditLogEventTypeSchema } from '../enums/AuditLogEventType.schema';
import { AuditLogResourceTypeSchema } from '../enums/AuditLogResourceType.schema';
import { AuditSeverityLevelSchema } from '../enums/AuditSeverityLevel.schema';
import { NullableJsonNullValueInputSchema } from '../enums/NullableJsonNullValueInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

const literalSchema = z.union([z.string(), z.number(), z.boolean()]);
const jsonSchema: z.ZodType<Prisma.InputJsonValue> = z.lazy(() =>
  z.union([
    literalSchema,
    z.array(jsonSchema.nullable()),
    z.record(jsonSchema.nullable())
  ])
);

type SchemaType = z.ZodType<Prisma.AuditLogCreateManyInput>;
export const AuditLogCreateManyInputObjectSchema: SchemaType = z
  .object({
    createdAt: z.union([z.date().optional(), z.string().datetime().optional()]),
    updatedAt: z.union([z.date().optional(), z.string().datetime().optional()]),
    createdBy: z.union([z.string(), z.null()]).optional().nullable(),
    updatedBy: z.union([z.string(), z.null()]).optional().nullable(),
    id: z.string().optional(),
    eventType: z.lazy(() => AuditLogEventTypeSchema),
    resourceType: z.lazy(() => AuditLogResourceTypeSchema),
    resourceId: z.string(),
    userId: z.string(),
    severity: z.lazy(() => AuditSeverityLevelSchema).optional(),
    description: z.string(),
    metadata: z
      .union([z.lazy(() => NullableJsonNullValueInputSchema), jsonSchema])
      .optional(),
    success: z.boolean().optional()
  })
  .strict() as SchemaType;
