/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.AuditLogMinAggregateInputType>;
export const AuditLogMinAggregateInputObjectSchema: SchemaType = z
  .object({
    createdAt: z.literal(true).optional(),
    updatedAt: z.literal(true).optional(),
    createdBy: z.literal(true).optional(),
    updatedBy: z.literal(true).optional(),
    id: z.literal(true).optional(),
    eventType: z.literal(true).optional(),
    resourceType: z.literal(true).optional(),
    resourceId: z.literal(true).optional(),
    userId: z.literal(true).optional(),
    severity: z.literal(true).optional(),
    description: z.literal(true).optional(),
    success: z.literal(true).optional()
  })
  .strict() as SchemaType;
