/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { DateTimeFieldUpdateOperationsInputObjectSchema } from './DateTimeFieldUpdateOperationsInput.schema';
import { NullableStringFieldUpdateOperationsInputObjectSchema } from './NullableStringFieldUpdateOperationsInput.schema';
import { StringFieldUpdateOperationsInputObjectSchema } from './StringFieldUpdateOperationsInput.schema';
import { AuditLogEventTypeSchema } from '../enums/AuditLogEventType.schema';
import { EnumAuditLogEventTypeFieldUpdateOperationsInputObjectSchema } from './EnumAuditLogEventTypeFieldUpdateOperationsInput.schema';
import { AuditLogResourceTypeSchema } from '../enums/AuditLogResourceType.schema';
import { EnumAuditLogResourceTypeFieldUpdateOperationsInputObjectSchema } from './EnumAuditLogResourceTypeFieldUpdateOperationsInput.schema';
import { AuditSeverityLevelSchema } from '../enums/AuditSeverityLevel.schema';
import { EnumAuditSeverityLevelFieldUpdateOperationsInputObjectSchema } from './EnumAuditSeverityLevelFieldUpdateOperationsInput.schema';
import { NullableJsonNullValueInputSchema } from '../enums/NullableJsonNullValueInput.schema';
import { BoolFieldUpdateOperationsInputObjectSchema } from './BoolFieldUpdateOperationsInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

const literalSchema = z.union([z.string(), z.number(), z.boolean()]);
const jsonSchema: z.ZodType<Prisma.InputJsonValue> = z.lazy(() =>
  z.union([
    literalSchema,
    z.array(jsonSchema.nullable()),
    z.record(jsonSchema.nullable())
  ])
);

type SchemaType = z.ZodType<Prisma.AuditLogUncheckedUpdateInput>;
export const AuditLogUncheckedUpdateInputObjectSchema: SchemaType = z
  .object({
    createdAt: z
      .union([
        z.union([z.date(), z.string().datetime().optional()]),
        z.lazy(() => DateTimeFieldUpdateOperationsInputObjectSchema)
      ])
      .optional(),
    updatedAt: z
      .union([
        z.union([z.date(), z.string().datetime().optional()]),
        z.lazy(() => DateTimeFieldUpdateOperationsInputObjectSchema)
      ])
      .optional(),
    createdBy: z
      .union([
        z.string(),
        z.lazy(() => NullableStringFieldUpdateOperationsInputObjectSchema),
        z.null()
      ])
      .optional()
      .nullable(),
    updatedBy: z
      .union([
        z.string(),
        z.lazy(() => NullableStringFieldUpdateOperationsInputObjectSchema),
        z.null()
      ])
      .optional()
      .nullable(),
    id: z
      .union([
        z.string(),
        z.lazy(() => StringFieldUpdateOperationsInputObjectSchema)
      ])
      .optional(),
    eventType: z
      .union([
        z.lazy(() => AuditLogEventTypeSchema),
        z.lazy(
          () => EnumAuditLogEventTypeFieldUpdateOperationsInputObjectSchema
        )
      ])
      .optional(),
    resourceType: z
      .union([
        z.lazy(() => AuditLogResourceTypeSchema),
        z.lazy(
          () => EnumAuditLogResourceTypeFieldUpdateOperationsInputObjectSchema
        )
      ])
      .optional(),
    resourceId: z
      .union([
        z.string(),
        z.lazy(() => StringFieldUpdateOperationsInputObjectSchema)
      ])
      .optional(),
    userId: z
      .union([
        z.string(),
        z.lazy(() => StringFieldUpdateOperationsInputObjectSchema)
      ])
      .optional(),
    severity: z
      .union([
        z.lazy(() => AuditSeverityLevelSchema),
        z.lazy(
          () => EnumAuditSeverityLevelFieldUpdateOperationsInputObjectSchema
        )
      ])
      .optional(),
    description: z
      .union([
        z.string(),
        z.lazy(() => StringFieldUpdateOperationsInputObjectSchema)
      ])
      .optional(),
    metadata: z
      .union([z.lazy(() => NullableJsonNullValueInputSchema), jsonSchema])
      .optional(),
    success: z
      .union([
        z.boolean(),
        z.lazy(() => BoolFieldUpdateOperationsInputObjectSchema)
      ])
      .optional()
  })
  .strict() as SchemaType;
