/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { AuditLogWhereInputObjectSchema } from './AuditLogWhereInput.schema';
import { DateTimeFilterObjectSchema } from './DateTimeFilter.schema';
import { StringNullableFilterObjectSchema } from './StringNullableFilter.schema';
import { EnumAuditLogEventTypeFilterObjectSchema } from './EnumAuditLogEventTypeFilter.schema';
import { AuditLogEventTypeSchema } from '../enums/AuditLogEventType.schema';
import { EnumAuditLogResourceTypeFilterObjectSchema } from './EnumAuditLogResourceTypeFilter.schema';
import { AuditLogResourceTypeSchema } from '../enums/AuditLogResourceType.schema';
import { StringFilterObjectSchema } from './StringFilter.schema';
import { EnumAuditSeverityLevelFilterObjectSchema } from './EnumAuditSeverityLevelFilter.schema';
import { AuditSeverityLevelSchema } from '../enums/AuditSeverityLevel.schema';
import { JsonNullableFilterObjectSchema } from './JsonNullableFilter.schema';
import { BoolFilterObjectSchema } from './BoolFilter.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.AuditLogWhereUniqueInput>;
export const AuditLogWhereUniqueInputObjectSchema: SchemaType = z
  .object({
    id: z.string().optional(),
    AND: z
      .union([
        z.lazy(() => AuditLogWhereInputObjectSchema),
        z.lazy(() => AuditLogWhereInputObjectSchema).array()
      ])
      .optional(),
    OR: z
      .lazy(() => AuditLogWhereInputObjectSchema)
      .array()
      .optional(),
    NOT: z
      .union([
        z.lazy(() => AuditLogWhereInputObjectSchema),
        z.lazy(() => AuditLogWhereInputObjectSchema).array()
      ])
      .optional(),
    createdAt: z
      .union([
        z.lazy(() => DateTimeFilterObjectSchema),
        z.union([z.date(), z.string().datetime().optional()])
      ])
      .optional(),
    updatedAt: z
      .union([
        z.lazy(() => DateTimeFilterObjectSchema),
        z.union([z.date(), z.string().datetime().optional()])
      ])
      .optional(),
    createdBy: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    updatedBy: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    eventType: z
      .union([
        z.lazy(() => EnumAuditLogEventTypeFilterObjectSchema),
        z.lazy(() => AuditLogEventTypeSchema)
      ])
      .optional(),
    resourceType: z
      .union([
        z.lazy(() => EnumAuditLogResourceTypeFilterObjectSchema),
        z.lazy(() => AuditLogResourceTypeSchema)
      ])
      .optional(),
    resourceId: z
      .union([z.lazy(() => StringFilterObjectSchema), z.string()])
      .optional(),
    userId: z
      .union([z.lazy(() => StringFilterObjectSchema), z.string()])
      .optional(),
    severity: z
      .union([
        z.lazy(() => EnumAuditSeverityLevelFilterObjectSchema),
        z.lazy(() => AuditSeverityLevelSchema)
      ])
      .optional(),
    description: z
      .union([z.lazy(() => StringFilterObjectSchema), z.string()])
      .optional(),
    metadata: z.lazy(() => JsonNullableFilterObjectSchema).optional(),
    success: z
      .union([z.lazy(() => BoolFilterObjectSchema), z.boolean()])
      .optional()
  })
  .strict() as SchemaType;
