/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { AuthSessionCreateWithoutUserInputObjectSchema } from './AuthSessionCreateWithoutUserInput.schema';
import { AuthSessionUncheckedCreateWithoutUserInputObjectSchema } from './AuthSessionUncheckedCreateWithoutUserInput.schema';
import { AuthSessionCreateOrConnectWithoutUserInputObjectSchema } from './AuthSessionCreateOrConnectWithoutUserInput.schema';
import { AuthSessionCreateManyUserInputEnvelopeObjectSchema } from './AuthSessionCreateManyUserInputEnvelope.schema';
import { AuthSessionWhereUniqueInputObjectSchema } from './AuthSessionWhereUniqueInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.AuthSessionUncheckedCreateNestedManyWithoutUserInput>;
export const AuthSessionUncheckedCreateNestedManyWithoutUserInputObjectSchema: SchemaType =
  z
    .object({
      create: z
        .union([
          z.lazy(() => AuthSessionCreateWithoutUserInputObjectSchema),
          z.lazy(() => AuthSessionCreateWithoutUserInputObjectSchema).array(),
          z.lazy(() => AuthSessionUncheckedCreateWithoutUserInputObjectSchema),
          z
            .lazy(() => AuthSessionUncheckedCreateWithoutUserInputObjectSchema)
            .array()
        ])
        .optional(),
      connectOrCreate: z
        .union([
          z.lazy(() => AuthSessionCreateOrConnectWithoutUserInputObjectSchema),
          z
            .lazy(() => AuthSessionCreateOrConnectWithoutUserInputObjectSchema)
            .array()
        ])
        .optional(),
      createMany: z
        .lazy(() => AuthSessionCreateManyUserInputEnvelopeObjectSchema)
        .optional(),
      connect: z
        .union([
          z.lazy(() => AuthSessionWhereUniqueInputObjectSchema),
          z.lazy(() => AuthSessionWhereUniqueInputObjectSchema).array()
        ])
        .optional()
    })
    .strict() as SchemaType;
