/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.AuthSessionMinAggregateInputType>;
export const AuthSessionMinAggregateInputObjectSchema: SchemaType = z
  .object({
    createdAt: z.literal(true).optional(),
    updatedAt: z.literal(true).optional(),
    createdBy: z.literal(true).optional(),
    updatedBy: z.literal(true).optional(),
    id: z.literal(true).optional(),
    token: z.literal(true).optional(),
    expiresAt: z.literal(true).optional(),
    userId: z.literal(true).optional(),
    ipAddress: z.literal(true).optional(),
    userAgent: z.literal(true).optional(),
    lastActiveAt: z.literal(true).optional(),
    isRevoked: z.literal(true).optional(),
    deviceId: z.literal(true).optional(),
    deviceName: z.literal(true).optional(),
    sessionType: z.literal(true).optional(),
    mfaVerified: z.literal(true).optional(),
    failedAttempts: z.literal(true).optional(),
    refreshToken: z.literal(true).optional()
  })
  .strict() as SchemaType;
