/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { AuthSessionWhereInputObjectSchema } from './AuthSessionWhereInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.AuthSessionListRelationFilter>;
export const AuthSessionListRelationFilterObjectSchema: SchemaType = z
  .object({
    every: z.lazy(() => AuthSessionWhereInputObjectSchema).optional(),
    some: z.lazy(() => AuthSessionWhereInputObjectSchema).optional(),
    none: z.lazy(() => AuthSessionWhereInputObjectSchema).optional()
  })
  .strict() as SchemaType;
