/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { DateTimeWithAggregatesFilterObjectSchema } from './DateTimeWithAggregatesFilter.schema';
import { StringNullableWithAggregatesFilterObjectSchema } from './StringNullableWithAggregatesFilter.schema';
import { StringWithAggregatesFilterObjectSchema } from './StringWithAggregatesFilter.schema';
import { EnumEntityStatusWithAggregatesFilterObjectSchema } from './EnumEntityStatusWithAggregatesFilter.schema';
import { EntityStatusSchema } from '../enums/EntityStatus.schema';
import { JsonNullableWithAggregatesFilterObjectSchema } from './JsonNullableWithAggregatesFilter.schema';
import { IntNullableWithAggregatesFilterObjectSchema } from './IntNullableWithAggregatesFilter.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ClientScalarWhereWithAggregatesInput>;
export const ClientScalarWhereWithAggregatesInputObjectSchema: SchemaType = z
  .object({
    AND: z
      .union([
        z.lazy(() => ClientScalarWhereWithAggregatesInputObjectSchema),
        z.lazy(() => ClientScalarWhereWithAggregatesInputObjectSchema).array()
      ])
      .optional(),
    OR: z
      .lazy(() => ClientScalarWhereWithAggregatesInputObjectSchema)
      .array()
      .optional(),
    NOT: z
      .union([
        z.lazy(() => ClientScalarWhereWithAggregatesInputObjectSchema),
        z.lazy(() => ClientScalarWhereWithAggregatesInputObjectSchema).array()
      ])
      .optional(),
    createdAt: z
      .union([
        z.lazy(() => DateTimeWithAggregatesFilterObjectSchema),
        z.union([z.date(), z.string().datetime().optional()])
      ])
      .optional(),
    updatedAt: z
      .union([
        z.lazy(() => DateTimeWithAggregatesFilterObjectSchema),
        z.union([z.date(), z.string().datetime().optional()])
      ])
      .optional(),
    createdBy: z
      .union([
        z.lazy(() => StringNullableWithAggregatesFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    updatedBy: z
      .union([
        z.lazy(() => StringNullableWithAggregatesFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    id: z
      .union([z.lazy(() => StringWithAggregatesFilterObjectSchema), z.string()])
      .optional(),
    name: z
      .union([z.lazy(() => StringWithAggregatesFilterObjectSchema), z.string()])
      .optional(),
    description: z
      .union([
        z.lazy(() => StringNullableWithAggregatesFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    logoUrl: z
      .union([
        z.lazy(() => StringNullableWithAggregatesFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    status: z
      .union([
        z.lazy(() => EnumEntityStatusWithAggregatesFilterObjectSchema),
        z.lazy(() => EntityStatusSchema)
      ])
      .optional(),
    settings: z
      .lazy(() => JsonNullableWithAggregatesFilterObjectSchema)
      .optional(),
    address: z
      .lazy(() => JsonNullableWithAggregatesFilterObjectSchema)
      .optional(),
    workspaceId: z
      .union([z.lazy(() => StringWithAggregatesFilterObjectSchema), z.string()])
      .optional(),
    maxPatrols: z
      .union([
        z.lazy(() => IntNullableWithAggregatesFilterObjectSchema),
        z.number(),
        z.null()
      ])
      .optional()
      .nullable()
  })
  .strict() as SchemaType;
