/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { ClientUpdateWithoutMembersInputObjectSchema } from './ClientUpdateWithoutMembersInput.schema';
import { ClientUncheckedUpdateWithoutMembersInputObjectSchema } from './ClientUncheckedUpdateWithoutMembersInput.schema';
import { ClientCreateWithoutMembersInputObjectSchema } from './ClientCreateWithoutMembersInput.schema';
import { ClientUncheckedCreateWithoutMembersInputObjectSchema } from './ClientUncheckedCreateWithoutMembersInput.schema';
import { ClientWhereInputObjectSchema } from './ClientWhereInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ClientUpsertWithoutMembersInput>;
export const ClientUpsertWithoutMembersInputObjectSchema: SchemaType = z
  .object({
    update: z.union([
      z.lazy(() => ClientUpdateWithoutMembersInputObjectSchema),
      z.lazy(() => ClientUncheckedUpdateWithoutMembersInputObjectSchema)
    ]),
    create: z.union([
      z.lazy(() => ClientCreateWithoutMembersInputObjectSchema),
      z.lazy(() => ClientUncheckedCreateWithoutMembersInputObjectSchema)
    ]),
    where: z.lazy(() => ClientWhereInputObjectSchema).optional()
  })
  .strict() as SchemaType;
