/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { WorkspaceDefaultArgsObjectSchema } from './WorkspaceDefaultArgs.schema';
import { PatrolInputSchema } from '../input/PatrolInput.schema';
import { IncidentInputSchema } from '../input/IncidentInput.schema';
import { ResourceMemberInputSchema } from '../input/ResourceMemberInput.schema';
import { ClientCountOutputTypeDefaultArgsObjectSchema } from './ClientCountOutputTypeDefaultArgs.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ClientSelect>;
export const ClientSelectObjectSchema: SchemaType = z
  .object({
    createdAt: z.boolean().optional(),
    updatedAt: z.boolean().optional(),
    createdBy: z.boolean().optional(),
    updatedBy: z.boolean().optional(),
    id: z.boolean().optional(),
    name: z.boolean().optional(),
    description: z.boolean().optional(),
    logoUrl: z.boolean().optional(),
    status: z.boolean().optional(),
    settings: z.boolean().optional(),
    address: z.boolean().optional(),
    workspace: z
      .union([z.boolean(), z.lazy(() => WorkspaceDefaultArgsObjectSchema)])
      .optional(),
    workspaceId: z.boolean().optional(),
    patrols: z
      .union([z.boolean(), z.lazy(() => PatrolInputSchema.findMany)])
      .optional(),
    maxPatrols: z.boolean().optional(),
    incidents: z
      .union([z.boolean(), z.lazy(() => IncidentInputSchema.findMany)])
      .optional(),
    members: z
      .union([z.boolean(), z.lazy(() => ResourceMemberInputSchema.findMany)])
      .optional(),
    _count: z
      .union([
        z.boolean(),
        z.lazy(() => ClientCountOutputTypeDefaultArgsObjectSchema)
      ])
      .optional()
  })
  .strict() as SchemaType;
