/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { UserSettingsSchema } from '../models/UserSettings.schema';

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { ClientWhereInputObjectSchema } from './ClientWhereInput.schema';
import { ClientUpdateWithoutIncidentsInputObjectSchema } from './ClientUpdateWithoutIncidentsInput.schema';
import { ClientUncheckedUpdateWithoutIncidentsInputObjectSchema } from './ClientUncheckedUpdateWithoutIncidentsInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.ClientUpdateToOneWithWhereWithoutIncidentsInput>;
export const ClientUpdateToOneWithWhereWithoutIncidentsInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => ClientWhereInputObjectSchema).optional(),
      data: z.union([
        z.lazy(() => ClientUpdateWithoutIncidentsInputObjectSchema),
        z.lazy(() => ClientUncheckedUpdateWithoutIncidentsInputObjectSchema)
      ])
    })
    .strict() as SchemaType;
