/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { UserSettingsSchema } from '../models/UserSettings.schema';

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { EntityStatusSchema } from '../enums/EntityStatus.schema';
import { WorkspaceCreateNestedOneWithoutClientsInputObjectSchema } from './WorkspaceCreateNestedOneWithoutClientsInput.schema';
import { PatrolCreateNestedManyWithoutClientInputObjectSchema } from './PatrolCreateNestedManyWithoutClientInput.schema';
import { IncidentCreateNestedManyWithoutClientInputObjectSchema } from './IncidentCreateNestedManyWithoutClientInput.schema';
import { ResourceMemberCreateNestedManyWithoutClientInputObjectSchema } from './ResourceMemberCreateNestedManyWithoutClientInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ClientCreateInput>;
export const ClientCreateInputObjectSchema: SchemaType = z
  .object({
    createdAt: z.union([z.date().optional(), z.string().datetime().optional()]),
    updatedAt: z.union([z.date().optional(), z.string().datetime().optional()]),
    createdBy: z.union([z.string(), z.null()]).optional().nullable(),
    updatedBy: z.union([z.string(), z.null()]).optional().nullable(),
    id: z.string().optional(),
    name: z.string(),
    description: z.union([z.string(), z.null()]).optional().nullable(),
    logoUrl: z.union([z.string(), z.null()]).optional().nullable(),
    status: z.lazy(() => EntityStatusSchema).optional(),
    settings: z.lazy(() => UserSettingsSchema),
    address: z.lazy(() => GooglePlacesAutocompleteSchema),
    maxPatrols: z.union([z.number(), z.null()]).optional().nullable(),
    workspace: z.lazy(
      () => WorkspaceCreateNestedOneWithoutClientsInputObjectSchema
    ),
    patrols: z
      .lazy(() => PatrolCreateNestedManyWithoutClientInputObjectSchema)
      .optional(),
    incidents: z
      .lazy(() => IncidentCreateNestedManyWithoutClientInputObjectSchema)
      .optional(),
    members: z
      .lazy(() => ResourceMemberCreateNestedManyWithoutClientInputObjectSchema)
      .optional()
  })
  .strict() as SchemaType;
