/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { UserSettingsSchema } from '../models/UserSettings.schema';

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { ClientCreateWithoutIncidentsInputObjectSchema } from './ClientCreateWithoutIncidentsInput.schema';
import { ClientUncheckedCreateWithoutIncidentsInputObjectSchema } from './ClientUncheckedCreateWithoutIncidentsInput.schema';
import { ClientCreateOrConnectWithoutIncidentsInputObjectSchema } from './ClientCreateOrConnectWithoutIncidentsInput.schema';
import { ClientUpsertWithoutIncidentsInputObjectSchema } from './ClientUpsertWithoutIncidentsInput.schema';
import { ClientWhereUniqueInputObjectSchema } from './ClientWhereUniqueInput.schema';
import { ClientUpdateToOneWithWhereWithoutIncidentsInputObjectSchema } from './ClientUpdateToOneWithWhereWithoutIncidentsInput.schema';
import { ClientUpdateWithoutIncidentsInputObjectSchema } from './ClientUpdateWithoutIncidentsInput.schema';
import { ClientUncheckedUpdateWithoutIncidentsInputObjectSchema } from './ClientUncheckedUpdateWithoutIncidentsInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.ClientUpdateOneRequiredWithoutIncidentsNestedInput>;
export const ClientUpdateOneRequiredWithoutIncidentsNestedInputObjectSchema: SchemaType =
  z
    .object({
      create: z
        .union([
          z.lazy(() => ClientCreateWithoutIncidentsInputObjectSchema),
          z.lazy(() => ClientUncheckedCreateWithoutIncidentsInputObjectSchema)
        ])
        .optional(),
      connectOrCreate: z
        .lazy(() => ClientCreateOrConnectWithoutIncidentsInputObjectSchema)
        .optional(),
      upsert: z
        .lazy(() => ClientUpsertWithoutIncidentsInputObjectSchema)
        .optional(),
      connect: z.lazy(() => ClientWhereUniqueInputObjectSchema).optional(),
      update: z
        .union([
          z.lazy(
            () => ClientUpdateToOneWithWhereWithoutIncidentsInputObjectSchema
          ),
          z.lazy(() => ClientUpdateWithoutIncidentsInputObjectSchema),
          z.lazy(() => ClientUncheckedUpdateWithoutIncidentsInputObjectSchema)
        ])
        .optional()
    })
    .strict() as SchemaType;
