/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { UserSettingsSchema } from '../models/UserSettings.schema';

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { ClientWhereUniqueInputObjectSchema } from './ClientWhereUniqueInput.schema';
import { ClientCreateWithoutPatrolsInputObjectSchema } from './ClientCreateWithoutPatrolsInput.schema';
import { ClientUncheckedCreateWithoutPatrolsInputObjectSchema } from './ClientUncheckedCreateWithoutPatrolsInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ClientCreateOrConnectWithoutPatrolsInput>;
export const ClientCreateOrConnectWithoutPatrolsInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => ClientWhereUniqueInputObjectSchema),
      create: z.union([
        z.lazy(() => ClientCreateWithoutPatrolsInputObjectSchema),
        z.lazy(() => ClientUncheckedCreateWithoutPatrolsInputObjectSchema)
      ])
    })
    .strict() as SchemaType;
