/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { SortOrderSchema } from '../enums/SortOrder.schema';
import { SortOrderInputObjectSchema } from './SortOrderInput.schema';
import { WorkspaceOrderByWithRelationInputObjectSchema } from './WorkspaceOrderByWithRelationInput.schema';
import { PatrolOrderByRelationAggregateInputObjectSchema } from './PatrolOrderByRelationAggregateInput.schema';
import { IncidentOrderByRelationAggregateInputObjectSchema } from './IncidentOrderByRelationAggregateInput.schema';
import { ResourceMemberOrderByRelationAggregateInputObjectSchema } from './ResourceMemberOrderByRelationAggregateInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ClientOrderByWithRelationInput>;
export const ClientOrderByWithRelationInputObjectSchema: SchemaType = z
  .object({
    createdAt: z.lazy(() => SortOrderSchema).optional(),
    updatedAt: z.lazy(() => SortOrderSchema).optional(),
    createdBy: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    updatedBy: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    id: z.lazy(() => SortOrderSchema).optional(),
    name: z.lazy(() => SortOrderSchema).optional(),
    description: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    logoUrl: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    status: z.lazy(() => SortOrderSchema).optional(),
    settings: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    address: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    workspaceId: z.lazy(() => SortOrderSchema).optional(),
    maxPatrols: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    workspace: z
      .lazy(() => WorkspaceOrderByWithRelationInputObjectSchema)
      .optional(),
    patrols: z
      .lazy(() => PatrolOrderByRelationAggregateInputObjectSchema)
      .optional(),
    incidents: z
      .lazy(() => IncidentOrderByRelationAggregateInputObjectSchema)
      .optional(),
    members: z
      .lazy(() => ResourceMemberOrderByRelationAggregateInputObjectSchema)
      .optional()
  })
  .strict() as SchemaType;
