/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { UserSettingsSchema } from '../models/UserSettings.schema';

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { ClientCreateWithoutMembersInputObjectSchema } from './ClientCreateWithoutMembersInput.schema';
import { ClientUncheckedCreateWithoutMembersInputObjectSchema } from './ClientUncheckedCreateWithoutMembersInput.schema';
import { ClientCreateOrConnectWithoutMembersInputObjectSchema } from './ClientCreateOrConnectWithoutMembersInput.schema';
import { ClientUpsertWithoutMembersInputObjectSchema } from './ClientUpsertWithoutMembersInput.schema';
import { ClientWhereInputObjectSchema } from './ClientWhereInput.schema';
import { ClientWhereUniqueInputObjectSchema } from './ClientWhereUniqueInput.schema';
import { ClientUpdateToOneWithWhereWithoutMembersInputObjectSchema } from './ClientUpdateToOneWithWhereWithoutMembersInput.schema';
import { ClientUpdateWithoutMembersInputObjectSchema } from './ClientUpdateWithoutMembersInput.schema';
import { ClientUncheckedUpdateWithoutMembersInputObjectSchema } from './ClientUncheckedUpdateWithoutMembersInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ClientUpdateOneWithoutMembersNestedInput>;
export const ClientUpdateOneWithoutMembersNestedInputObjectSchema: SchemaType =
  z
    .object({
      create: z
        .union([
          z.lazy(() => ClientCreateWithoutMembersInputObjectSchema),
          z.lazy(() => ClientUncheckedCreateWithoutMembersInputObjectSchema)
        ])
        .optional(),
      connectOrCreate: z
        .lazy(() => ClientCreateOrConnectWithoutMembersInputObjectSchema)
        .optional(),
      upsert: z
        .lazy(() => ClientUpsertWithoutMembersInputObjectSchema)
        .optional(),
      disconnect: z
        .union([z.boolean(), z.lazy(() => ClientWhereInputObjectSchema)])
        .optional(),
      delete: z
        .union([z.boolean(), z.lazy(() => ClientWhereInputObjectSchema)])
        .optional(),
      connect: z.lazy(() => ClientWhereUniqueInputObjectSchema).optional(),
      update: z
        .union([
          z.lazy(
            () => ClientUpdateToOneWithWhereWithoutMembersInputObjectSchema
          ),
          z.lazy(() => ClientUpdateWithoutMembersInputObjectSchema),
          z.lazy(() => ClientUncheckedUpdateWithoutMembersInputObjectSchema)
        ])
        .optional()
    })
    .strict() as SchemaType;
