/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { ClientWorkspaceIdNameCompoundUniqueInputObjectSchema } from './ClientWorkspaceIdNameCompoundUniqueInput.schema';
import { ClientWhereInputObjectSchema } from './ClientWhereInput.schema';
import { DateTimeFilterObjectSchema } from './DateTimeFilter.schema';
import { StringNullableFilterObjectSchema } from './StringNullableFilter.schema';
import { StringFilterObjectSchema } from './StringFilter.schema';
import { EnumEntityStatusFilterObjectSchema } from './EnumEntityStatusFilter.schema';
import { EntityStatusSchema } from '../enums/EntityStatus.schema';
import { JsonNullableFilterObjectSchema } from './JsonNullableFilter.schema';
import { IntNullableFilterObjectSchema } from './IntNullableFilter.schema';
import { WorkspaceScalarRelationFilterObjectSchema } from './WorkspaceScalarRelationFilter.schema';
import { WorkspaceWhereInputObjectSchema } from './WorkspaceWhereInput.schema';
import { PatrolListRelationFilterObjectSchema } from './PatrolListRelationFilter.schema';
import { IncidentListRelationFilterObjectSchema } from './IncidentListRelationFilter.schema';
import { ResourceMemberListRelationFilterObjectSchema } from './ResourceMemberListRelationFilter.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ClientWhereUniqueInput>;
export const ClientWhereUniqueInputObjectSchema: SchemaType = z
  .object({
    id: z.string().optional(),
    workspaceId_name: z
      .lazy(() => ClientWorkspaceIdNameCompoundUniqueInputObjectSchema)
      .optional(),
    AND: z
      .union([
        z.lazy(() => ClientWhereInputObjectSchema),
        z.lazy(() => ClientWhereInputObjectSchema).array()
      ])
      .optional(),
    OR: z
      .lazy(() => ClientWhereInputObjectSchema)
      .array()
      .optional(),
    NOT: z
      .union([
        z.lazy(() => ClientWhereInputObjectSchema),
        z.lazy(() => ClientWhereInputObjectSchema).array()
      ])
      .optional(),
    createdAt: z
      .union([
        z.lazy(() => DateTimeFilterObjectSchema),
        z.union([z.date(), z.string().datetime().optional()])
      ])
      .optional(),
    updatedAt: z
      .union([
        z.lazy(() => DateTimeFilterObjectSchema),
        z.union([z.date(), z.string().datetime().optional()])
      ])
      .optional(),
    createdBy: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    updatedBy: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    name: z
      .union([z.lazy(() => StringFilterObjectSchema), z.string()])
      .optional(),
    description: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    logoUrl: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    status: z
      .union([
        z.lazy(() => EnumEntityStatusFilterObjectSchema),
        z.lazy(() => EntityStatusSchema)
      ])
      .optional(),
    settings: z.lazy(() => JsonNullableFilterObjectSchema).optional(),
    address: z.lazy(() => JsonNullableFilterObjectSchema).optional(),
    workspaceId: z
      .union([z.lazy(() => StringFilterObjectSchema), z.string()])
      .optional(),
    maxPatrols: z
      .union([
        z.lazy(() => IntNullableFilterObjectSchema),
        z.number(),
        z.null()
      ])
      .optional()
      .nullable(),
    workspace: z
      .union([
        z.lazy(() => WorkspaceScalarRelationFilterObjectSchema),
        z.lazy(() => WorkspaceWhereInputObjectSchema)
      ])
      .optional(),
    patrols: z.lazy(() => PatrolListRelationFilterObjectSchema).optional(),
    incidents: z.lazy(() => IncidentListRelationFilterObjectSchema).optional(),
    members: z
      .lazy(() => ResourceMemberListRelationFilterObjectSchema)
      .optional()
  })
  .strict() as SchemaType;
