/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { UserSettingsSchema } from '../models/UserSettings.schema';

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { ClientCreateWithoutMembersInputObjectSchema } from './ClientCreateWithoutMembersInput.schema';
import { ClientUncheckedCreateWithoutMembersInputObjectSchema } from './ClientUncheckedCreateWithoutMembersInput.schema';
import { ClientCreateOrConnectWithoutMembersInputObjectSchema } from './ClientCreateOrConnectWithoutMembersInput.schema';
import { ClientWhereUniqueInputObjectSchema } from './ClientWhereUniqueInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ClientCreateNestedOneWithoutMembersInput>;
export const ClientCreateNestedOneWithoutMembersInputObjectSchema: SchemaType =
  z
    .object({
      create: z
        .union([
          z.lazy(() => ClientCreateWithoutMembersInputObjectSchema),
          z.lazy(() => ClientUncheckedCreateWithoutMembersInputObjectSchema)
        ])
        .optional(),
      connectOrCreate: z
        .lazy(() => ClientCreateOrConnectWithoutMembersInputObjectSchema)
        .optional(),
      connect: z.lazy(() => ClientWhereUniqueInputObjectSchema).optional()
    })
    .strict() as SchemaType;
