/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { UserSettingsSchema } from '../models/UserSettings.schema';

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { DateTimeFieldUpdateOperationsInputObjectSchema } from './DateTimeFieldUpdateOperationsInput.schema';
import { NullableStringFieldUpdateOperationsInputObjectSchema } from './NullableStringFieldUpdateOperationsInput.schema';
import { StringFieldUpdateOperationsInputObjectSchema } from './StringFieldUpdateOperationsInput.schema';
import { EntityStatusSchema } from '../enums/EntityStatus.schema';
import { EnumEntityStatusFieldUpdateOperationsInputObjectSchema } from './EnumEntityStatusFieldUpdateOperationsInput.schema';
import { NullableIntFieldUpdateOperationsInputObjectSchema } from './NullableIntFieldUpdateOperationsInput.schema';
import { WorkspaceUpdateOneRequiredWithoutClientsNestedInputObjectSchema } from './WorkspaceUpdateOneRequiredWithoutClientsNestedInput.schema';
import { PatrolUpdateManyWithoutClientNestedInputObjectSchema } from './PatrolUpdateManyWithoutClientNestedInput.schema';
import { IncidentUpdateManyWithoutClientNestedInputObjectSchema } from './IncidentUpdateManyWithoutClientNestedInput.schema';
import { ResourceMemberUpdateManyWithoutClientNestedInputObjectSchema } from './ResourceMemberUpdateManyWithoutClientNestedInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ClientUpdateInput>;
export const ClientUpdateInputObjectSchema: SchemaType = z
  .object({
    createdAt: z
      .union([
        z.union([z.date(), z.string().datetime().optional()]),
        z.lazy(() => DateTimeFieldUpdateOperationsInputObjectSchema)
      ])
      .optional(),
    updatedAt: z
      .union([
        z.union([z.date(), z.string().datetime().optional()]),
        z.lazy(() => DateTimeFieldUpdateOperationsInputObjectSchema)
      ])
      .optional(),
    createdBy: z
      .union([
        z.string(),
        z.lazy(() => NullableStringFieldUpdateOperationsInputObjectSchema),
        z.null()
      ])
      .optional()
      .nullable(),
    updatedBy: z
      .union([
        z.string(),
        z.lazy(() => NullableStringFieldUpdateOperationsInputObjectSchema),
        z.null()
      ])
      .optional()
      .nullable(),
    id: z
      .union([
        z.string(),
        z.lazy(() => StringFieldUpdateOperationsInputObjectSchema)
      ])
      .optional(),
    name: z
      .union([
        z.string(),
        z.lazy(() => StringFieldUpdateOperationsInputObjectSchema)
      ])
      .optional(),
    description: z
      .union([
        z.string(),
        z.lazy(() => NullableStringFieldUpdateOperationsInputObjectSchema),
        z.null()
      ])
      .optional()
      .nullable(),
    logoUrl: z
      .union([
        z.string(),
        z.lazy(() => NullableStringFieldUpdateOperationsInputObjectSchema),
        z.null()
      ])
      .optional()
      .nullable(),
    status: z
      .union([
        z.lazy(() => EntityStatusSchema),
        z.lazy(() => EnumEntityStatusFieldUpdateOperationsInputObjectSchema)
      ])
      .optional(),
    settings: z.lazy(() => UserSettingsSchema),
    address: z.lazy(() => GooglePlacesAutocompleteSchema),
    maxPatrols: z
      .union([
        z.number(),
        z.lazy(() => NullableIntFieldUpdateOperationsInputObjectSchema),
        z.null()
      ])
      .optional()
      .nullable(),
    workspace: z
      .lazy(
        () => WorkspaceUpdateOneRequiredWithoutClientsNestedInputObjectSchema
      )
      .optional(),
    patrols: z
      .lazy(() => PatrolUpdateManyWithoutClientNestedInputObjectSchema)
      .optional(),
    incidents: z
      .lazy(() => IncidentUpdateManyWithoutClientNestedInputObjectSchema)
      .optional(),
    members: z
      .lazy(() => ResourceMemberUpdateManyWithoutClientNestedInputObjectSchema)
      .optional()
  })
  .strict() as SchemaType;
