/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { SortOrderSchema } from '../enums/SortOrder.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ClientSumOrderByAggregateInput>;
export const ClientSumOrderByAggregateInputObjectSchema: SchemaType = z
  .object({
    maxPatrols: z.lazy(() => SortOrderSchema).optional()
  })
  .strict() as SchemaType;
