/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { UserSettingsSchema } from '../models/UserSettings.schema';

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { ClientCreateWithoutWorkspaceInputObjectSchema } from './ClientCreateWithoutWorkspaceInput.schema';
import { ClientUncheckedCreateWithoutWorkspaceInputObjectSchema } from './ClientUncheckedCreateWithoutWorkspaceInput.schema';
import { ClientCreateOrConnectWithoutWorkspaceInputObjectSchema } from './ClientCreateOrConnectWithoutWorkspaceInput.schema';
import { ClientCreateManyWorkspaceInputEnvelopeObjectSchema } from './ClientCreateManyWorkspaceInputEnvelope.schema';
import { ClientWhereUniqueInputObjectSchema } from './ClientWhereUniqueInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ClientCreateNestedManyWithoutWorkspaceInput>;
export const ClientCreateNestedManyWithoutWorkspaceInputObjectSchema: SchemaType =
  z
    .object({
      create: z
        .union([
          z.lazy(() => ClientCreateWithoutWorkspaceInputObjectSchema),
          z.lazy(() => ClientCreateWithoutWorkspaceInputObjectSchema).array(),
          z.lazy(() => ClientUncheckedCreateWithoutWorkspaceInputObjectSchema),
          z
            .lazy(() => ClientUncheckedCreateWithoutWorkspaceInputObjectSchema)
            .array()
        ])
        .optional(),
      connectOrCreate: z
        .union([
          z.lazy(() => ClientCreateOrConnectWithoutWorkspaceInputObjectSchema),
          z
            .lazy(() => ClientCreateOrConnectWithoutWorkspaceInputObjectSchema)
            .array()
        ])
        .optional(),
      createMany: z
        .lazy(() => ClientCreateManyWorkspaceInputEnvelopeObjectSchema)
        .optional(),
      connect: z
        .union([
          z.lazy(() => ClientWhereUniqueInputObjectSchema),
          z.lazy(() => ClientWhereUniqueInputObjectSchema).array()
        ])
        .optional()
    })
    .strict() as SchemaType;
