/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { IncidentSeveritySchema } from '../enums/IncidentSeverity.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.EnumIncidentSeverityFieldUpdateOperationsInput>;
export const EnumIncidentSeverityFieldUpdateOperationsInputObjectSchema: SchemaType =
  z
    .object({
      set: z.lazy(() => IncidentSeveritySchema).optional()
    })
    .strict() as SchemaType;
