/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { AuditLogEventTypeSchema } from '../enums/AuditLogEventType.schema';
import { NestedEnumAuditLogEventTypeFilterObjectSchema } from './NestedEnumAuditLogEventTypeFilter.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.EnumAuditLogEventTypeFilter>;
export const EnumAuditLogEventTypeFilterObjectSchema: SchemaType = z
  .object({
    equals: z.lazy(() => AuditLogEventTypeSchema).optional(),
    in: z
      .lazy(() => AuditLogEventTypeSchema)
      .array()
      .optional(),
    notIn: z
      .lazy(() => AuditLogEventTypeSchema)
      .array()
      .optional(),
    not: z
      .union([
        z.lazy(() => AuditLogEventTypeSchema),
        z.lazy(() => NestedEnumAuditLogEventTypeFilterObjectSchema)
      ])
      .optional()
  })
  .strict() as SchemaType;
