/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { PermissionSchema } from '../enums/Permission.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.EnumPermissionNullableListFilter>;
export const EnumPermissionNullableListFilterObjectSchema: SchemaType = z
  .object({
    equals: z
      .union([z.lazy(() => PermissionSchema).array(), z.null()])
      .optional()
      .nullable(),
    has: z
      .union([z.lazy(() => PermissionSchema), z.null()])
      .optional()
      .nullable(),
    hasEvery: z
      .lazy(() => PermissionSchema)
      .array()
      .optional(),
    hasSome: z
      .lazy(() => PermissionSchema)
      .array()
      .optional(),
    isEmpty: z.boolean().optional()
  })
  .strict() as SchemaType;
