/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { VerificationTokenTypeSchema } from '../enums/VerificationTokenType.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.EnumVerificationTokenTypeFieldUpdateOperationsInput>;
export const EnumVerificationTokenTypeFieldUpdateOperationsInputObjectSchema: SchemaType =
  z
    .object({
      set: z.lazy(() => VerificationTokenTypeSchema).optional()
    })
    .strict() as SchemaType;
