/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { IncidentCategorySchema } from '../enums/IncidentCategory.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.EnumIncidentCategoryFieldUpdateOperationsInput>;
export const EnumIncidentCategoryFieldUpdateOperationsInputObjectSchema: SchemaType =
  z
    .object({
      set: z.lazy(() => IncidentCategorySchema).optional()
    })
    .strict() as SchemaType;
