/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { SeedExecutionStatusSchema } from '../enums/SeedExecutionStatus.schema';
import { NestedEnumSeedExecutionStatusFilterObjectSchema } from './NestedEnumSeedExecutionStatusFilter.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.EnumSeedExecutionStatusFilter>;
export const EnumSeedExecutionStatusFilterObjectSchema: SchemaType = z
  .object({
    equals: z.lazy(() => SeedExecutionStatusSchema).optional(),
    in: z
      .lazy(() => SeedExecutionStatusSchema)
      .array()
      .optional(),
    notIn: z
      .lazy(() => SeedExecutionStatusSchema)
      .array()
      .optional(),
    not: z
      .union([
        z.lazy(() => SeedExecutionStatusSchema),
        z.lazy(() => NestedEnumSeedExecutionStatusFilterObjectSchema)
      ])
      .optional()
  })
  .strict() as SchemaType;
