/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { EntityStatusSchema } from '../enums/EntityStatus.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.EnumEntityStatusFieldUpdateOperationsInput>;
export const EnumEntityStatusFieldUpdateOperationsInputObjectSchema: SchemaType =
  z
    .object({
      set: z.lazy(() => EntityStatusSchema).optional()
    })
    .strict() as SchemaType;
