/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { SeedExecutionStatusSchema } from '../enums/SeedExecutionStatus.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.EnumSeedExecutionStatusFieldUpdateOperationsInput>;
export const EnumSeedExecutionStatusFieldUpdateOperationsInputObjectSchema: SchemaType =
  z
    .object({
      set: z.lazy(() => SeedExecutionStatusSchema).optional()
    })
    .strict() as SchemaType;
