/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { IncidentCountOutputTypeSelectObjectSchema } from './IncidentCountOutputTypeSelect.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.IncidentCountOutputTypeDefaultArgs>;
export const IncidentCountOutputTypeDefaultArgsObjectSchema: SchemaType = z
  .object({
    select: z.lazy(() => IncidentCountOutputTypeSelectObjectSchema).optional()
  })
  .strict() as SchemaType;
