/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { IncidentWhereUniqueInputObjectSchema } from './IncidentWhereUniqueInput.schema';
import { IncidentUpdateWithoutRelatedToIncidentsInputObjectSchema } from './IncidentUpdateWithoutRelatedToIncidentsInput.schema';
import { IncidentUncheckedUpdateWithoutRelatedToIncidentsInputObjectSchema } from './IncidentUncheckedUpdateWithoutRelatedToIncidentsInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.IncidentUpdateWithWhereUniqueWithoutRelatedToIncidentsInput>;
export const IncidentUpdateWithWhereUniqueWithoutRelatedToIncidentsInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => IncidentWhereUniqueInputObjectSchema),
      data: z.union([
        z.lazy(() => IncidentUpdateWithoutRelatedToIncidentsInputObjectSchema),
        z.lazy(
          () =>
            IncidentUncheckedUpdateWithoutRelatedToIncidentsInputObjectSchema
        )
      ])
    })
    .strict() as SchemaType;
