/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { DateTimeFieldUpdateOperationsInputObjectSchema } from './DateTimeFieldUpdateOperationsInput.schema';
import { NullableStringFieldUpdateOperationsInputObjectSchema } from './NullableStringFieldUpdateOperationsInput.schema';
import { StringFieldUpdateOperationsInputObjectSchema } from './StringFieldUpdateOperationsInput.schema';
import { IncidentStatusSchema } from '../enums/IncidentStatus.schema';
import { EnumIncidentStatusFieldUpdateOperationsInputObjectSchema } from './EnumIncidentStatusFieldUpdateOperationsInput.schema';
import { IncidentSeveritySchema } from '../enums/IncidentSeverity.schema';
import { EnumIncidentSeverityFieldUpdateOperationsInputObjectSchema } from './EnumIncidentSeverityFieldUpdateOperationsInput.schema';
import { IncidentCategorySchema } from '../enums/IncidentCategory.schema';
import { EnumIncidentCategoryFieldUpdateOperationsInputObjectSchema } from './EnumIncidentCategoryFieldUpdateOperationsInput.schema';
import { NullableIntFieldUpdateOperationsInputObjectSchema } from './NullableIntFieldUpdateOperationsInput.schema';
import { NullableDateTimeFieldUpdateOperationsInputObjectSchema } from './NullableDateTimeFieldUpdateOperationsInput.schema';
import { IncidentUpdatetagsInputObjectSchema } from './IncidentUpdatetagsInput.schema';
import { ObjectStorageFileUncheckedUpdateManyWithoutIncidentsNestedInputObjectSchema } from './ObjectStorageFileUncheckedUpdateManyWithoutIncidentsNestedInput.schema';
import { IncidentUncheckedUpdateManyWithoutRelatedIncidentsNestedInputObjectSchema } from './IncidentUncheckedUpdateManyWithoutRelatedIncidentsNestedInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.IncidentUncheckedUpdateWithoutRelatedIncidentsInput>;
export const IncidentUncheckedUpdateWithoutRelatedIncidentsInputObjectSchema: SchemaType =
  z
    .object({
      createdAt: z
        .union([
          z.union([z.date(), z.string().datetime().optional()]),
          z.lazy(() => DateTimeFieldUpdateOperationsInputObjectSchema)
        ])
        .optional(),
      updatedAt: z
        .union([
          z.union([z.date(), z.string().datetime().optional()]),
          z.lazy(() => DateTimeFieldUpdateOperationsInputObjectSchema)
        ])
        .optional(),
      createdBy: z
        .union([
          z.string(),
          z.lazy(() => NullableStringFieldUpdateOperationsInputObjectSchema),
          z.null()
        ])
        .optional()
        .nullable(),
      updatedBy: z
        .union([
          z.string(),
          z.lazy(() => NullableStringFieldUpdateOperationsInputObjectSchema),
          z.null()
        ])
        .optional()
        .nullable(),
      id: z
        .union([
          z.string(),
          z.lazy(() => StringFieldUpdateOperationsInputObjectSchema)
        ])
        .optional(),
      title: z
        .union([
          z.string(),
          z.lazy(() => StringFieldUpdateOperationsInputObjectSchema)
        ])
        .optional(),
      description: z
        .union([
          z.string(),
          z.lazy(() => NullableStringFieldUpdateOperationsInputObjectSchema),
          z.null()
        ])
        .optional()
        .nullable(),
      status: z
        .union([
          z.lazy(() => IncidentStatusSchema),
          z.lazy(() => EnumIncidentStatusFieldUpdateOperationsInputObjectSchema)
        ])
        .optional(),
      occurredAt: z
        .union([
          z.union([z.date(), z.string().datetime().optional()]),
          z.lazy(() => DateTimeFieldUpdateOperationsInputObjectSchema)
        ])
        .optional(),
      address: z.lazy(() => GooglePlacesAutocompleteSchema),
      severity: z
        .union([
          z.lazy(() => IncidentSeveritySchema),
          z.lazy(
            () => EnumIncidentSeverityFieldUpdateOperationsInputObjectSchema
          )
        ])
        .optional(),
      category: z
        .union([
          z.lazy(() => IncidentCategorySchema),
          z.lazy(
            () => EnumIncidentCategoryFieldUpdateOperationsInputObjectSchema
          )
        ])
        .optional(),
      responseTime: z
        .union([
          z.number(),
          z.lazy(() => NullableIntFieldUpdateOperationsInputObjectSchema),
          z.null()
        ])
        .optional()
        .nullable(),
      resolutionTime: z
        .union([
          z.number(),
          z.lazy(() => NullableIntFieldUpdateOperationsInputObjectSchema),
          z.null()
        ])
        .optional()
        .nullable(),
      assignedAt: z
        .union([
          z.union([z.date(), z.string().datetime().optional()]),
          z.lazy(() => NullableDateTimeFieldUpdateOperationsInputObjectSchema),
          z.null()
        ])
        .optional()
        .nullable(),
      priority: z
        .union([
          z.number(),
          z.lazy(() => NullableIntFieldUpdateOperationsInputObjectSchema),
          z.null()
        ])
        .optional()
        .nullable(),
      dueDate: z
        .union([
          z.union([z.date(), z.string().datetime().optional()]),
          z.lazy(() => NullableDateTimeFieldUpdateOperationsInputObjectSchema),
          z.null()
        ])
        .optional()
        .nullable(),
      tags: z
        .union([
          z.lazy(() => IncidentUpdatetagsInputObjectSchema),
          z.string().array()
        ])
        .optional(),
      clientId: z
        .union([
          z.string(),
          z.lazy(() => StringFieldUpdateOperationsInputObjectSchema)
        ])
        .optional(),
      patrolId: z
        .union([
          z.string(),
          z.lazy(() => StringFieldUpdateOperationsInputObjectSchema)
        ])
        .optional(),
      attachments: z
        .lazy(
          () =>
            ObjectStorageFileUncheckedUpdateManyWithoutIncidentsNestedInputObjectSchema
        )
        .optional(),
      relatedToIncidents: z
        .lazy(
          () =>
            IncidentUncheckedUpdateManyWithoutRelatedIncidentsNestedInputObjectSchema
        )
        .optional()
    })
    .strict() as SchemaType;
