/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { IncidentWhereUniqueInputObjectSchema } from './IncidentWhereUniqueInput.schema';
import { IncidentUpdateWithoutClientInputObjectSchema } from './IncidentUpdateWithoutClientInput.schema';
import { IncidentUncheckedUpdateWithoutClientInputObjectSchema } from './IncidentUncheckedUpdateWithoutClientInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.IncidentUpdateWithWhereUniqueWithoutClientInput>;
export const IncidentUpdateWithWhereUniqueWithoutClientInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => IncidentWhereUniqueInputObjectSchema),
      data: z.union([
        z.lazy(() => IncidentUpdateWithoutClientInputObjectSchema),
        z.lazy(() => IncidentUncheckedUpdateWithoutClientInputObjectSchema)
      ])
    })
    .strict() as SchemaType;
