/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { IncidentWhereUniqueInputObjectSchema } from './IncidentWhereUniqueInput.schema';
import { IncidentUpdateWithoutAttachmentsInputObjectSchema } from './IncidentUpdateWithoutAttachmentsInput.schema';
import { IncidentUncheckedUpdateWithoutAttachmentsInputObjectSchema } from './IncidentUncheckedUpdateWithoutAttachmentsInput.schema';
import { IncidentCreateWithoutAttachmentsInputObjectSchema } from './IncidentCreateWithoutAttachmentsInput.schema';
import { IncidentUncheckedCreateWithoutAttachmentsInputObjectSchema } from './IncidentUncheckedCreateWithoutAttachmentsInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.IncidentUpsertWithWhereUniqueWithoutAttachmentsInput>;
export const IncidentUpsertWithWhereUniqueWithoutAttachmentsInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => IncidentWhereUniqueInputObjectSchema),
      update: z.union([
        z.lazy(() => IncidentUpdateWithoutAttachmentsInputObjectSchema),
        z.lazy(() => IncidentUncheckedUpdateWithoutAttachmentsInputObjectSchema)
      ]),
      create: z.union([
        z.lazy(() => IncidentCreateWithoutAttachmentsInputObjectSchema),
        z.lazy(() => IncidentUncheckedCreateWithoutAttachmentsInputObjectSchema)
      ])
    })
    .strict() as SchemaType;
