/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.IncidentCreatetagsInput>;
export const IncidentCreatetagsInputObjectSchema: SchemaType = z
  .object({
    set: z.string().array()
  })
  .strict() as SchemaType;
