/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.IncidentCountOutputTypeSelect>;
export const IncidentCountOutputTypeSelectObjectSchema: SchemaType = z
  .object({
    attachments: z.boolean().optional(),
    relatedIncidents: z.boolean().optional(),
    relatedToIncidents: z.boolean().optional()
  })
  .strict() as SchemaType;
