/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { IncidentCreateWithoutRelatedToIncidentsInputObjectSchema } from './IncidentCreateWithoutRelatedToIncidentsInput.schema';
import { IncidentUncheckedCreateWithoutRelatedToIncidentsInputObjectSchema } from './IncidentUncheckedCreateWithoutRelatedToIncidentsInput.schema';
import { IncidentCreateOrConnectWithoutRelatedToIncidentsInputObjectSchema } from './IncidentCreateOrConnectWithoutRelatedToIncidentsInput.schema';
import { IncidentUpsertWithWhereUniqueWithoutRelatedToIncidentsInputObjectSchema } from './IncidentUpsertWithWhereUniqueWithoutRelatedToIncidentsInput.schema';
import { IncidentWhereUniqueInputObjectSchema } from './IncidentWhereUniqueInput.schema';
import { IncidentUpdateWithWhereUniqueWithoutRelatedToIncidentsInputObjectSchema } from './IncidentUpdateWithWhereUniqueWithoutRelatedToIncidentsInput.schema';
import { IncidentUpdateManyWithWhereWithoutRelatedToIncidentsInputObjectSchema } from './IncidentUpdateManyWithWhereWithoutRelatedToIncidentsInput.schema';
import { IncidentScalarWhereInputObjectSchema } from './IncidentScalarWhereInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.IncidentUncheckedUpdateManyWithoutRelatedToIncidentsNestedInput>;
export const IncidentUncheckedUpdateManyWithoutRelatedToIncidentsNestedInputObjectSchema: SchemaType =
  z
    .object({
      create: z
        .union([
          z.lazy(
            () => IncidentCreateWithoutRelatedToIncidentsInputObjectSchema
          ),
          z
            .lazy(
              () => IncidentCreateWithoutRelatedToIncidentsInputObjectSchema
            )
            .array(),
          z.lazy(
            () =>
              IncidentUncheckedCreateWithoutRelatedToIncidentsInputObjectSchema
          ),
          z
            .lazy(
              () =>
                IncidentUncheckedCreateWithoutRelatedToIncidentsInputObjectSchema
            )
            .array()
        ])
        .optional(),
      connectOrCreate: z
        .union([
          z.lazy(
            () =>
              IncidentCreateOrConnectWithoutRelatedToIncidentsInputObjectSchema
          ),
          z
            .lazy(
              () =>
                IncidentCreateOrConnectWithoutRelatedToIncidentsInputObjectSchema
            )
            .array()
        ])
        .optional(),
      upsert: z
        .union([
          z.lazy(
            () =>
              IncidentUpsertWithWhereUniqueWithoutRelatedToIncidentsInputObjectSchema
          ),
          z
            .lazy(
              () =>
                IncidentUpsertWithWhereUniqueWithoutRelatedToIncidentsInputObjectSchema
            )
            .array()
        ])
        .optional(),
      set: z
        .union([
          z.lazy(() => IncidentWhereUniqueInputObjectSchema),
          z.lazy(() => IncidentWhereUniqueInputObjectSchema).array()
        ])
        .optional(),
      disconnect: z
        .union([
          z.lazy(() => IncidentWhereUniqueInputObjectSchema),
          z.lazy(() => IncidentWhereUniqueInputObjectSchema).array()
        ])
        .optional(),
      delete: z
        .union([
          z.lazy(() => IncidentWhereUniqueInputObjectSchema),
          z.lazy(() => IncidentWhereUniqueInputObjectSchema).array()
        ])
        .optional(),
      connect: z
        .union([
          z.lazy(() => IncidentWhereUniqueInputObjectSchema),
          z.lazy(() => IncidentWhereUniqueInputObjectSchema).array()
        ])
        .optional(),
      update: z
        .union([
          z.lazy(
            () =>
              IncidentUpdateWithWhereUniqueWithoutRelatedToIncidentsInputObjectSchema
          ),
          z
            .lazy(
              () =>
                IncidentUpdateWithWhereUniqueWithoutRelatedToIncidentsInputObjectSchema
            )
            .array()
        ])
        .optional(),
      updateMany: z
        .union([
          z.lazy(
            () =>
              IncidentUpdateManyWithWhereWithoutRelatedToIncidentsInputObjectSchema
          ),
          z
            .lazy(
              () =>
                IncidentUpdateManyWithWhereWithoutRelatedToIncidentsInputObjectSchema
            )
            .array()
        ])
        .optional(),
      deleteMany: z
        .union([
          z.lazy(() => IncidentScalarWhereInputObjectSchema),
          z.lazy(() => IncidentScalarWhereInputObjectSchema).array()
        ])
        .optional()
    })
    .strict() as SchemaType;
