/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { IncidentStatusSchema } from '../enums/IncidentStatus.schema';
import { IncidentSeveritySchema } from '../enums/IncidentSeverity.schema';
import { IncidentCategorySchema } from '../enums/IncidentCategory.schema';
import { IncidentCreatetagsInputObjectSchema } from './IncidentCreatetagsInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.IncidentCreateManyInput>;
export const IncidentCreateManyInputObjectSchema: SchemaType = z
  .object({
    createdAt: z.union([z.date().optional(), z.string().datetime().optional()]),
    updatedAt: z.union([z.date().optional(), z.string().datetime().optional()]),
    createdBy: z.union([z.string(), z.null()]).optional().nullable(),
    updatedBy: z.union([z.string(), z.null()]).optional().nullable(),
    id: z.string().optional(),
    title: z.string(),
    description: z.union([z.string(), z.null()]).optional().nullable(),
    status: z.lazy(() => IncidentStatusSchema).optional(),
    occurredAt: z.union([z.date(), z.string().datetime()]),
    address: z.lazy(() => GooglePlacesAutocompleteSchema),
    severity: z.lazy(() => IncidentSeveritySchema).optional(),
    category: z.lazy(() => IncidentCategorySchema).optional(),
    responseTime: z.union([z.number(), z.null()]).optional().nullable(),
    resolutionTime: z.union([z.number(), z.null()]).optional().nullable(),
    assignedAt: z
      .union([z.union([z.date(), z.string().datetime().optional()]), z.null()])
      .optional()
      .nullable(),
    priority: z.union([z.number(), z.null()]).optional().nullable(),
    dueDate: z
      .union([z.union([z.date(), z.string().datetime().optional()]), z.null()])
      .optional()
      .nullable(),
    tags: z
      .union([
        z.lazy(() => IncidentCreatetagsInputObjectSchema),
        z.string().array()
      ])
      .optional(),
    clientId: z.string(),
    patrolId: z.string()
  })
  .strict() as SchemaType;
