/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { IncidentCreateWithoutAttachmentsInputObjectSchema } from './IncidentCreateWithoutAttachmentsInput.schema';
import { IncidentUncheckedCreateWithoutAttachmentsInputObjectSchema } from './IncidentUncheckedCreateWithoutAttachmentsInput.schema';
import { IncidentCreateOrConnectWithoutAttachmentsInputObjectSchema } from './IncidentCreateOrConnectWithoutAttachmentsInput.schema';
import { IncidentUpsertWithWhereUniqueWithoutAttachmentsInputObjectSchema } from './IncidentUpsertWithWhereUniqueWithoutAttachmentsInput.schema';
import { IncidentWhereUniqueInputObjectSchema } from './IncidentWhereUniqueInput.schema';
import { IncidentUpdateWithWhereUniqueWithoutAttachmentsInputObjectSchema } from './IncidentUpdateWithWhereUniqueWithoutAttachmentsInput.schema';
import { IncidentUpdateManyWithWhereWithoutAttachmentsInputObjectSchema } from './IncidentUpdateManyWithWhereWithoutAttachmentsInput.schema';
import { IncidentScalarWhereInputObjectSchema } from './IncidentScalarWhereInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.IncidentUpdateManyWithoutAttachmentsNestedInput>;
export const IncidentUpdateManyWithoutAttachmentsNestedInputObjectSchema: SchemaType =
  z
    .object({
      create: z
        .union([
          z.lazy(() => IncidentCreateWithoutAttachmentsInputObjectSchema),
          z
            .lazy(() => IncidentCreateWithoutAttachmentsInputObjectSchema)
            .array(),
          z.lazy(
            () => IncidentUncheckedCreateWithoutAttachmentsInputObjectSchema
          ),
          z
            .lazy(
              () => IncidentUncheckedCreateWithoutAttachmentsInputObjectSchema
            )
            .array()
        ])
        .optional(),
      connectOrCreate: z
        .union([
          z.lazy(
            () => IncidentCreateOrConnectWithoutAttachmentsInputObjectSchema
          ),
          z
            .lazy(
              () => IncidentCreateOrConnectWithoutAttachmentsInputObjectSchema
            )
            .array()
        ])
        .optional(),
      upsert: z
        .union([
          z.lazy(
            () =>
              IncidentUpsertWithWhereUniqueWithoutAttachmentsInputObjectSchema
          ),
          z
            .lazy(
              () =>
                IncidentUpsertWithWhereUniqueWithoutAttachmentsInputObjectSchema
            )
            .array()
        ])
        .optional(),
      set: z
        .union([
          z.lazy(() => IncidentWhereUniqueInputObjectSchema),
          z.lazy(() => IncidentWhereUniqueInputObjectSchema).array()
        ])
        .optional(),
      disconnect: z
        .union([
          z.lazy(() => IncidentWhereUniqueInputObjectSchema),
          z.lazy(() => IncidentWhereUniqueInputObjectSchema).array()
        ])
        .optional(),
      delete: z
        .union([
          z.lazy(() => IncidentWhereUniqueInputObjectSchema),
          z.lazy(() => IncidentWhereUniqueInputObjectSchema).array()
        ])
        .optional(),
      connect: z
        .union([
          z.lazy(() => IncidentWhereUniqueInputObjectSchema),
          z.lazy(() => IncidentWhereUniqueInputObjectSchema).array()
        ])
        .optional(),
      update: z
        .union([
          z.lazy(
            () =>
              IncidentUpdateWithWhereUniqueWithoutAttachmentsInputObjectSchema
          ),
          z
            .lazy(
              () =>
                IncidentUpdateWithWhereUniqueWithoutAttachmentsInputObjectSchema
            )
            .array()
        ])
        .optional(),
      updateMany: z
        .union([
          z.lazy(
            () => IncidentUpdateManyWithWhereWithoutAttachmentsInputObjectSchema
          ),
          z
            .lazy(
              () =>
                IncidentUpdateManyWithWhereWithoutAttachmentsInputObjectSchema
            )
            .array()
        ])
        .optional(),
      deleteMany: z
        .union([
          z.lazy(() => IncidentScalarWhereInputObjectSchema),
          z.lazy(() => IncidentScalarWhereInputObjectSchema).array()
        ])
        .optional()
    })
    .strict() as SchemaType;
