/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { ObjectStorageFileInputSchema } from '../input/ObjectStorageFileInput.schema';
import { IncidentInputSchema } from '../input/IncidentInput.schema';
import { ClientDefaultArgsObjectSchema } from './ClientDefaultArgs.schema';
import { PatrolDefaultArgsObjectSchema } from './PatrolDefaultArgs.schema';
import { IncidentCountOutputTypeDefaultArgsObjectSchema } from './IncidentCountOutputTypeDefaultArgs.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.IncidentSelect>;
export const IncidentSelectObjectSchema: SchemaType = z
  .object({
    createdAt: z.boolean().optional(),
    updatedAt: z.boolean().optional(),
    createdBy: z.boolean().optional(),
    updatedBy: z.boolean().optional(),
    id: z.boolean().optional(),
    title: z.boolean().optional(),
    description: z.boolean().optional(),
    status: z.boolean().optional(),
    occurredAt: z.boolean().optional(),
    address: z.boolean().optional(),
    attachments: z
      .union([z.boolean(), z.lazy(() => ObjectStorageFileInputSchema.findMany)])
      .optional(),
    severity: z.boolean().optional(),
    category: z.boolean().optional(),
    responseTime: z.boolean().optional(),
    resolutionTime: z.boolean().optional(),
    assignedAt: z.boolean().optional(),
    priority: z.boolean().optional(),
    dueDate: z.boolean().optional(),
    tags: z.boolean().optional(),
    relatedIncidents: z
      .union([z.boolean(), z.lazy(() => IncidentInputSchema.findMany)])
      .optional(),
    relatedToIncidents: z
      .union([z.boolean(), z.lazy(() => IncidentInputSchema.findMany)])
      .optional(),
    client: z
      .union([z.boolean(), z.lazy(() => ClientDefaultArgsObjectSchema)])
      .optional(),
    clientId: z.boolean().optional(),
    patrol: z
      .union([z.boolean(), z.lazy(() => PatrolDefaultArgsObjectSchema)])
      .optional(),
    patrolId: z.boolean().optional(),
    _count: z
      .union([
        z.boolean(),
        z.lazy(() => IncidentCountOutputTypeDefaultArgsObjectSchema)
      ])
      .optional()
  })
  .strict() as SchemaType;
