/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { IncidentWhereUniqueInputObjectSchema } from './IncidentWhereUniqueInput.schema';
import { IncidentUpdateWithoutPatrolInputObjectSchema } from './IncidentUpdateWithoutPatrolInput.schema';
import { IncidentUncheckedUpdateWithoutPatrolInputObjectSchema } from './IncidentUncheckedUpdateWithoutPatrolInput.schema';
import { IncidentCreateWithoutPatrolInputObjectSchema } from './IncidentCreateWithoutPatrolInput.schema';
import { IncidentUncheckedCreateWithoutPatrolInputObjectSchema } from './IncidentUncheckedCreateWithoutPatrolInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.IncidentUpsertWithWhereUniqueWithoutPatrolInput>;
export const IncidentUpsertWithWhereUniqueWithoutPatrolInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => IncidentWhereUniqueInputObjectSchema),
      update: z.union([
        z.lazy(() => IncidentUpdateWithoutPatrolInputObjectSchema),
        z.lazy(() => IncidentUncheckedUpdateWithoutPatrolInputObjectSchema)
      ]),
      create: z.union([
        z.lazy(() => IncidentCreateWithoutPatrolInputObjectSchema),
        z.lazy(() => IncidentUncheckedCreateWithoutPatrolInputObjectSchema)
      ])
    })
    .strict() as SchemaType;
