/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { IncidentWhereUniqueInputObjectSchema } from './IncidentWhereUniqueInput.schema';
import { IncidentUpdateWithoutRelatedToIncidentsInputObjectSchema } from './IncidentUpdateWithoutRelatedToIncidentsInput.schema';
import { IncidentUncheckedUpdateWithoutRelatedToIncidentsInputObjectSchema } from './IncidentUncheckedUpdateWithoutRelatedToIncidentsInput.schema';
import { IncidentCreateWithoutRelatedToIncidentsInputObjectSchema } from './IncidentCreateWithoutRelatedToIncidentsInput.schema';
import { IncidentUncheckedCreateWithoutRelatedToIncidentsInputObjectSchema } from './IncidentUncheckedCreateWithoutRelatedToIncidentsInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.IncidentUpsertWithWhereUniqueWithoutRelatedToIncidentsInput>;
export const IncidentUpsertWithWhereUniqueWithoutRelatedToIncidentsInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => IncidentWhereUniqueInputObjectSchema),
      update: z.union([
        z.lazy(() => IncidentUpdateWithoutRelatedToIncidentsInputObjectSchema),
        z.lazy(
          () =>
            IncidentUncheckedUpdateWithoutRelatedToIncidentsInputObjectSchema
        )
      ]),
      create: z.union([
        z.lazy(() => IncidentCreateWithoutRelatedToIncidentsInputObjectSchema),
        z.lazy(
          () =>
            IncidentUncheckedCreateWithoutRelatedToIncidentsInputObjectSchema
        )
      ])
    })
    .strict() as SchemaType;
