/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { IncidentWhereUniqueInputObjectSchema } from './IncidentWhereUniqueInput.schema';
import { IncidentUpdateWithoutClientInputObjectSchema } from './IncidentUpdateWithoutClientInput.schema';
import { IncidentUncheckedUpdateWithoutClientInputObjectSchema } from './IncidentUncheckedUpdateWithoutClientInput.schema';
import { IncidentCreateWithoutClientInputObjectSchema } from './IncidentCreateWithoutClientInput.schema';
import { IncidentUncheckedCreateWithoutClientInputObjectSchema } from './IncidentUncheckedCreateWithoutClientInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.IncidentUpsertWithWhereUniqueWithoutClientInput>;
export const IncidentUpsertWithWhereUniqueWithoutClientInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => IncidentWhereUniqueInputObjectSchema),
      update: z.union([
        z.lazy(() => IncidentUpdateWithoutClientInputObjectSchema),
        z.lazy(() => IncidentUncheckedUpdateWithoutClientInputObjectSchema)
      ]),
      create: z.union([
        z.lazy(() => IncidentCreateWithoutClientInputObjectSchema),
        z.lazy(() => IncidentUncheckedCreateWithoutClientInputObjectSchema)
      ])
    })
    .strict() as SchemaType;
