/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { IncidentWhereUniqueInputObjectSchema } from './IncidentWhereUniqueInput.schema';
import { IncidentCreateWithoutRelatedToIncidentsInputObjectSchema } from './IncidentCreateWithoutRelatedToIncidentsInput.schema';
import { IncidentUncheckedCreateWithoutRelatedToIncidentsInputObjectSchema } from './IncidentUncheckedCreateWithoutRelatedToIncidentsInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.IncidentCreateOrConnectWithoutRelatedToIncidentsInput>;
export const IncidentCreateOrConnectWithoutRelatedToIncidentsInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => IncidentWhereUniqueInputObjectSchema),
      create: z.union([
        z.lazy(() => IncidentCreateWithoutRelatedToIncidentsInputObjectSchema),
        z.lazy(
          () =>
            IncidentUncheckedCreateWithoutRelatedToIncidentsInputObjectSchema
        )
      ])
    })
    .strict() as SchemaType;
