/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { IncidentWhereInputObjectSchema } from './IncidentWhereInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.IncidentListRelationFilter>;
export const IncidentListRelationFilterObjectSchema: SchemaType = z
  .object({
    every: z.lazy(() => IncidentWhereInputObjectSchema).optional(),
    some: z.lazy(() => IncidentWhereInputObjectSchema).optional(),
    none: z.lazy(() => IncidentWhereInputObjectSchema).optional()
  })
  .strict() as SchemaType;
