/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { IncidentWhereUniqueInputObjectSchema } from './IncidentWhereUniqueInput.schema';
import { IncidentCreateWithoutPatrolInputObjectSchema } from './IncidentCreateWithoutPatrolInput.schema';
import { IncidentUncheckedCreateWithoutPatrolInputObjectSchema } from './IncidentUncheckedCreateWithoutPatrolInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.IncidentCreateOrConnectWithoutPatrolInput>;
export const IncidentCreateOrConnectWithoutPatrolInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => IncidentWhereUniqueInputObjectSchema),
      create: z.union([
        z.lazy(() => IncidentCreateWithoutPatrolInputObjectSchema),
        z.lazy(() => IncidentUncheckedCreateWithoutPatrolInputObjectSchema)
      ])
    })
    .strict() as SchemaType;
