/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { IncidentCreateWithoutRelatedIncidentsInputObjectSchema } from './IncidentCreateWithoutRelatedIncidentsInput.schema';
import { IncidentUncheckedCreateWithoutRelatedIncidentsInputObjectSchema } from './IncidentUncheckedCreateWithoutRelatedIncidentsInput.schema';
import { IncidentCreateOrConnectWithoutRelatedIncidentsInputObjectSchema } from './IncidentCreateOrConnectWithoutRelatedIncidentsInput.schema';
import { IncidentWhereUniqueInputObjectSchema } from './IncidentWhereUniqueInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.IncidentCreateNestedManyWithoutRelatedIncidentsInput>;
export const IncidentCreateNestedManyWithoutRelatedIncidentsInputObjectSchema: SchemaType =
  z
    .object({
      create: z
        .union([
          z.lazy(() => IncidentCreateWithoutRelatedIncidentsInputObjectSchema),
          z
            .lazy(() => IncidentCreateWithoutRelatedIncidentsInputObjectSchema)
            .array(),
          z.lazy(
            () =>
              IncidentUncheckedCreateWithoutRelatedIncidentsInputObjectSchema
          ),
          z
            .lazy(
              () =>
                IncidentUncheckedCreateWithoutRelatedIncidentsInputObjectSchema
            )
            .array()
        ])
        .optional(),
      connectOrCreate: z
        .union([
          z.lazy(
            () =>
              IncidentCreateOrConnectWithoutRelatedIncidentsInputObjectSchema
          ),
          z
            .lazy(
              () =>
                IncidentCreateOrConnectWithoutRelatedIncidentsInputObjectSchema
            )
            .array()
        ])
        .optional(),
      connect: z
        .union([
          z.lazy(() => IncidentWhereUniqueInputObjectSchema),
          z.lazy(() => IncidentWhereUniqueInputObjectSchema).array()
        ])
        .optional()
    })
    .strict() as SchemaType;
