/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.IncidentMaxAggregateInputType>;
export const IncidentMaxAggregateInputObjectSchema: SchemaType = z
  .object({
    createdAt: z.literal(true).optional(),
    updatedAt: z.literal(true).optional(),
    createdBy: z.literal(true).optional(),
    updatedBy: z.literal(true).optional(),
    id: z.literal(true).optional(),
    title: z.literal(true).optional(),
    description: z.literal(true).optional(),
    status: z.literal(true).optional(),
    occurredAt: z.literal(true).optional(),
    severity: z.literal(true).optional(),
    category: z.literal(true).optional(),
    responseTime: z.literal(true).optional(),
    resolutionTime: z.literal(true).optional(),
    assignedAt: z.literal(true).optional(),
    priority: z.literal(true).optional(),
    dueDate: z.literal(true).optional(),
    clientId: z.literal(true).optional(),
    patrolId: z.literal(true).optional()
  })
  .strict() as SchemaType;
