/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { IncidentScalarWhereInputObjectSchema } from './IncidentScalarWhereInput.schema';
import { IncidentUpdateManyMutationInputObjectSchema } from './IncidentUpdateManyMutationInput.schema';
import { IncidentUncheckedUpdateManyWithoutClientInputObjectSchema } from './IncidentUncheckedUpdateManyWithoutClientInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.IncidentUpdateManyWithWhereWithoutClientInput>;
export const IncidentUpdateManyWithWhereWithoutClientInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => IncidentScalarWhereInputObjectSchema),
      data: z.union([
        z.lazy(() => IncidentUpdateManyMutationInputObjectSchema),
        z.lazy(() => IncidentUncheckedUpdateManyWithoutClientInputObjectSchema)
      ])
    })
    .strict() as SchemaType;
