/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { IncidentWhereUniqueInputObjectSchema } from './IncidentWhereUniqueInput.schema';
import { IncidentCreateWithoutRelatedIncidentsInputObjectSchema } from './IncidentCreateWithoutRelatedIncidentsInput.schema';
import { IncidentUncheckedCreateWithoutRelatedIncidentsInputObjectSchema } from './IncidentUncheckedCreateWithoutRelatedIncidentsInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.IncidentCreateOrConnectWithoutRelatedIncidentsInput>;
export const IncidentCreateOrConnectWithoutRelatedIncidentsInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => IncidentWhereUniqueInputObjectSchema),
      create: z.union([
        z.lazy(() => IncidentCreateWithoutRelatedIncidentsInputObjectSchema),
        z.lazy(
          () => IncidentUncheckedCreateWithoutRelatedIncidentsInputObjectSchema
        )
      ])
    })
    .strict() as SchemaType;
