/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { IncidentWhereUniqueInputObjectSchema } from './IncidentWhereUniqueInput.schema';
import { IncidentUpdateWithoutPatrolInputObjectSchema } from './IncidentUpdateWithoutPatrolInput.schema';
import { IncidentUncheckedUpdateWithoutPatrolInputObjectSchema } from './IncidentUncheckedUpdateWithoutPatrolInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.IncidentUpdateWithWhereUniqueWithoutPatrolInput>;
export const IncidentUpdateWithWhereUniqueWithoutPatrolInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => IncidentWhereUniqueInputObjectSchema),
      data: z.union([
        z.lazy(() => IncidentUpdateWithoutPatrolInputObjectSchema),
        z.lazy(() => IncidentUncheckedUpdateWithoutPatrolInputObjectSchema)
      ])
    })
    .strict() as SchemaType;
