/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { IncidentCreateWithoutRelatedToIncidentsInputObjectSchema } from './IncidentCreateWithoutRelatedToIncidentsInput.schema';
import { IncidentUncheckedCreateWithoutRelatedToIncidentsInputObjectSchema } from './IncidentUncheckedCreateWithoutRelatedToIncidentsInput.schema';
import { IncidentCreateOrConnectWithoutRelatedToIncidentsInputObjectSchema } from './IncidentCreateOrConnectWithoutRelatedToIncidentsInput.schema';
import { IncidentWhereUniqueInputObjectSchema } from './IncidentWhereUniqueInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.IncidentUncheckedCreateNestedManyWithoutRelatedToIncidentsInput>;
export const IncidentUncheckedCreateNestedManyWithoutRelatedToIncidentsInputObjectSchema: SchemaType =
  z
    .object({
      create: z
        .union([
          z.lazy(
            () => IncidentCreateWithoutRelatedToIncidentsInputObjectSchema
          ),
          z
            .lazy(
              () => IncidentCreateWithoutRelatedToIncidentsInputObjectSchema
            )
            .array(),
          z.lazy(
            () =>
              IncidentUncheckedCreateWithoutRelatedToIncidentsInputObjectSchema
          ),
          z
            .lazy(
              () =>
                IncidentUncheckedCreateWithoutRelatedToIncidentsInputObjectSchema
            )
            .array()
        ])
        .optional(),
      connectOrCreate: z
        .union([
          z.lazy(
            () =>
              IncidentCreateOrConnectWithoutRelatedToIncidentsInputObjectSchema
          ),
          z
            .lazy(
              () =>
                IncidentCreateOrConnectWithoutRelatedToIncidentsInputObjectSchema
            )
            .array()
        ])
        .optional(),
      connect: z
        .union([
          z.lazy(() => IncidentWhereUniqueInputObjectSchema),
          z.lazy(() => IncidentWhereUniqueInputObjectSchema).array()
        ])
        .optional()
    })
    .strict() as SchemaType;
