/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { SortOrderSchema } from '../enums/SortOrder.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.IncidentAvgOrderByAggregateInput>;
export const IncidentAvgOrderByAggregateInputObjectSchema: SchemaType = z
  .object({
    responseTime: z.lazy(() => SortOrderSchema).optional(),
    resolutionTime: z.lazy(() => SortOrderSchema).optional(),
    priority: z.lazy(() => SortOrderSchema).optional()
  })
  .strict() as SchemaType;
