/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.IncidentUpdatetagsInput>;
export const IncidentUpdatetagsInputObjectSchema: SchemaType = z
  .object({
    set: z.string().array().optional(),
    push: z.union([z.string(), z.string().array()]).optional()
  })
  .strict() as SchemaType;
