/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { IncidentCreateWithoutAttachmentsInputObjectSchema } from './IncidentCreateWithoutAttachmentsInput.schema';
import { IncidentUncheckedCreateWithoutAttachmentsInputObjectSchema } from './IncidentUncheckedCreateWithoutAttachmentsInput.schema';
import { IncidentCreateOrConnectWithoutAttachmentsInputObjectSchema } from './IncidentCreateOrConnectWithoutAttachmentsInput.schema';
import { IncidentWhereUniqueInputObjectSchema } from './IncidentWhereUniqueInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.IncidentUncheckedCreateNestedManyWithoutAttachmentsInput>;
export const IncidentUncheckedCreateNestedManyWithoutAttachmentsInputObjectSchema: SchemaType =
  z
    .object({
      create: z
        .union([
          z.lazy(() => IncidentCreateWithoutAttachmentsInputObjectSchema),
          z
            .lazy(() => IncidentCreateWithoutAttachmentsInputObjectSchema)
            .array(),
          z.lazy(
            () => IncidentUncheckedCreateWithoutAttachmentsInputObjectSchema
          ),
          z
            .lazy(
              () => IncidentUncheckedCreateWithoutAttachmentsInputObjectSchema
            )
            .array()
        ])
        .optional(),
      connectOrCreate: z
        .union([
          z.lazy(
            () => IncidentCreateOrConnectWithoutAttachmentsInputObjectSchema
          ),
          z
            .lazy(
              () => IncidentCreateOrConnectWithoutAttachmentsInputObjectSchema
            )
            .array()
        ])
        .optional(),
      connect: z
        .union([
          z.lazy(() => IncidentWhereUniqueInputObjectSchema),
          z.lazy(() => IncidentWhereUniqueInputObjectSchema).array()
        ])
        .optional()
    })
    .strict() as SchemaType;
