/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { AuditLogEventTypeSchema } from '../enums/AuditLogEventType.schema';
import { NestedIntFilterObjectSchema } from './NestedIntFilter.schema';
import { NestedEnumAuditLogEventTypeFilterObjectSchema } from './NestedEnumAuditLogEventTypeFilter.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.NestedEnumAuditLogEventTypeWithAggregatesFilter>;
export const NestedEnumAuditLogEventTypeWithAggregatesFilterObjectSchema: SchemaType =
  z
    .object({
      equals: z.lazy(() => AuditLogEventTypeSchema).optional(),
      in: z
        .lazy(() => AuditLogEventTypeSchema)
        .array()
        .optional(),
      notIn: z
        .lazy(() => AuditLogEventTypeSchema)
        .array()
        .optional(),
      not: z
        .union([
          z.lazy(() => AuditLogEventTypeSchema),
          z.lazy(
            () => NestedEnumAuditLogEventTypeWithAggregatesFilterObjectSchema
          )
        ])
        .optional(),
      _count: z.lazy(() => NestedIntFilterObjectSchema).optional(),
      _min: z
        .lazy(() => NestedEnumAuditLogEventTypeFilterObjectSchema)
        .optional(),
      _max: z
        .lazy(() => NestedEnumAuditLogEventTypeFilterObjectSchema)
        .optional()
    })
    .strict() as SchemaType;
