/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { EntityStatusSchema } from '../enums/EntityStatus.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.NestedEnumEntityStatusFilter>;
export const NestedEnumEntityStatusFilterObjectSchema: SchemaType = z
  .object({
    equals: z.lazy(() => EntityStatusSchema).optional(),
    in: z
      .lazy(() => EntityStatusSchema)
      .array()
      .optional(),
    notIn: z
      .lazy(() => EntityStatusSchema)
      .array()
      .optional(),
    not: z
      .union([
        z.lazy(() => EntityStatusSchema),
        z.lazy(() => NestedEnumEntityStatusFilterObjectSchema)
      ])
      .optional()
  })
  .strict() as SchemaType;
