/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { AuditSeverityLevelSchema } from '../enums/AuditSeverityLevel.schema';
import { NestedIntFilterObjectSchema } from './NestedIntFilter.schema';
import { NestedEnumAuditSeverityLevelFilterObjectSchema } from './NestedEnumAuditSeverityLevelFilter.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.NestedEnumAuditSeverityLevelWithAggregatesFilter>;
export const NestedEnumAuditSeverityLevelWithAggregatesFilterObjectSchema: SchemaType =
  z
    .object({
      equals: z.lazy(() => AuditSeverityLevelSchema).optional(),
      in: z
        .lazy(() => AuditSeverityLevelSchema)
        .array()
        .optional(),
      notIn: z
        .lazy(() => AuditSeverityLevelSchema)
        .array()
        .optional(),
      not: z
        .union([
          z.lazy(() => AuditSeverityLevelSchema),
          z.lazy(
            () => NestedEnumAuditSeverityLevelWithAggregatesFilterObjectSchema
          )
        ])
        .optional(),
      _count: z.lazy(() => NestedIntFilterObjectSchema).optional(),
      _min: z
        .lazy(() => NestedEnumAuditSeverityLevelFilterObjectSchema)
        .optional(),
      _max: z
        .lazy(() => NestedEnumAuditSeverityLevelFilterObjectSchema)
        .optional()
    })
    .strict() as SchemaType;
