/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { IncidentStatusSchema } from '../enums/IncidentStatus.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.NestedEnumIncidentStatusFilter>;
export const NestedEnumIncidentStatusFilterObjectSchema: SchemaType = z
  .object({
    equals: z.lazy(() => IncidentStatusSchema).optional(),
    in: z
      .lazy(() => IncidentStatusSchema)
      .array()
      .optional(),
    notIn: z
      .lazy(() => IncidentStatusSchema)
      .array()
      .optional(),
    not: z
      .union([
        z.lazy(() => IncidentStatusSchema),
        z.lazy(() => NestedEnumIncidentStatusFilterObjectSchema)
      ])
      .optional()
  })
  .strict() as SchemaType;
