/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { IncidentSeveritySchema } from '../enums/IncidentSeverity.schema';
import { NestedIntFilterObjectSchema } from './NestedIntFilter.schema';
import { NestedEnumIncidentSeverityFilterObjectSchema } from './NestedEnumIncidentSeverityFilter.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.NestedEnumIncidentSeverityWithAggregatesFilter>;
export const NestedEnumIncidentSeverityWithAggregatesFilterObjectSchema: SchemaType =
  z
    .object({
      equals: z.lazy(() => IncidentSeveritySchema).optional(),
      in: z
        .lazy(() => IncidentSeveritySchema)
        .array()
        .optional(),
      notIn: z
        .lazy(() => IncidentSeveritySchema)
        .array()
        .optional(),
      not: z
        .union([
          z.lazy(() => IncidentSeveritySchema),
          z.lazy(
            () => NestedEnumIncidentSeverityWithAggregatesFilterObjectSchema
          )
        ])
        .optional(),
      _count: z.lazy(() => NestedIntFilterObjectSchema).optional(),
      _min: z
        .lazy(() => NestedEnumIncidentSeverityFilterObjectSchema)
        .optional(),
      _max: z
        .lazy(() => NestedEnumIncidentSeverityFilterObjectSchema)
        .optional()
    })
    .strict() as SchemaType;
