/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { OAuthAccountCreateWithoutUserInputObjectSchema } from './OAuthAccountCreateWithoutUserInput.schema';
import { OAuthAccountUncheckedCreateWithoutUserInputObjectSchema } from './OAuthAccountUncheckedCreateWithoutUserInput.schema';
import { OAuthAccountCreateOrConnectWithoutUserInputObjectSchema } from './OAuthAccountCreateOrConnectWithoutUserInput.schema';
import { OAuthAccountUpsertWithWhereUniqueWithoutUserInputObjectSchema } from './OAuthAccountUpsertWithWhereUniqueWithoutUserInput.schema';
import { OAuthAccountCreateManyUserInputEnvelopeObjectSchema } from './OAuthAccountCreateManyUserInputEnvelope.schema';
import { OAuthAccountWhereUniqueInputObjectSchema } from './OAuthAccountWhereUniqueInput.schema';
import { OAuthAccountUpdateWithWhereUniqueWithoutUserInputObjectSchema } from './OAuthAccountUpdateWithWhereUniqueWithoutUserInput.schema';
import { OAuthAccountUpdateManyWithWhereWithoutUserInputObjectSchema } from './OAuthAccountUpdateManyWithWhereWithoutUserInput.schema';
import { OAuthAccountScalarWhereInputObjectSchema } from './OAuthAccountScalarWhereInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.OAuthAccountUpdateManyWithoutUserNestedInput>;
export const OAuthAccountUpdateManyWithoutUserNestedInputObjectSchema: SchemaType =
  z
    .object({
      create: z
        .union([
          z.lazy(() => OAuthAccountCreateWithoutUserInputObjectSchema),
          z.lazy(() => OAuthAccountCreateWithoutUserInputObjectSchema).array(),
          z.lazy(() => OAuthAccountUncheckedCreateWithoutUserInputObjectSchema),
          z
            .lazy(() => OAuthAccountUncheckedCreateWithoutUserInputObjectSchema)
            .array()
        ])
        .optional(),
      connectOrCreate: z
        .union([
          z.lazy(() => OAuthAccountCreateOrConnectWithoutUserInputObjectSchema),
          z
            .lazy(() => OAuthAccountCreateOrConnectWithoutUserInputObjectSchema)
            .array()
        ])
        .optional(),
      upsert: z
        .union([
          z.lazy(
            () => OAuthAccountUpsertWithWhereUniqueWithoutUserInputObjectSchema
          ),
          z
            .lazy(
              () =>
                OAuthAccountUpsertWithWhereUniqueWithoutUserInputObjectSchema
            )
            .array()
        ])
        .optional(),
      createMany: z
        .lazy(() => OAuthAccountCreateManyUserInputEnvelopeObjectSchema)
        .optional(),
      set: z
        .union([
          z.lazy(() => OAuthAccountWhereUniqueInputObjectSchema),
          z.lazy(() => OAuthAccountWhereUniqueInputObjectSchema).array()
        ])
        .optional(),
      disconnect: z
        .union([
          z.lazy(() => OAuthAccountWhereUniqueInputObjectSchema),
          z.lazy(() => OAuthAccountWhereUniqueInputObjectSchema).array()
        ])
        .optional(),
      delete: z
        .union([
          z.lazy(() => OAuthAccountWhereUniqueInputObjectSchema),
          z.lazy(() => OAuthAccountWhereUniqueInputObjectSchema).array()
        ])
        .optional(),
      connect: z
        .union([
          z.lazy(() => OAuthAccountWhereUniqueInputObjectSchema),
          z.lazy(() => OAuthAccountWhereUniqueInputObjectSchema).array()
        ])
        .optional(),
      update: z
        .union([
          z.lazy(
            () => OAuthAccountUpdateWithWhereUniqueWithoutUserInputObjectSchema
          ),
          z
            .lazy(
              () =>
                OAuthAccountUpdateWithWhereUniqueWithoutUserInputObjectSchema
            )
            .array()
        ])
        .optional(),
      updateMany: z
        .union([
          z.lazy(
            () => OAuthAccountUpdateManyWithWhereWithoutUserInputObjectSchema
          ),
          z
            .lazy(
              () => OAuthAccountUpdateManyWithWhereWithoutUserInputObjectSchema
            )
            .array()
        ])
        .optional(),
      deleteMany: z
        .union([
          z.lazy(() => OAuthAccountScalarWhereInputObjectSchema),
          z.lazy(() => OAuthAccountScalarWhereInputObjectSchema).array()
        ])
        .optional()
    })
    .strict() as SchemaType;
