/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.OAuthAccountProviderProviderAccountIdCompoundUniqueInput>;
export const OAuthAccountProviderProviderAccountIdCompoundUniqueInputObjectSchema: SchemaType =
  z
    .object({
      provider: z.string(),
      providerAccountId: z.string()
    })
    .strict() as SchemaType;
