/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { OAuthAccountWhereUniqueInputObjectSchema } from './OAuthAccountWhereUniqueInput.schema';
import { OAuthAccountCreateWithoutUserInputObjectSchema } from './OAuthAccountCreateWithoutUserInput.schema';
import { OAuthAccountUncheckedCreateWithoutUserInputObjectSchema } from './OAuthAccountUncheckedCreateWithoutUserInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.OAuthAccountCreateOrConnectWithoutUserInput>;
export const OAuthAccountCreateOrConnectWithoutUserInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => OAuthAccountWhereUniqueInputObjectSchema),
      create: z.union([
        z.lazy(() => OAuthAccountCreateWithoutUserInputObjectSchema),
        z.lazy(() => OAuthAccountUncheckedCreateWithoutUserInputObjectSchema)
      ])
    })
    .strict() as SchemaType;
