/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.OAuthAccountCreateManyUserInput>;
export const OAuthAccountCreateManyUserInputObjectSchema: SchemaType = z
  .object({
    createdAt: z.union([z.date().optional(), z.string().datetime().optional()]),
    updatedAt: z.union([z.date().optional(), z.string().datetime().optional()]),
    createdBy: z.union([z.string(), z.null()]).optional().nullable(),
    updatedBy: z.union([z.string(), z.null()]).optional().nullable(),
    id: z.string().optional(),
    provider: z.string(),
    providerAccountId: z.string(),
    accessToken: z.union([z.string(), z.null()]).optional().nullable(),
    refreshToken: z.union([z.string(), z.null()]).optional().nullable(),
    expiresAt: z
      .union([z.union([z.date(), z.string().datetime().optional()]), z.null()])
      .optional()
      .nullable(),
    scope: z.union([z.string(), z.null()]).optional().nullable(),
    idToken: z.union([z.string(), z.null()]).optional().nullable(),
    tokenType: z.union([z.string(), z.null()]).optional().nullable(),
    sessionState: z.union([z.string(), z.null()]).optional().nullable()
  })
  .strict() as SchemaType;
