/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.OAuthAccountCountAggregateInputType>;
export const OAuthAccountCountAggregateInputObjectSchema: SchemaType = z
  .object({
    createdAt: z.literal(true).optional(),
    updatedAt: z.literal(true).optional(),
    createdBy: z.literal(true).optional(),
    updatedBy: z.literal(true).optional(),
    id: z.literal(true).optional(),
    provider: z.literal(true).optional(),
    providerAccountId: z.literal(true).optional(),
    accessToken: z.literal(true).optional(),
    refreshToken: z.literal(true).optional(),
    expiresAt: z.literal(true).optional(),
    scope: z.literal(true).optional(),
    idToken: z.literal(true).optional(),
    tokenType: z.literal(true).optional(),
    sessionState: z.literal(true).optional(),
    userId: z.literal(true).optional(),
    _all: z.literal(true).optional()
  })
  .strict() as SchemaType;
