/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { OAuthAccountWhereInputObjectSchema } from './OAuthAccountWhereInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.OAuthAccountListRelationFilter>;
export const OAuthAccountListRelationFilterObjectSchema: SchemaType = z
  .object({
    every: z.lazy(() => OAuthAccountWhereInputObjectSchema).optional(),
    some: z.lazy(() => OAuthAccountWhereInputObjectSchema).optional(),
    none: z.lazy(() => OAuthAccountWhereInputObjectSchema).optional()
  })
  .strict() as SchemaType;
