/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { DateTimeWithAggregatesFilterObjectSchema } from './DateTimeWithAggregatesFilter.schema';
import { StringNullableWithAggregatesFilterObjectSchema } from './StringNullableWithAggregatesFilter.schema';
import { StringWithAggregatesFilterObjectSchema } from './StringWithAggregatesFilter.schema';
import { DateTimeNullableWithAggregatesFilterObjectSchema } from './DateTimeNullableWithAggregatesFilter.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.OAuthAccountScalarWhereWithAggregatesInput>;
export const OAuthAccountScalarWhereWithAggregatesInputObjectSchema: SchemaType =
  z
    .object({
      AND: z
        .union([
          z.lazy(() => OAuthAccountScalarWhereWithAggregatesInputObjectSchema),
          z
            .lazy(() => OAuthAccountScalarWhereWithAggregatesInputObjectSchema)
            .array()
        ])
        .optional(),
      OR: z
        .lazy(() => OAuthAccountScalarWhereWithAggregatesInputObjectSchema)
        .array()
        .optional(),
      NOT: z
        .union([
          z.lazy(() => OAuthAccountScalarWhereWithAggregatesInputObjectSchema),
          z
            .lazy(() => OAuthAccountScalarWhereWithAggregatesInputObjectSchema)
            .array()
        ])
        .optional(),
      createdAt: z
        .union([
          z.lazy(() => DateTimeWithAggregatesFilterObjectSchema),
          z.union([z.date(), z.string().datetime().optional()])
        ])
        .optional(),
      updatedAt: z
        .union([
          z.lazy(() => DateTimeWithAggregatesFilterObjectSchema),
          z.union([z.date(), z.string().datetime().optional()])
        ])
        .optional(),
      createdBy: z
        .union([
          z.lazy(() => StringNullableWithAggregatesFilterObjectSchema),
          z.string(),
          z.null()
        ])
        .optional()
        .nullable(),
      updatedBy: z
        .union([
          z.lazy(() => StringNullableWithAggregatesFilterObjectSchema),
          z.string(),
          z.null()
        ])
        .optional()
        .nullable(),
      id: z
        .union([
          z.lazy(() => StringWithAggregatesFilterObjectSchema),
          z.string()
        ])
        .optional(),
      provider: z
        .union([
          z.lazy(() => StringWithAggregatesFilterObjectSchema),
          z.string()
        ])
        .optional(),
      providerAccountId: z
        .union([
          z.lazy(() => StringWithAggregatesFilterObjectSchema),
          z.string()
        ])
        .optional(),
      accessToken: z
        .union([
          z.lazy(() => StringNullableWithAggregatesFilterObjectSchema),
          z.string(),
          z.null()
        ])
        .optional()
        .nullable(),
      refreshToken: z
        .union([
          z.lazy(() => StringNullableWithAggregatesFilterObjectSchema),
          z.string(),
          z.null()
        ])
        .optional()
        .nullable(),
      expiresAt: z
        .union([
          z.lazy(() => DateTimeNullableWithAggregatesFilterObjectSchema),
          z.union([z.date(), z.string().datetime().optional()]),
          z.null()
        ])
        .optional()
        .nullable(),
      scope: z
        .union([
          z.lazy(() => StringNullableWithAggregatesFilterObjectSchema),
          z.string(),
          z.null()
        ])
        .optional()
        .nullable(),
      idToken: z
        .union([
          z.lazy(() => StringNullableWithAggregatesFilterObjectSchema),
          z.string(),
          z.null()
        ])
        .optional()
        .nullable(),
      tokenType: z
        .union([
          z.lazy(() => StringNullableWithAggregatesFilterObjectSchema),
          z.string(),
          z.null()
        ])
        .optional()
        .nullable(),
      sessionState: z
        .union([
          z.lazy(() => StringNullableWithAggregatesFilterObjectSchema),
          z.string(),
          z.null()
        ])
        .optional()
        .nullable(),
      userId: z
        .union([
          z.lazy(() => StringWithAggregatesFilterObjectSchema),
          z.string()
        ])
        .optional()
    })
    .strict() as SchemaType;
