/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { SortOrderSchema } from '../enums/SortOrder.schema';
import { SortOrderInputObjectSchema } from './SortOrderInput.schema';
import { IncidentOrderByRelationAggregateInputObjectSchema } from './IncidentOrderByRelationAggregateInput.schema';
import { UserOrderByWithRelationInputObjectSchema } from './UserOrderByWithRelationInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ObjectStorageFileOrderByWithRelationInput>;
export const ObjectStorageFileOrderByWithRelationInputObjectSchema: SchemaType =
  z
    .object({
      createdAt: z.lazy(() => SortOrderSchema).optional(),
      updatedAt: z.lazy(() => SortOrderSchema).optional(),
      createdBy: z
        .union([
          z.lazy(() => SortOrderSchema),
          z.lazy(() => SortOrderInputObjectSchema)
        ])
        .optional(),
      updatedBy: z
        .union([
          z.lazy(() => SortOrderSchema),
          z.lazy(() => SortOrderInputObjectSchema)
        ])
        .optional(),
      id: z.lazy(() => SortOrderSchema).optional(),
      objectKey: z.lazy(() => SortOrderSchema).optional(),
      objectBucket: z.lazy(() => SortOrderSchema).optional(),
      sizeInBytes: z.lazy(() => SortOrderSchema).optional(),
      mimeType: z.lazy(() => SortOrderSchema).optional(),
      metadata: z
        .union([
          z.lazy(() => SortOrderSchema),
          z.lazy(() => SortOrderInputObjectSchema)
        ])
        .optional(),
      incidents: z
        .lazy(() => IncidentOrderByRelationAggregateInputObjectSchema)
        .optional(),
      profilePictureUser: z
        .lazy(() => UserOrderByWithRelationInputObjectSchema)
        .optional()
    })
    .strict() as SchemaType;
