/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { SortOrderSchema } from '../enums/SortOrder.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ObjectStorageFileAvgOrderByAggregateInput>;
export const ObjectStorageFileAvgOrderByAggregateInputObjectSchema: SchemaType =
  z
    .object({
      sizeInBytes: z.lazy(() => SortOrderSchema).optional()
    })
    .strict() as SchemaType;
