/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ObjectStorageFileMinAggregateInputType>;
export const ObjectStorageFileMinAggregateInputObjectSchema: SchemaType = z
  .object({
    createdAt: z.literal(true).optional(),
    updatedAt: z.literal(true).optional(),
    createdBy: z.literal(true).optional(),
    updatedBy: z.literal(true).optional(),
    id: z.literal(true).optional(),
    objectKey: z.literal(true).optional(),
    objectBucket: z.literal(true).optional(),
    sizeInBytes: z.literal(true).optional(),
    mimeType: z.literal(true).optional()
  })
  .strict() as SchemaType;
