/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { ObjectStorageFileSelectObjectSchema } from './ObjectStorageFileSelect.schema';
import { ObjectStorageFileIncludeObjectSchema } from './ObjectStorageFileInclude.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ObjectStorageFileDefaultArgs>;
export const ObjectStorageFileDefaultArgsObjectSchema: SchemaType = z
  .object({
    select: z.lazy(() => ObjectStorageFileSelectObjectSchema).optional(),
    include: z.lazy(() => ObjectStorageFileIncludeObjectSchema).optional()
  })
  .strict() as SchemaType;
