/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ObjectStorageFileSumAggregateInputType>;
export const ObjectStorageFileSumAggregateInputObjectSchema: SchemaType = z
  .object({
    sizeInBytes: z.literal(true).optional()
  })
  .strict() as SchemaType;
