/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { NullableJsonNullValueInputSchema } from '../enums/NullableJsonNullValueInput.schema';
import { IncidentUncheckedCreateNestedManyWithoutAttachmentsInputObjectSchema } from './IncidentUncheckedCreateNestedManyWithoutAttachmentsInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

const literalSchema = z.union([z.string(), z.number(), z.boolean()]);
const jsonSchema: z.ZodType<Prisma.InputJsonValue> = z.lazy(() =>
  z.union([
    literalSchema,
    z.array(jsonSchema.nullable()),
    z.record(jsonSchema.nullable())
  ])
);

type SchemaType =
  z.ZodType<Prisma.ObjectStorageFileUncheckedCreateWithoutProfilePictureUserInput>;
export const ObjectStorageFileUncheckedCreateWithoutProfilePictureUserInputObjectSchema: SchemaType =
  z
    .object({
      createdAt: z.union([
        z.date().optional(),
        z.string().datetime().optional()
      ]),
      updatedAt: z.union([
        z.date().optional(),
        z.string().datetime().optional()
      ]),
      createdBy: z.union([z.string(), z.null()]).optional().nullable(),
      updatedBy: z.union([z.string(), z.null()]).optional().nullable(),
      id: z.string().optional(),
      objectKey: z.string(),
      objectBucket: z.string(),
      sizeInBytes: z.number(),
      mimeType: z.string(),
      metadata: z
        .union([z.lazy(() => NullableJsonNullValueInputSchema), jsonSchema])
        .optional(),
      incidents: z
        .lazy(
          () =>
            IncidentUncheckedCreateNestedManyWithoutAttachmentsInputObjectSchema
        )
        .optional()
    })
    .strict() as SchemaType;
