/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { ObjectStorageFileCountOutputTypeSelectObjectSchema } from './ObjectStorageFileCountOutputTypeSelect.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ObjectStorageFileCountOutputTypeDefaultArgs>;
export const ObjectStorageFileCountOutputTypeDefaultArgsObjectSchema: SchemaType =
  z
    .object({
      select: z
        .lazy(() => ObjectStorageFileCountOutputTypeSelectObjectSchema)
        .optional()
    })
    .strict() as SchemaType;
