/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { ObjectStorageFileWhereInputObjectSchema } from './ObjectStorageFileWhereInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ObjectStorageFileListRelationFilter>;
export const ObjectStorageFileListRelationFilterObjectSchema: SchemaType = z
  .object({
    every: z.lazy(() => ObjectStorageFileWhereInputObjectSchema).optional(),
    some: z.lazy(() => ObjectStorageFileWhereInputObjectSchema).optional(),
    none: z.lazy(() => ObjectStorageFileWhereInputObjectSchema).optional()
  })
  .strict() as SchemaType;
