/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { ObjectStorageFileWhereInputObjectSchema } from './ObjectStorageFileWhereInput.schema';
import { ObjectStorageFileUpdateWithoutProfilePictureUserInputObjectSchema } from './ObjectStorageFileUpdateWithoutProfilePictureUserInput.schema';
import { ObjectStorageFileUncheckedUpdateWithoutProfilePictureUserInputObjectSchema } from './ObjectStorageFileUncheckedUpdateWithoutProfilePictureUserInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.ObjectStorageFileUpdateToOneWithWhereWithoutProfilePictureUserInput>;
export const ObjectStorageFileUpdateToOneWithWhereWithoutProfilePictureUserInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => ObjectStorageFileWhereInputObjectSchema).optional(),
      data: z.union([
        z.lazy(
          () =>
            ObjectStorageFileUpdateWithoutProfilePictureUserInputObjectSchema
        ),
        z.lazy(
          () =>
            ObjectStorageFileUncheckedUpdateWithoutProfilePictureUserInputObjectSchema
        )
      ])
    })
    .strict() as SchemaType;
