/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { ObjectStorageFileWhereUniqueInputObjectSchema } from './ObjectStorageFileWhereUniqueInput.schema';
import { ObjectStorageFileCreateWithoutProfilePictureUserInputObjectSchema } from './ObjectStorageFileCreateWithoutProfilePictureUserInput.schema';
import { ObjectStorageFileUncheckedCreateWithoutProfilePictureUserInputObjectSchema } from './ObjectStorageFileUncheckedCreateWithoutProfilePictureUserInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.ObjectStorageFileCreateOrConnectWithoutProfilePictureUserInput>;
export const ObjectStorageFileCreateOrConnectWithoutProfilePictureUserInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => ObjectStorageFileWhereUniqueInputObjectSchema),
      create: z.union([
        z.lazy(
          () =>
            ObjectStorageFileCreateWithoutProfilePictureUserInputObjectSchema
        ),
        z.lazy(
          () =>
            ObjectStorageFileUncheckedCreateWithoutProfilePictureUserInputObjectSchema
        )
      ])
    })
    .strict() as SchemaType;
