/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { SortOrderSchema } from '../enums/SortOrder.schema';
import { SortOrderInputObjectSchema } from './SortOrderInput.schema';
import { ObjectStorageFileCountOrderByAggregateInputObjectSchema } from './ObjectStorageFileCountOrderByAggregateInput.schema';
import { ObjectStorageFileAvgOrderByAggregateInputObjectSchema } from './ObjectStorageFileAvgOrderByAggregateInput.schema';
import { ObjectStorageFileMaxOrderByAggregateInputObjectSchema } from './ObjectStorageFileMaxOrderByAggregateInput.schema';
import { ObjectStorageFileMinOrderByAggregateInputObjectSchema } from './ObjectStorageFileMinOrderByAggregateInput.schema';
import { ObjectStorageFileSumOrderByAggregateInputObjectSchema } from './ObjectStorageFileSumOrderByAggregateInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.ObjectStorageFileOrderByWithAggregationInput>;
export const ObjectStorageFileOrderByWithAggregationInputObjectSchema: SchemaType =
  z
    .object({
      createdAt: z.lazy(() => SortOrderSchema).optional(),
      updatedAt: z.lazy(() => SortOrderSchema).optional(),
      createdBy: z
        .union([
          z.lazy(() => SortOrderSchema),
          z.lazy(() => SortOrderInputObjectSchema)
        ])
        .optional(),
      updatedBy: z
        .union([
          z.lazy(() => SortOrderSchema),
          z.lazy(() => SortOrderInputObjectSchema)
        ])
        .optional(),
      id: z.lazy(() => SortOrderSchema).optional(),
      objectKey: z.lazy(() => SortOrderSchema).optional(),
      objectBucket: z.lazy(() => SortOrderSchema).optional(),
      sizeInBytes: z.lazy(() => SortOrderSchema).optional(),
      mimeType: z.lazy(() => SortOrderSchema).optional(),
      metadata: z
        .union([
          z.lazy(() => SortOrderSchema),
          z.lazy(() => SortOrderInputObjectSchema)
        ])
        .optional(),
      _count: z
        .lazy(() => ObjectStorageFileCountOrderByAggregateInputObjectSchema)
        .optional(),
      _avg: z
        .lazy(() => ObjectStorageFileAvgOrderByAggregateInputObjectSchema)
        .optional(),
      _max: z
        .lazy(() => ObjectStorageFileMaxOrderByAggregateInputObjectSchema)
        .optional(),
      _min: z
        .lazy(() => ObjectStorageFileMinOrderByAggregateInputObjectSchema)
        .optional(),
      _sum: z
        .lazy(() => ObjectStorageFileSumOrderByAggregateInputObjectSchema)
        .optional()
    })
    .strict() as SchemaType;
