/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { IncidentInputSchema } from '../input/IncidentInput.schema';
import { UserDefaultArgsObjectSchema } from './UserDefaultArgs.schema';
import { ObjectStorageFileCountOutputTypeDefaultArgsObjectSchema } from './ObjectStorageFileCountOutputTypeDefaultArgs.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ObjectStorageFileInclude>;
export const ObjectStorageFileIncludeObjectSchema: SchemaType = z
  .object({
    incidents: z
      .union([z.boolean(), z.lazy(() => IncidentInputSchema.findMany)])
      .optional(),
    profilePictureUser: z
      .union([z.boolean(), z.lazy(() => UserDefaultArgsObjectSchema)])
      .optional(),
    _count: z
      .union([
        z.boolean(),
        z.lazy(() => ObjectStorageFileCountOutputTypeDefaultArgsObjectSchema)
      ])
      .optional()
  })
  .strict() as SchemaType;
