/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { DateTimeFilterObjectSchema } from './DateTimeFilter.schema';
import { StringNullableFilterObjectSchema } from './StringNullableFilter.schema';
import { StringFilterObjectSchema } from './StringFilter.schema';
import { IntFilterObjectSchema } from './IntFilter.schema';
import { JsonNullableFilterObjectSchema } from './JsonNullableFilter.schema';
import { IncidentListRelationFilterObjectSchema } from './IncidentListRelationFilter.schema';
import { UserNullableScalarRelationFilterObjectSchema } from './UserNullableScalarRelationFilter.schema';
import { UserWhereInputObjectSchema } from './UserWhereInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ObjectStorageFileWhereInput>;
export const ObjectStorageFileWhereInputObjectSchema: SchemaType = z
  .object({
    AND: z
      .union([
        z.lazy(() => ObjectStorageFileWhereInputObjectSchema),
        z.lazy(() => ObjectStorageFileWhereInputObjectSchema).array()
      ])
      .optional(),
    OR: z
      .lazy(() => ObjectStorageFileWhereInputObjectSchema)
      .array()
      .optional(),
    NOT: z
      .union([
        z.lazy(() => ObjectStorageFileWhereInputObjectSchema),
        z.lazy(() => ObjectStorageFileWhereInputObjectSchema).array()
      ])
      .optional(),
    createdAt: z
      .union([
        z.lazy(() => DateTimeFilterObjectSchema),
        z.union([z.date(), z.string().datetime().optional()])
      ])
      .optional(),
    updatedAt: z
      .union([
        z.lazy(() => DateTimeFilterObjectSchema),
        z.union([z.date(), z.string().datetime().optional()])
      ])
      .optional(),
    createdBy: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    updatedBy: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    id: z
      .union([z.lazy(() => StringFilterObjectSchema), z.string()])
      .optional(),
    objectKey: z
      .union([z.lazy(() => StringFilterObjectSchema), z.string()])
      .optional(),
    objectBucket: z
      .union([z.lazy(() => StringFilterObjectSchema), z.string()])
      .optional(),
    sizeInBytes: z
      .union([z.lazy(() => IntFilterObjectSchema), z.number()])
      .optional(),
    mimeType: z
      .union([z.lazy(() => StringFilterObjectSchema), z.string()])
      .optional(),
    metadata: z.lazy(() => JsonNullableFilterObjectSchema).optional(),
    incidents: z.lazy(() => IncidentListRelationFilterObjectSchema).optional(),
    profilePictureUser: z
      .union([
        z.lazy(() => UserNullableScalarRelationFilterObjectSchema),
        z.lazy(() => UserWhereInputObjectSchema),
        z.null()
      ])
      .optional()
      .nullable()
  })
  .strict() as SchemaType;
