/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { ObjectStorageFileWhereUniqueInputObjectSchema } from './ObjectStorageFileWhereUniqueInput.schema';
import { ObjectStorageFileUpdateWithoutIncidentsInputObjectSchema } from './ObjectStorageFileUpdateWithoutIncidentsInput.schema';
import { ObjectStorageFileUncheckedUpdateWithoutIncidentsInputObjectSchema } from './ObjectStorageFileUncheckedUpdateWithoutIncidentsInput.schema';
import { ObjectStorageFileCreateWithoutIncidentsInputObjectSchema } from './ObjectStorageFileCreateWithoutIncidentsInput.schema';
import { ObjectStorageFileUncheckedCreateWithoutIncidentsInputObjectSchema } from './ObjectStorageFileUncheckedCreateWithoutIncidentsInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.ObjectStorageFileUpsertWithWhereUniqueWithoutIncidentsInput>;
export const ObjectStorageFileUpsertWithWhereUniqueWithoutIncidentsInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => ObjectStorageFileWhereUniqueInputObjectSchema),
      update: z.union([
        z.lazy(() => ObjectStorageFileUpdateWithoutIncidentsInputObjectSchema),
        z.lazy(
          () =>
            ObjectStorageFileUncheckedUpdateWithoutIncidentsInputObjectSchema
        )
      ]),
      create: z.union([
        z.lazy(() => ObjectStorageFileCreateWithoutIncidentsInputObjectSchema),
        z.lazy(
          () =>
            ObjectStorageFileUncheckedCreateWithoutIncidentsInputObjectSchema
        )
      ])
    })
    .strict() as SchemaType;
