/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { PatrolWhereInputObjectSchema } from './PatrolWhereInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.PatrolScalarRelationFilter>;
export const PatrolScalarRelationFilterObjectSchema: SchemaType = z
  .object({
    is: z.lazy(() => PatrolWhereInputObjectSchema).optional(),
    isNot: z.lazy(() => PatrolWhereInputObjectSchema).optional()
  })
  .strict() as SchemaType;
