/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { PatrolWhereInputObjectSchema } from './PatrolWhereInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.PatrolNullableScalarRelationFilter>;
export const PatrolNullableScalarRelationFilterObjectSchema: SchemaType = z
  .object({
    is: z
      .union([z.lazy(() => PatrolWhereInputObjectSchema), z.null()])
      .optional()
      .nullable(),
    isNot: z
      .union([z.lazy(() => PatrolWhereInputObjectSchema), z.null()])
      .optional()
      .nullable()
  })
  .strict() as SchemaType;
