/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { PatrolClientIdNameCompoundUniqueInputObjectSchema } from './PatrolClientIdNameCompoundUniqueInput.schema';
import { PatrolWhereInputObjectSchema } from './PatrolWhereInput.schema';
import { DateTimeFilterObjectSchema } from './DateTimeFilter.schema';
import { StringNullableFilterObjectSchema } from './StringNullableFilter.schema';
import { StringFilterObjectSchema } from './StringFilter.schema';
import { EnumEntityStatusFilterObjectSchema } from './EnumEntityStatusFilter.schema';
import { EntityStatusSchema } from '../enums/EntityStatus.schema';
import { JsonNullableFilterObjectSchema } from './JsonNullableFilter.schema';
import { ClientScalarRelationFilterObjectSchema } from './ClientScalarRelationFilter.schema';
import { ClientWhereInputObjectSchema } from './ClientWhereInput.schema';
import { IncidentListRelationFilterObjectSchema } from './IncidentListRelationFilter.schema';
import { ResourceMemberListRelationFilterObjectSchema } from './ResourceMemberListRelationFilter.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.PatrolWhereUniqueInput>;
export const PatrolWhereUniqueInputObjectSchema: SchemaType = z
  .object({
    id: z.string().optional(),
    clientId_name: z
      .lazy(() => PatrolClientIdNameCompoundUniqueInputObjectSchema)
      .optional(),
    AND: z
      .union([
        z.lazy(() => PatrolWhereInputObjectSchema),
        z.lazy(() => PatrolWhereInputObjectSchema).array()
      ])
      .optional(),
    OR: z
      .lazy(() => PatrolWhereInputObjectSchema)
      .array()
      .optional(),
    NOT: z
      .union([
        z.lazy(() => PatrolWhereInputObjectSchema),
        z.lazy(() => PatrolWhereInputObjectSchema).array()
      ])
      .optional(),
    createdAt: z
      .union([
        z.lazy(() => DateTimeFilterObjectSchema),
        z.union([z.date(), z.string().datetime().optional()])
      ])
      .optional(),
    updatedAt: z
      .union([
        z.lazy(() => DateTimeFilterObjectSchema),
        z.union([z.date(), z.string().datetime().optional()])
      ])
      .optional(),
    createdBy: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    updatedBy: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    name: z
      .union([z.lazy(() => StringFilterObjectSchema), z.string()])
      .optional(),
    description: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    status: z
      .union([
        z.lazy(() => EnumEntityStatusFilterObjectSchema),
        z.lazy(() => EntityStatusSchema)
      ])
      .optional(),
    address: z.lazy(() => JsonNullableFilterObjectSchema).optional(),
    patrolSettings: z.lazy(() => JsonNullableFilterObjectSchema).optional(),
    clientId: z
      .union([z.lazy(() => StringFilterObjectSchema), z.string()])
      .optional(),
    client: z
      .union([
        z.lazy(() => ClientScalarRelationFilterObjectSchema),
        z.lazy(() => ClientWhereInputObjectSchema)
      ])
      .optional(),
    incidents: z.lazy(() => IncidentListRelationFilterObjectSchema).optional(),
    members: z
      .lazy(() => ResourceMemberListRelationFilterObjectSchema)
      .optional()
  })
  .strict() as SchemaType;
