/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.PatrolClientIdNameCompoundUniqueInput>;
export const PatrolClientIdNameCompoundUniqueInputObjectSchema: SchemaType = z
  .object({
    clientId: z.string(),
    name: z.string()
  })
  .strict() as SchemaType;
