/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { ClientDefaultArgsObjectSchema } from './ClientDefaultArgs.schema';
import { IncidentInputSchema } from '../input/IncidentInput.schema';
import { ResourceMemberInputSchema } from '../input/ResourceMemberInput.schema';
import { PatrolCountOutputTypeDefaultArgsObjectSchema } from './PatrolCountOutputTypeDefaultArgs.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.PatrolInclude>;
export const PatrolIncludeObjectSchema: SchemaType = z
  .object({
    client: z
      .union([z.boolean(), z.lazy(() => ClientDefaultArgsObjectSchema)])
      .optional(),
    incidents: z
      .union([z.boolean(), z.lazy(() => IncidentInputSchema.findMany)])
      .optional(),
    members: z
      .union([z.boolean(), z.lazy(() => ResourceMemberInputSchema.findMany)])
      .optional(),
    _count: z
      .union([
        z.boolean(),
        z.lazy(() => PatrolCountOutputTypeDefaultArgsObjectSchema)
      ])
      .optional()
  })
  .strict() as SchemaType;
