/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { PatrolWhereUniqueInputObjectSchema } from './PatrolWhereUniqueInput.schema';
import { PatrolCreateWithoutClientInputObjectSchema } from './PatrolCreateWithoutClientInput.schema';
import { PatrolUncheckedCreateWithoutClientInputObjectSchema } from './PatrolUncheckedCreateWithoutClientInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.PatrolCreateOrConnectWithoutClientInput>;
export const PatrolCreateOrConnectWithoutClientInputObjectSchema: SchemaType = z
  .object({
    where: z.lazy(() => PatrolWhereUniqueInputObjectSchema),
    create: z.union([
      z.lazy(() => PatrolCreateWithoutClientInputObjectSchema),
      z.lazy(() => PatrolUncheckedCreateWithoutClientInputObjectSchema)
    ])
  })
  .strict() as SchemaType;
