/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { PatrolWhereInputObjectSchema } from './PatrolWhereInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.PatrolListRelationFilter>;
export const PatrolListRelationFilterObjectSchema: SchemaType = z
  .object({
    every: z.lazy(() => PatrolWhereInputObjectSchema).optional(),
    some: z.lazy(() => PatrolWhereInputObjectSchema).optional(),
    none: z.lazy(() => PatrolWhereInputObjectSchema).optional()
  })
  .strict() as SchemaType;
