/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { ClientDefaultArgsObjectSchema } from './ClientDefaultArgs.schema';
import { IncidentInputSchema } from '../input/IncidentInput.schema';
import { ResourceMemberInputSchema } from '../input/ResourceMemberInput.schema';
import { PatrolCountOutputTypeDefaultArgsObjectSchema } from './PatrolCountOutputTypeDefaultArgs.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.PatrolSelect>;
export const PatrolSelectObjectSchema: SchemaType = z
  .object({
    createdAt: z.boolean().optional(),
    updatedAt: z.boolean().optional(),
    createdBy: z.boolean().optional(),
    updatedBy: z.boolean().optional(),
    id: z.boolean().optional(),
    name: z.boolean().optional(),
    description: z.boolean().optional(),
    status: z.boolean().optional(),
    address: z.boolean().optional(),
    patrolSettings: z.boolean().optional(),
    client: z
      .union([z.boolean(), z.lazy(() => ClientDefaultArgsObjectSchema)])
      .optional(),
    clientId: z.boolean().optional(),
    incidents: z
      .union([z.boolean(), z.lazy(() => IncidentInputSchema.findMany)])
      .optional(),
    members: z
      .union([z.boolean(), z.lazy(() => ResourceMemberInputSchema.findMany)])
      .optional(),
    _count: z
      .union([
        z.boolean(),
        z.lazy(() => PatrolCountOutputTypeDefaultArgsObjectSchema)
      ])
      .optional()
  })
  .strict() as SchemaType;
