/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { PatrolCreateManyClientInputObjectSchema } from './PatrolCreateManyClientInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.PatrolCreateManyClientInputEnvelope>;
export const PatrolCreateManyClientInputEnvelopeObjectSchema: SchemaType = z
  .object({
    data: z.union([
      z.lazy(() => PatrolCreateManyClientInputObjectSchema),
      z.lazy(() => PatrolCreateManyClientInputObjectSchema).array()
    ]),
    skipDuplicates: z.boolean().optional()
  })
  .strict() as SchemaType;
