/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { PatrolWhereInputObjectSchema } from './PatrolWhereInput.schema';
import { PatrolUpdateWithoutIncidentsInputObjectSchema } from './PatrolUpdateWithoutIncidentsInput.schema';
import { PatrolUncheckedUpdateWithoutIncidentsInputObjectSchema } from './PatrolUncheckedUpdateWithoutIncidentsInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.PatrolUpdateToOneWithWhereWithoutIncidentsInput>;
export const PatrolUpdateToOneWithWhereWithoutIncidentsInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => PatrolWhereInputObjectSchema).optional(),
      data: z.union([
        z.lazy(() => PatrolUpdateWithoutIncidentsInputObjectSchema),
        z.lazy(() => PatrolUncheckedUpdateWithoutIncidentsInputObjectSchema)
      ])
    })
    .strict() as SchemaType;
