/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { PatrolSelectObjectSchema } from './PatrolSelect.schema';
import { PatrolIncludeObjectSchema } from './PatrolInclude.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.PatrolDefaultArgs>;
export const PatrolDefaultArgsObjectSchema: SchemaType = z
  .object({
    select: z.lazy(() => PatrolSelectObjectSchema).optional(),
    include: z.lazy(() => PatrolIncludeObjectSchema).optional()
  })
  .strict() as SchemaType;
