/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { PatrolCountOutputTypeSelectObjectSchema } from './PatrolCountOutputTypeSelect.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.PatrolCountOutputTypeDefaultArgs>;
export const PatrolCountOutputTypeDefaultArgsObjectSchema: SchemaType = z
  .object({
    select: z.lazy(() => PatrolCountOutputTypeSelectObjectSchema).optional()
  })
  .strict() as SchemaType;
