/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { EntityStatusSchema } from '../enums/EntityStatus.schema';
import { NullableJsonNullValueInputSchema } from '../enums/NullableJsonNullValueInput.schema';
import { ClientCreateNestedOneWithoutPatrolsInputObjectSchema } from './ClientCreateNestedOneWithoutPatrolsInput.schema';
import { IncidentCreateNestedManyWithoutPatrolInputObjectSchema } from './IncidentCreateNestedManyWithoutPatrolInput.schema';
import { ResourceMemberCreateNestedManyWithoutPatrolInputObjectSchema } from './ResourceMemberCreateNestedManyWithoutPatrolInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

const literalSchema = z.union([z.string(), z.number(), z.boolean()]);
const jsonSchema: z.ZodType<Prisma.InputJsonValue> = z.lazy(() =>
  z.union([
    literalSchema,
    z.array(jsonSchema.nullable()),
    z.record(jsonSchema.nullable())
  ])
);

type SchemaType = z.ZodType<Prisma.PatrolCreateInput>;
export const PatrolCreateInputObjectSchema: SchemaType = z
  .object({
    createdAt: z.union([z.date().optional(), z.string().datetime().optional()]),
    updatedAt: z.union([z.date().optional(), z.string().datetime().optional()]),
    createdBy: z.union([z.string(), z.null()]).optional().nullable(),
    updatedBy: z.union([z.string(), z.null()]).optional().nullable(),
    id: z.string().optional(),
    name: z.string(),
    description: z.union([z.string(), z.null()]).optional().nullable(),
    status: z.lazy(() => EntityStatusSchema).optional(),
    address: z.lazy(() => GooglePlacesAutocompleteSchema),
    patrolSettings: z
      .union([z.lazy(() => NullableJsonNullValueInputSchema), jsonSchema])
      .optional(),
    client: z.lazy(() => ClientCreateNestedOneWithoutPatrolsInputObjectSchema),
    incidents: z
      .lazy(() => IncidentCreateNestedManyWithoutPatrolInputObjectSchema)
      .optional(),
    members: z
      .lazy(() => ResourceMemberCreateNestedManyWithoutPatrolInputObjectSchema)
      .optional()
  })
  .strict() as SchemaType;
