/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { ResourceMemberWhereInputObjectSchema } from './ResourceMemberWhereInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ResourceMemberListRelationFilter>;
export const ResourceMemberListRelationFilterObjectSchema: SchemaType = z
  .object({
    every: z.lazy(() => ResourceMemberWhereInputObjectSchema).optional(),
    some: z.lazy(() => ResourceMemberWhereInputObjectSchema).optional(),
    none: z.lazy(() => ResourceMemberWhereInputObjectSchema).optional()
  })
  .strict() as SchemaType;
