/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { ResourceMemberCreateWithoutPatrolInputObjectSchema } from './ResourceMemberCreateWithoutPatrolInput.schema';
import { ResourceMemberUncheckedCreateWithoutPatrolInputObjectSchema } from './ResourceMemberUncheckedCreateWithoutPatrolInput.schema';
import { ResourceMemberCreateOrConnectWithoutPatrolInputObjectSchema } from './ResourceMemberCreateOrConnectWithoutPatrolInput.schema';
import { ResourceMemberUpsertWithWhereUniqueWithoutPatrolInputObjectSchema } from './ResourceMemberUpsertWithWhereUniqueWithoutPatrolInput.schema';
import { ResourceMemberCreateManyPatrolInputEnvelopeObjectSchema } from './ResourceMemberCreateManyPatrolInputEnvelope.schema';
import { ResourceMemberWhereUniqueInputObjectSchema } from './ResourceMemberWhereUniqueInput.schema';
import { ResourceMemberUpdateWithWhereUniqueWithoutPatrolInputObjectSchema } from './ResourceMemberUpdateWithWhereUniqueWithoutPatrolInput.schema';
import { ResourceMemberUpdateManyWithWhereWithoutPatrolInputObjectSchema } from './ResourceMemberUpdateManyWithWhereWithoutPatrolInput.schema';
import { ResourceMemberScalarWhereInputObjectSchema } from './ResourceMemberScalarWhereInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.ResourceMemberUpdateManyWithoutPatrolNestedInput>;
export const ResourceMemberUpdateManyWithoutPatrolNestedInputObjectSchema: SchemaType =
  z
    .object({
      create: z
        .union([
          z.lazy(() => ResourceMemberCreateWithoutPatrolInputObjectSchema),
          z
            .lazy(() => ResourceMemberCreateWithoutPatrolInputObjectSchema)
            .array(),
          z.lazy(
            () => ResourceMemberUncheckedCreateWithoutPatrolInputObjectSchema
          ),
          z
            .lazy(
              () => ResourceMemberUncheckedCreateWithoutPatrolInputObjectSchema
            )
            .array()
        ])
        .optional(),
      connectOrCreate: z
        .union([
          z.lazy(
            () => ResourceMemberCreateOrConnectWithoutPatrolInputObjectSchema
          ),
          z
            .lazy(
              () => ResourceMemberCreateOrConnectWithoutPatrolInputObjectSchema
            )
            .array()
        ])
        .optional(),
      upsert: z
        .union([
          z.lazy(
            () =>
              ResourceMemberUpsertWithWhereUniqueWithoutPatrolInputObjectSchema
          ),
          z
            .lazy(
              () =>
                ResourceMemberUpsertWithWhereUniqueWithoutPatrolInputObjectSchema
            )
            .array()
        ])
        .optional(),
      createMany: z
        .lazy(() => ResourceMemberCreateManyPatrolInputEnvelopeObjectSchema)
        .optional(),
      set: z
        .union([
          z.lazy(() => ResourceMemberWhereUniqueInputObjectSchema),
          z.lazy(() => ResourceMemberWhereUniqueInputObjectSchema).array()
        ])
        .optional(),
      disconnect: z
        .union([
          z.lazy(() => ResourceMemberWhereUniqueInputObjectSchema),
          z.lazy(() => ResourceMemberWhereUniqueInputObjectSchema).array()
        ])
        .optional(),
      delete: z
        .union([
          z.lazy(() => ResourceMemberWhereUniqueInputObjectSchema),
          z.lazy(() => ResourceMemberWhereUniqueInputObjectSchema).array()
        ])
        .optional(),
      connect: z
        .union([
          z.lazy(() => ResourceMemberWhereUniqueInputObjectSchema),
          z.lazy(() => ResourceMemberWhereUniqueInputObjectSchema).array()
        ])
        .optional(),
      update: z
        .union([
          z.lazy(
            () =>
              ResourceMemberUpdateWithWhereUniqueWithoutPatrolInputObjectSchema
          ),
          z
            .lazy(
              () =>
                ResourceMemberUpdateWithWhereUniqueWithoutPatrolInputObjectSchema
            )
            .array()
        ])
        .optional(),
      updateMany: z
        .union([
          z.lazy(
            () =>
              ResourceMemberUpdateManyWithWhereWithoutPatrolInputObjectSchema
          ),
          z
            .lazy(
              () =>
                ResourceMemberUpdateManyWithWhereWithoutPatrolInputObjectSchema
            )
            .array()
        ])
        .optional(),
      deleteMany: z
        .union([
          z.lazy(() => ResourceMemberScalarWhereInputObjectSchema),
          z.lazy(() => ResourceMemberScalarWhereInputObjectSchema).array()
        ])
        .optional()
    })
    .strict() as SchemaType;
