/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { ResourceMemberSelectObjectSchema } from './ResourceMemberSelect.schema';
import { ResourceMemberIncludeObjectSchema } from './ResourceMemberInclude.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ResourceMemberDefaultArgs>;
export const ResourceMemberDefaultArgsObjectSchema: SchemaType = z
  .object({
    select: z.lazy(() => ResourceMemberSelectObjectSchema).optional(),
    include: z.lazy(() => ResourceMemberIncludeObjectSchema).optional()
  })
  .strict() as SchemaType;
