/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { PermissionSchema } from '../enums/Permission.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ResourceMemberCreatepermissionsInput>;
export const ResourceMemberCreatepermissionsInputObjectSchema: SchemaType = z
  .object({
    set: z.lazy(() => PermissionSchema).array()
  })
  .strict() as SchemaType;
