/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { UserDefaultArgsObjectSchema } from './UserDefaultArgs.schema';
import { WorkspaceDefaultArgsObjectSchema } from './WorkspaceDefaultArgs.schema';
import { ClientDefaultArgsObjectSchema } from './ClientDefaultArgs.schema';
import { PatrolDefaultArgsObjectSchema } from './PatrolDefaultArgs.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ResourceMemberInclude>;
export const ResourceMemberIncludeObjectSchema: SchemaType = z
  .object({
    user: z
      .union([z.boolean(), z.lazy(() => UserDefaultArgsObjectSchema)])
      .optional(),
    workspace: z
      .union([z.boolean(), z.lazy(() => WorkspaceDefaultArgsObjectSchema)])
      .optional(),
    client: z
      .union([z.boolean(), z.lazy(() => ClientDefaultArgsObjectSchema)])
      .optional(),
    patrol: z
      .union([z.boolean(), z.lazy(() => PatrolDefaultArgsObjectSchema)])
      .optional()
  })
  .strict() as SchemaType;
