/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { ResourceMemberCreateManyWorkspaceInputObjectSchema } from './ResourceMemberCreateManyWorkspaceInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.ResourceMemberCreateManyWorkspaceInputEnvelope>;
export const ResourceMemberCreateManyWorkspaceInputEnvelopeObjectSchema: SchemaType =
  z
    .object({
      data: z.union([
        z.lazy(() => ResourceMemberCreateManyWorkspaceInputObjectSchema),
        z.lazy(() => ResourceMemberCreateManyWorkspaceInputObjectSchema).array()
      ]),
      skipDuplicates: z.boolean().optional()
    })
    .strict() as SchemaType;
