/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { ResourceMemberCreateManyUserInputObjectSchema } from './ResourceMemberCreateManyUserInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ResourceMemberCreateManyUserInputEnvelope>;
export const ResourceMemberCreateManyUserInputEnvelopeObjectSchema: SchemaType =
  z
    .object({
      data: z.union([
        z.lazy(() => ResourceMemberCreateManyUserInputObjectSchema),
        z.lazy(() => ResourceMemberCreateManyUserInputObjectSchema).array()
      ]),
      skipDuplicates: z.boolean().optional()
    })
    .strict() as SchemaType;
