/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { ResourceMemberCreateManyClientInputObjectSchema } from './ResourceMemberCreateManyClientInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ResourceMemberCreateManyClientInputEnvelope>;
export const ResourceMemberCreateManyClientInputEnvelopeObjectSchema: SchemaType =
  z
    .object({
      data: z.union([
        z.lazy(() => ResourceMemberCreateManyClientInputObjectSchema),
        z.lazy(() => ResourceMemberCreateManyClientInputObjectSchema).array()
      ]),
      skipDuplicates: z.boolean().optional()
    })
    .strict() as SchemaType;
