/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.ResourceMemberUserIdClientIdCompoundUniqueInput>;
export const ResourceMemberUserIdClientIdCompoundUniqueInputObjectSchema: SchemaType =
  z
    .object({
      userId: z.string(),
      clientId: z.string()
    })
    .strict() as SchemaType;
