/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { RoleSchema } from '../enums/Role.schema';
import { ResourceMemberCreatepermissionsInputObjectSchema } from './ResourceMemberCreatepermissionsInput.schema';
import { PermissionSchema } from '../enums/Permission.schema';
import { UserCreateNestedOneWithoutMembershipsInputObjectSchema } from './UserCreateNestedOneWithoutMembershipsInput.schema';
import { WorkspaceCreateNestedOneWithoutMembersInputObjectSchema } from './WorkspaceCreateNestedOneWithoutMembersInput.schema';
import { PatrolCreateNestedOneWithoutMembersInputObjectSchema } from './PatrolCreateNestedOneWithoutMembersInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ResourceMemberCreateWithoutClientInput>;
export const ResourceMemberCreateWithoutClientInputObjectSchema: SchemaType = z
  .object({
    createdAt: z.union([z.date().optional(), z.string().datetime().optional()]),
    updatedAt: z.union([z.date().optional(), z.string().datetime().optional()]),
    createdBy: z.union([z.string(), z.null()]).optional().nullable(),
    updatedBy: z.union([z.string(), z.null()]).optional().nullable(),
    id: z.string().optional(),
    role: z.lazy(() => RoleSchema),
    permissions: z
      .union([
        z.lazy(() => ResourceMemberCreatepermissionsInputObjectSchema),
        z.lazy(() => PermissionSchema).array()
      ])
      .optional(),
    user: z.lazy(() => UserCreateNestedOneWithoutMembershipsInputObjectSchema),
    workspace: z
      .lazy(() => WorkspaceCreateNestedOneWithoutMembersInputObjectSchema)
      .optional(),
    patrol: z
      .lazy(() => PatrolCreateNestedOneWithoutMembersInputObjectSchema)
      .optional()
  })
  .strict() as SchemaType;
