/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { ResourceMemberWhereUniqueInputObjectSchema } from './ResourceMemberWhereUniqueInput.schema';
import { ResourceMemberUpdateWithoutUserInputObjectSchema } from './ResourceMemberUpdateWithoutUserInput.schema';
import { ResourceMemberUncheckedUpdateWithoutUserInputObjectSchema } from './ResourceMemberUncheckedUpdateWithoutUserInput.schema';
import { ResourceMemberCreateWithoutUserInputObjectSchema } from './ResourceMemberCreateWithoutUserInput.schema';
import { ResourceMemberUncheckedCreateWithoutUserInputObjectSchema } from './ResourceMemberUncheckedCreateWithoutUserInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.ResourceMemberUpsertWithWhereUniqueWithoutUserInput>;
export const ResourceMemberUpsertWithWhereUniqueWithoutUserInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => ResourceMemberWhereUniqueInputObjectSchema),
      update: z.union([
        z.lazy(() => ResourceMemberUpdateWithoutUserInputObjectSchema),
        z.lazy(() => ResourceMemberUncheckedUpdateWithoutUserInputObjectSchema)
      ]),
      create: z.union([
        z.lazy(() => ResourceMemberCreateWithoutUserInputObjectSchema),
        z.lazy(() => ResourceMemberUncheckedCreateWithoutUserInputObjectSchema)
      ])
    })
    .strict() as SchemaType;
