/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { DateTimeWithAggregatesFilterObjectSchema } from './DateTimeWithAggregatesFilter.schema';
import { StringNullableWithAggregatesFilterObjectSchema } from './StringNullableWithAggregatesFilter.schema';
import { StringWithAggregatesFilterObjectSchema } from './StringWithAggregatesFilter.schema';
import { EnumRoleWithAggregatesFilterObjectSchema } from './EnumRoleWithAggregatesFilter.schema';
import { RoleSchema } from '../enums/Role.schema';
import { EnumPermissionNullableListFilterObjectSchema } from './EnumPermissionNullableListFilter.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.ResourceMemberScalarWhereWithAggregatesInput>;
export const ResourceMemberScalarWhereWithAggregatesInputObjectSchema: SchemaType =
  z
    .object({
      AND: z
        .union([
          z.lazy(
            () => ResourceMemberScalarWhereWithAggregatesInputObjectSchema
          ),
          z
            .lazy(
              () => ResourceMemberScalarWhereWithAggregatesInputObjectSchema
            )
            .array()
        ])
        .optional(),
      OR: z
        .lazy(() => ResourceMemberScalarWhereWithAggregatesInputObjectSchema)
        .array()
        .optional(),
      NOT: z
        .union([
          z.lazy(
            () => ResourceMemberScalarWhereWithAggregatesInputObjectSchema
          ),
          z
            .lazy(
              () => ResourceMemberScalarWhereWithAggregatesInputObjectSchema
            )
            .array()
        ])
        .optional(),
      createdAt: z
        .union([
          z.lazy(() => DateTimeWithAggregatesFilterObjectSchema),
          z.union([z.date(), z.string().datetime().optional()])
        ])
        .optional(),
      updatedAt: z
        .union([
          z.lazy(() => DateTimeWithAggregatesFilterObjectSchema),
          z.union([z.date(), z.string().datetime().optional()])
        ])
        .optional(),
      createdBy: z
        .union([
          z.lazy(() => StringNullableWithAggregatesFilterObjectSchema),
          z.string(),
          z.null()
        ])
        .optional()
        .nullable(),
      updatedBy: z
        .union([
          z.lazy(() => StringNullableWithAggregatesFilterObjectSchema),
          z.string(),
          z.null()
        ])
        .optional()
        .nullable(),
      id: z
        .union([
          z.lazy(() => StringWithAggregatesFilterObjectSchema),
          z.string()
        ])
        .optional(),
      userId: z
        .union([
          z.lazy(() => StringWithAggregatesFilterObjectSchema),
          z.string()
        ])
        .optional(),
      workspaceId: z
        .union([
          z.lazy(() => StringNullableWithAggregatesFilterObjectSchema),
          z.string(),
          z.null()
        ])
        .optional()
        .nullable(),
      clientId: z
        .union([
          z.lazy(() => StringNullableWithAggregatesFilterObjectSchema),
          z.string(),
          z.null()
        ])
        .optional()
        .nullable(),
      patrolId: z
        .union([
          z.lazy(() => StringNullableWithAggregatesFilterObjectSchema),
          z.string(),
          z.null()
        ])
        .optional()
        .nullable(),
      role: z
        .union([
          z.lazy(() => EnumRoleWithAggregatesFilterObjectSchema),
          z.lazy(() => RoleSchema)
        ])
        .optional(),
      permissions: z
        .lazy(() => EnumPermissionNullableListFilterObjectSchema)
        .optional()
    })
    .strict() as SchemaType;
