/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { DateTimeFilterObjectSchema } from './DateTimeFilter.schema';
import { StringNullableFilterObjectSchema } from './StringNullableFilter.schema';
import { StringFilterObjectSchema } from './StringFilter.schema';
import { EnumRoleFilterObjectSchema } from './EnumRoleFilter.schema';
import { RoleSchema } from '../enums/Role.schema';
import { EnumPermissionNullableListFilterObjectSchema } from './EnumPermissionNullableListFilter.schema';
import { UserScalarRelationFilterObjectSchema } from './UserScalarRelationFilter.schema';
import { UserWhereInputObjectSchema } from './UserWhereInput.schema';
import { WorkspaceNullableScalarRelationFilterObjectSchema } from './WorkspaceNullableScalarRelationFilter.schema';
import { WorkspaceWhereInputObjectSchema } from './WorkspaceWhereInput.schema';
import { ClientNullableScalarRelationFilterObjectSchema } from './ClientNullableScalarRelationFilter.schema';
import { ClientWhereInputObjectSchema } from './ClientWhereInput.schema';
import { PatrolNullableScalarRelationFilterObjectSchema } from './PatrolNullableScalarRelationFilter.schema';
import { PatrolWhereInputObjectSchema } from './PatrolWhereInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ResourceMemberWhereInput>;
export const ResourceMemberWhereInputObjectSchema: SchemaType = z
  .object({
    AND: z
      .union([
        z.lazy(() => ResourceMemberWhereInputObjectSchema),
        z.lazy(() => ResourceMemberWhereInputObjectSchema).array()
      ])
      .optional(),
    OR: z
      .lazy(() => ResourceMemberWhereInputObjectSchema)
      .array()
      .optional(),
    NOT: z
      .union([
        z.lazy(() => ResourceMemberWhereInputObjectSchema),
        z.lazy(() => ResourceMemberWhereInputObjectSchema).array()
      ])
      .optional(),
    createdAt: z
      .union([
        z.lazy(() => DateTimeFilterObjectSchema),
        z.union([z.date(), z.string().datetime().optional()])
      ])
      .optional(),
    updatedAt: z
      .union([
        z.lazy(() => DateTimeFilterObjectSchema),
        z.union([z.date(), z.string().datetime().optional()])
      ])
      .optional(),
    createdBy: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    updatedBy: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    id: z
      .union([z.lazy(() => StringFilterObjectSchema), z.string()])
      .optional(),
    userId: z
      .union([z.lazy(() => StringFilterObjectSchema), z.string()])
      .optional(),
    workspaceId: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    clientId: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    patrolId: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    role: z
      .union([
        z.lazy(() => EnumRoleFilterObjectSchema),
        z.lazy(() => RoleSchema)
      ])
      .optional(),
    permissions: z
      .lazy(() => EnumPermissionNullableListFilterObjectSchema)
      .optional(),
    user: z
      .union([
        z.lazy(() => UserScalarRelationFilterObjectSchema),
        z.lazy(() => UserWhereInputObjectSchema)
      ])
      .optional(),
    workspace: z
      .union([
        z.lazy(() => WorkspaceNullableScalarRelationFilterObjectSchema),
        z.lazy(() => WorkspaceWhereInputObjectSchema),
        z.null()
      ])
      .optional()
      .nullable(),
    client: z
      .union([
        z.lazy(() => ClientNullableScalarRelationFilterObjectSchema),
        z.lazy(() => ClientWhereInputObjectSchema),
        z.null()
      ])
      .optional()
      .nullable(),
    patrol: z
      .union([
        z.lazy(() => PatrolNullableScalarRelationFilterObjectSchema),
        z.lazy(() => PatrolWhereInputObjectSchema),
        z.null()
      ])
      .optional()
      .nullable()
  })
  .strict() as SchemaType;
