/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { SortOrderSchema } from '../enums/SortOrder.schema';
import { SortOrderInputObjectSchema } from './SortOrderInput.schema';
import { ResourceMemberCountOrderByAggregateInputObjectSchema } from './ResourceMemberCountOrderByAggregateInput.schema';
import { ResourceMemberMaxOrderByAggregateInputObjectSchema } from './ResourceMemberMaxOrderByAggregateInput.schema';
import { ResourceMemberMinOrderByAggregateInputObjectSchema } from './ResourceMemberMinOrderByAggregateInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.ResourceMemberOrderByWithAggregationInput>;
export const ResourceMemberOrderByWithAggregationInputObjectSchema: SchemaType =
  z
    .object({
      createdAt: z.lazy(() => SortOrderSchema).optional(),
      updatedAt: z.lazy(() => SortOrderSchema).optional(),
      createdBy: z
        .union([
          z.lazy(() => SortOrderSchema),
          z.lazy(() => SortOrderInputObjectSchema)
        ])
        .optional(),
      updatedBy: z
        .union([
          z.lazy(() => SortOrderSchema),
          z.lazy(() => SortOrderInputObjectSchema)
        ])
        .optional(),
      id: z.lazy(() => SortOrderSchema).optional(),
      userId: z.lazy(() => SortOrderSchema).optional(),
      workspaceId: z
        .union([
          z.lazy(() => SortOrderSchema),
          z.lazy(() => SortOrderInputObjectSchema)
        ])
        .optional(),
      clientId: z
        .union([
          z.lazy(() => SortOrderSchema),
          z.lazy(() => SortOrderInputObjectSchema)
        ])
        .optional(),
      patrolId: z
        .union([
          z.lazy(() => SortOrderSchema),
          z.lazy(() => SortOrderInputObjectSchema)
        ])
        .optional(),
      role: z.lazy(() => SortOrderSchema).optional(),
      permissions: z.lazy(() => SortOrderSchema).optional(),
      _count: z
        .lazy(() => ResourceMemberCountOrderByAggregateInputObjectSchema)
        .optional(),
      _max: z
        .lazy(() => ResourceMemberMaxOrderByAggregateInputObjectSchema)
        .optional(),
      _min: z
        .lazy(() => ResourceMemberMinOrderByAggregateInputObjectSchema)
        .optional()
    })
    .strict() as SchemaType;
