/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { ResourceMemberScalarWhereInputObjectSchema } from './ResourceMemberScalarWhereInput.schema';
import { ResourceMemberUpdateManyMutationInputObjectSchema } from './ResourceMemberUpdateManyMutationInput.schema';
import { ResourceMemberUncheckedUpdateManyWithoutPatrolInputObjectSchema } from './ResourceMemberUncheckedUpdateManyWithoutPatrolInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.ResourceMemberUpdateManyWithWhereWithoutPatrolInput>;
export const ResourceMemberUpdateManyWithWhereWithoutPatrolInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => ResourceMemberScalarWhereInputObjectSchema),
      data: z.union([
        z.lazy(() => ResourceMemberUpdateManyMutationInputObjectSchema),
        z.lazy(
          () => ResourceMemberUncheckedUpdateManyWithoutPatrolInputObjectSchema
        )
      ])
    })
    .strict() as SchemaType;
