/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { ResourceMemberWhereUniqueInputObjectSchema } from './ResourceMemberWhereUniqueInput.schema';
import { ResourceMemberCreateWithoutPatrolInputObjectSchema } from './ResourceMemberCreateWithoutPatrolInput.schema';
import { ResourceMemberUncheckedCreateWithoutPatrolInputObjectSchema } from './ResourceMemberUncheckedCreateWithoutPatrolInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.ResourceMemberCreateOrConnectWithoutPatrolInput>;
export const ResourceMemberCreateOrConnectWithoutPatrolInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => ResourceMemberWhereUniqueInputObjectSchema),
      create: z.union([
        z.lazy(() => ResourceMemberCreateWithoutPatrolInputObjectSchema),
        z.lazy(
          () => ResourceMemberUncheckedCreateWithoutPatrolInputObjectSchema
        )
      ])
    })
    .strict() as SchemaType;
