/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.SeedExecutionSelect>;
export const SeedExecutionSelectObjectSchema: SchemaType = z
  .object({
    createdAt: z.boolean().optional(),
    updatedAt: z.boolean().optional(),
    createdBy: z.boolean().optional(),
    updatedBy: z.boolean().optional(),
    id: z.boolean().optional(),
    seedName: z.boolean().optional(),
    executedAt: z.boolean().optional(),
    completedAt: z.boolean().optional(),
    status: z.boolean().optional(),
    error: z.boolean().optional(),
    metadata: z.boolean().optional()
  })
  .strict() as SchemaType;
