/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.SeedExecutionSeedNameExecutedAtCompoundUniqueInput>;
export const SeedExecutionSeedNameExecutedAtCompoundUniqueInputObjectSchema: SchemaType =
  z
    .object({
      seedName: z.string(),
      executedAt: z.union([z.date(), z.string().datetime()])
    })
    .strict() as SchemaType;
