/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { SeedExecutionSeedNameExecutedAtCompoundUniqueInputObjectSchema } from './SeedExecutionSeedNameExecutedAtCompoundUniqueInput.schema';
import { SeedExecutionWhereInputObjectSchema } from './SeedExecutionWhereInput.schema';
import { DateTimeFilterObjectSchema } from './DateTimeFilter.schema';
import { StringNullableFilterObjectSchema } from './StringNullableFilter.schema';
import { StringFilterObjectSchema } from './StringFilter.schema';
import { DateTimeNullableFilterObjectSchema } from './DateTimeNullableFilter.schema';
import { EnumSeedExecutionStatusFilterObjectSchema } from './EnumSeedExecutionStatusFilter.schema';
import { SeedExecutionStatusSchema } from '../enums/SeedExecutionStatus.schema';
import { JsonNullableFilterObjectSchema } from './JsonNullableFilter.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.SeedExecutionWhereUniqueInput>;
export const SeedExecutionWhereUniqueInputObjectSchema: SchemaType = z
  .object({
    id: z.string().optional(),
    seedName_executedAt: z
      .lazy(
        () => SeedExecutionSeedNameExecutedAtCompoundUniqueInputObjectSchema
      )
      .optional(),
    AND: z
      .union([
        z.lazy(() => SeedExecutionWhereInputObjectSchema),
        z.lazy(() => SeedExecutionWhereInputObjectSchema).array()
      ])
      .optional(),
    OR: z
      .lazy(() => SeedExecutionWhereInputObjectSchema)
      .array()
      .optional(),
    NOT: z
      .union([
        z.lazy(() => SeedExecutionWhereInputObjectSchema),
        z.lazy(() => SeedExecutionWhereInputObjectSchema).array()
      ])
      .optional(),
    createdAt: z
      .union([
        z.lazy(() => DateTimeFilterObjectSchema),
        z.union([z.date(), z.string().datetime().optional()])
      ])
      .optional(),
    updatedAt: z
      .union([
        z.lazy(() => DateTimeFilterObjectSchema),
        z.union([z.date(), z.string().datetime().optional()])
      ])
      .optional(),
    createdBy: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    updatedBy: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    seedName: z
      .union([z.lazy(() => StringFilterObjectSchema), z.string()])
      .optional(),
    executedAt: z
      .union([
        z.lazy(() => DateTimeFilterObjectSchema),
        z.union([z.date(), z.string().datetime().optional()])
      ])
      .optional(),
    completedAt: z
      .union([
        z.lazy(() => DateTimeNullableFilterObjectSchema),
        z.union([z.date(), z.string().datetime().optional()]),
        z.null()
      ])
      .optional()
      .nullable(),
    status: z
      .union([
        z.lazy(() => EnumSeedExecutionStatusFilterObjectSchema),
        z.lazy(() => SeedExecutionStatusSchema)
      ])
      .optional(),
    error: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    metadata: z.lazy(() => JsonNullableFilterObjectSchema).optional()
  })
  .strict() as SchemaType;
