/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { SeedExecutionSelectObjectSchema } from './SeedExecutionSelect.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.SeedExecutionDefaultArgs>;
export const SeedExecutionDefaultArgsObjectSchema: SchemaType = z
  .object({
    select: z.lazy(() => SeedExecutionSelectObjectSchema).optional()
  })
  .strict() as SchemaType;
