/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { UserWhereInputObjectSchema } from './UserWhereInput.schema';
import { UserUpdateWithoutProfilePictureInputObjectSchema } from './UserUpdateWithoutProfilePictureInput.schema';
import { UserUncheckedUpdateWithoutProfilePictureInputObjectSchema } from './UserUncheckedUpdateWithoutProfilePictureInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.UserUpdateToOneWithWhereWithoutProfilePictureInput>;
export const UserUpdateToOneWithWhereWithoutProfilePictureInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => UserWhereInputObjectSchema).optional(),
      data: z.union([
        z.lazy(() => UserUpdateWithoutProfilePictureInputObjectSchema),
        z.lazy(() => UserUncheckedUpdateWithoutProfilePictureInputObjectSchema)
      ])
    })
    .strict() as SchemaType;
