/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { UserCreateWithoutVerificationTokensInputObjectSchema } from './UserCreateWithoutVerificationTokensInput.schema';
import { UserUncheckedCreateWithoutVerificationTokensInputObjectSchema } from './UserUncheckedCreateWithoutVerificationTokensInput.schema';
import { UserCreateOrConnectWithoutVerificationTokensInputObjectSchema } from './UserCreateOrConnectWithoutVerificationTokensInput.schema';
import { UserWhereUniqueInputObjectSchema } from './UserWhereUniqueInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.UserCreateNestedOneWithoutVerificationTokensInput>;
export const UserCreateNestedOneWithoutVerificationTokensInputObjectSchema: SchemaType =
  z
    .object({
      create: z
        .union([
          z.lazy(() => UserCreateWithoutVerificationTokensInputObjectSchema),
          z.lazy(
            () => UserUncheckedCreateWithoutVerificationTokensInputObjectSchema
          )
        ])
        .optional(),
      connectOrCreate: z
        .lazy(
          () => UserCreateOrConnectWithoutVerificationTokensInputObjectSchema
        )
        .optional(),
      connect: z.lazy(() => UserWhereUniqueInputObjectSchema).optional()
    })
    .strict() as SchemaType;
