/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { UserUpdateWithoutOauthAccountsInputObjectSchema } from './UserUpdateWithoutOauthAccountsInput.schema';
import { UserUncheckedUpdateWithoutOauthAccountsInputObjectSchema } from './UserUncheckedUpdateWithoutOauthAccountsInput.schema';
import { UserCreateWithoutOauthAccountsInputObjectSchema } from './UserCreateWithoutOauthAccountsInput.schema';
import { UserUncheckedCreateWithoutOauthAccountsInputObjectSchema } from './UserUncheckedCreateWithoutOauthAccountsInput.schema';
import { UserWhereInputObjectSchema } from './UserWhereInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.UserUpsertWithoutOauthAccountsInput>;
export const UserUpsertWithoutOauthAccountsInputObjectSchema: SchemaType = z
  .object({
    update: z.union([
      z.lazy(() => UserUpdateWithoutOauthAccountsInputObjectSchema),
      z.lazy(() => UserUncheckedUpdateWithoutOauthAccountsInputObjectSchema)
    ]),
    create: z.union([
      z.lazy(() => UserCreateWithoutOauthAccountsInputObjectSchema),
      z.lazy(() => UserUncheckedCreateWithoutOauthAccountsInputObjectSchema)
    ]),
    where: z.lazy(() => UserWhereInputObjectSchema).optional()
  })
  .strict() as SchemaType;
