/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { UserCreatebackupCodesInputObjectSchema } from './UserCreatebackupCodesInput.schema';
import { UserStatusSchema } from '../enums/UserStatus.schema';
import { UserCreateauthenticationMethodsInputObjectSchema } from './UserCreateauthenticationMethodsInput.schema';
import { AuthenticationMethodSchema } from '../enums/AuthenticationMethod.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.UserCreateManyInput>;
export const UserCreateManyInputObjectSchema: SchemaType = z
  .object({
    deletedAt: z
      .union([z.union([z.date(), z.string().datetime().optional()]), z.null()])
      .optional()
      .nullable(),
    deletedBy: z.union([z.string(), z.null()]).optional().nullable(),
    createdAt: z.union([z.date().optional(), z.string().datetime().optional()]),
    updatedAt: z.union([z.date().optional(), z.string().datetime().optional()]),
    createdBy: z.union([z.string(), z.null()]).optional().nullable(),
    updatedBy: z.union([z.string(), z.null()]).optional().nullable(),
    id: z.string().optional(),
    email: z.string(),
    emailVerified: z
      .union([z.union([z.date(), z.string().datetime().optional()]), z.null()])
      .optional()
      .nullable(),
    password: z.union([z.string(), z.null()]).optional().nullable(),
    phoneNumber: z.union([z.string(), z.null()]).optional().nullable(),
    phoneVerified: z
      .union([z.union([z.date(), z.string().datetime().optional()]), z.null()])
      .optional()
      .nullable(),
    mfaEnabled: z.boolean().optional(),
    mfaSecret: z.union([z.string(), z.null()]).optional().nullable(),
    backupCodes: z
      .union([
        z.lazy(() => UserCreatebackupCodesInputObjectSchema),
        z.string().array()
      ])
      .optional(),
    lastLoginAt: z
      .union([z.union([z.date(), z.string().datetime().optional()]), z.null()])
      .optional()
      .nullable(),
    status: z.lazy(() => UserStatusSchema).optional(),
    authenticationMethods: z
      .union([
        z.lazy(() => UserCreateauthenticationMethodsInputObjectSchema),
        z.lazy(() => AuthenticationMethodSchema).array()
      ])
      .optional(),
    failedLoginAttempts: z.number().optional(),
    lockoutUntil: z
      .union([z.union([z.date(), z.string().datetime().optional()]), z.null()])
      .optional()
      .nullable(),
    isPlatformAdmin: z.boolean().optional(),
    requirePasswordChange: z.boolean().optional(),
    passwordLastChanged: z
      .union([z.union([z.date(), z.string().datetime().optional()]), z.null()])
      .optional()
      .nullable(),
    passwordResetAttempts: z.number().optional(),
    name: z.union([z.string(), z.null()]).optional().nullable(),
    image: z.union([z.string(), z.null()]).optional().nullable(),
    profilePictureId: z.union([z.string(), z.null()]).optional().nullable()
  })
  .strict() as SchemaType;
