/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { UserProfileCreateWithoutUserInputObjectSchema } from './UserProfileCreateWithoutUserInput.schema';
import { UserProfileUncheckedCreateWithoutUserInputObjectSchema } from './UserProfileUncheckedCreateWithoutUserInput.schema';
import { UserProfileCreateOrConnectWithoutUserInputObjectSchema } from './UserProfileCreateOrConnectWithoutUserInput.schema';
import { UserProfileWhereUniqueInputObjectSchema } from './UserProfileWhereUniqueInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.UserProfileUncheckedCreateNestedOneWithoutUserInput>;
export const UserProfileUncheckedCreateNestedOneWithoutUserInputObjectSchema: SchemaType =
  z
    .object({
      create: z
        .union([
          z.lazy(() => UserProfileCreateWithoutUserInputObjectSchema),
          z.lazy(() => UserProfileUncheckedCreateWithoutUserInputObjectSchema)
        ])
        .optional(),
      connectOrCreate: z
        .lazy(() => UserProfileCreateOrConnectWithoutUserInputObjectSchema)
        .optional(),
      connect: z.lazy(() => UserProfileWhereUniqueInputObjectSchema).optional()
    })
    .strict() as SchemaType;
