/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { SortOrderSchema } from '../enums/SortOrder.schema';
import { SortOrderInputObjectSchema } from './SortOrderInput.schema';
import { UserProfileOrderByWithRelationInputObjectSchema } from './UserProfileOrderByWithRelationInput.schema';
import { VerificationTokenOrderByRelationAggregateInputObjectSchema } from './VerificationTokenOrderByRelationAggregateInput.schema';
import { AuthSessionOrderByRelationAggregateInputObjectSchema } from './AuthSessionOrderByRelationAggregateInput.schema';
import { WorkspaceOrderByRelationAggregateInputObjectSchema } from './WorkspaceOrderByRelationAggregateInput.schema';
import { ObjectStorageFileOrderByWithRelationInputObjectSchema } from './ObjectStorageFileOrderByWithRelationInput.schema';
import { ResourceMemberOrderByRelationAggregateInputObjectSchema } from './ResourceMemberOrderByRelationAggregateInput.schema';
import { OAuthAccountOrderByRelationAggregateInputObjectSchema } from './OAuthAccountOrderByRelationAggregateInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.UserOrderByWithRelationInput>;
export const UserOrderByWithRelationInputObjectSchema: SchemaType = z
  .object({
    deletedAt: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    deletedBy: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    createdAt: z.lazy(() => SortOrderSchema).optional(),
    updatedAt: z.lazy(() => SortOrderSchema).optional(),
    createdBy: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    updatedBy: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    id: z.lazy(() => SortOrderSchema).optional(),
    email: z.lazy(() => SortOrderSchema).optional(),
    emailVerified: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    password: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    phoneNumber: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    phoneVerified: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    mfaEnabled: z.lazy(() => SortOrderSchema).optional(),
    mfaSecret: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    backupCodes: z.lazy(() => SortOrderSchema).optional(),
    lastLoginAt: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    status: z.lazy(() => SortOrderSchema).optional(),
    authenticationMethods: z.lazy(() => SortOrderSchema).optional(),
    failedLoginAttempts: z.lazy(() => SortOrderSchema).optional(),
    lockoutUntil: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    isPlatformAdmin: z.lazy(() => SortOrderSchema).optional(),
    requirePasswordChange: z.lazy(() => SortOrderSchema).optional(),
    passwordLastChanged: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    passwordResetAttempts: z.lazy(() => SortOrderSchema).optional(),
    name: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    image: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    profilePictureId: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    userProfile: z
      .lazy(() => UserProfileOrderByWithRelationInputObjectSchema)
      .optional(),
    verificationTokens: z
      .lazy(() => VerificationTokenOrderByRelationAggregateInputObjectSchema)
      .optional(),
    sessions: z
      .lazy(() => AuthSessionOrderByRelationAggregateInputObjectSchema)
      .optional(),
    ownedWorkspaces: z
      .lazy(() => WorkspaceOrderByRelationAggregateInputObjectSchema)
      .optional(),
    profilePicture: z
      .lazy(() => ObjectStorageFileOrderByWithRelationInputObjectSchema)
      .optional(),
    memberships: z
      .lazy(() => ResourceMemberOrderByRelationAggregateInputObjectSchema)
      .optional(),
    oauthAccounts: z
      .lazy(() => OAuthAccountOrderByRelationAggregateInputObjectSchema)
      .optional()
  })
  .strict() as SchemaType;
