/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { DateTimeFieldUpdateOperationsInputObjectSchema } from './DateTimeFieldUpdateOperationsInput.schema';
import { NullableStringFieldUpdateOperationsInputObjectSchema } from './NullableStringFieldUpdateOperationsInput.schema';
import { StringFieldUpdateOperationsInputObjectSchema } from './StringFieldUpdateOperationsInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.UserProfileUncheckedUpdateWithoutUserInput>;
export const UserProfileUncheckedUpdateWithoutUserInputObjectSchema: SchemaType =
  z
    .object({
      createdAt: z
        .union([
          z.union([z.date(), z.string().datetime().optional()]),
          z.lazy(() => DateTimeFieldUpdateOperationsInputObjectSchema)
        ])
        .optional(),
      updatedAt: z
        .union([
          z.union([z.date(), z.string().datetime().optional()]),
          z.lazy(() => DateTimeFieldUpdateOperationsInputObjectSchema)
        ])
        .optional(),
      createdBy: z
        .union([
          z.string(),
          z.lazy(() => NullableStringFieldUpdateOperationsInputObjectSchema),
          z.null()
        ])
        .optional()
        .nullable(),
      updatedBy: z
        .union([
          z.string(),
          z.lazy(() => NullableStringFieldUpdateOperationsInputObjectSchema),
          z.null()
        ])
        .optional()
        .nullable(),
      id: z
        .union([
          z.string(),
          z.lazy(() => StringFieldUpdateOperationsInputObjectSchema)
        ])
        .optional(),
      firstName: z
        .union([
          z.string(),
          z.lazy(() => StringFieldUpdateOperationsInputObjectSchema)
        ])
        .optional(),
      lastName: z
        .union([
          z.string(),
          z.lazy(() => NullableStringFieldUpdateOperationsInputObjectSchema),
          z.null()
        ])
        .optional()
        .nullable()
    })
    .strict() as SchemaType;
