/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { UserDefaultArgsObjectSchema } from './UserDefaultArgs.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.UserProfileSelect>;
export const UserProfileSelectObjectSchema: SchemaType = z
  .object({
    createdAt: z.boolean().optional(),
    updatedAt: z.boolean().optional(),
    createdBy: z.boolean().optional(),
    updatedBy: z.boolean().optional(),
    id: z.boolean().optional(),
    firstName: z.boolean().optional(),
    lastName: z.boolean().optional(),
    user: z
      .union([z.boolean(), z.lazy(() => UserDefaultArgsObjectSchema)])
      .optional(),
    userId: z.boolean().optional()
  })
  .strict() as SchemaType;
