/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { UserProfileUpdateWithoutUserInputObjectSchema } from './UserProfileUpdateWithoutUserInput.schema';
import { UserProfileUncheckedUpdateWithoutUserInputObjectSchema } from './UserProfileUncheckedUpdateWithoutUserInput.schema';
import { UserProfileCreateWithoutUserInputObjectSchema } from './UserProfileCreateWithoutUserInput.schema';
import { UserProfileUncheckedCreateWithoutUserInputObjectSchema } from './UserProfileUncheckedCreateWithoutUserInput.schema';
import { UserProfileWhereInputObjectSchema } from './UserProfileWhereInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.UserProfileUpsertWithoutUserInput>;
export const UserProfileUpsertWithoutUserInputObjectSchema: SchemaType = z
  .object({
    update: z.union([
      z.lazy(() => UserProfileUpdateWithoutUserInputObjectSchema),
      z.lazy(() => UserProfileUncheckedUpdateWithoutUserInputObjectSchema)
    ]),
    create: z.union([
      z.lazy(() => UserProfileCreateWithoutUserInputObjectSchema),
      z.lazy(() => UserProfileUncheckedCreateWithoutUserInputObjectSchema)
    ]),
    where: z.lazy(() => UserProfileWhereInputObjectSchema).optional()
  })
  .strict() as SchemaType;
