/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { UserProfileWhereUniqueInputObjectSchema } from './UserProfileWhereUniqueInput.schema';
import { UserProfileCreateWithoutUserInputObjectSchema } from './UserProfileCreateWithoutUserInput.schema';
import { UserProfileUncheckedCreateWithoutUserInputObjectSchema } from './UserProfileUncheckedCreateWithoutUserInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.UserProfileCreateOrConnectWithoutUserInput>;
export const UserProfileCreateOrConnectWithoutUserInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => UserProfileWhereUniqueInputObjectSchema),
      create: z.union([
        z.lazy(() => UserProfileCreateWithoutUserInputObjectSchema),
        z.lazy(() => UserProfileUncheckedCreateWithoutUserInputObjectSchema)
      ])
    })
    .strict() as SchemaType;
