/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { UserCreateWithoutProfilePictureInputObjectSchema } from './UserCreateWithoutProfilePictureInput.schema';
import { UserUncheckedCreateWithoutProfilePictureInputObjectSchema } from './UserUncheckedCreateWithoutProfilePictureInput.schema';
import { UserCreateOrConnectWithoutProfilePictureInputObjectSchema } from './UserCreateOrConnectWithoutProfilePictureInput.schema';
import { UserUpsertWithoutProfilePictureInputObjectSchema } from './UserUpsertWithoutProfilePictureInput.schema';
import { UserWhereInputObjectSchema } from './UserWhereInput.schema';
import { UserWhereUniqueInputObjectSchema } from './UserWhereUniqueInput.schema';
import { UserUpdateToOneWithWhereWithoutProfilePictureInputObjectSchema } from './UserUpdateToOneWithWhereWithoutProfilePictureInput.schema';
import { UserUpdateWithoutProfilePictureInputObjectSchema } from './UserUpdateWithoutProfilePictureInput.schema';
import { UserUncheckedUpdateWithoutProfilePictureInputObjectSchema } from './UserUncheckedUpdateWithoutProfilePictureInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.UserUpdateOneWithoutProfilePictureNestedInput>;
export const UserUpdateOneWithoutProfilePictureNestedInputObjectSchema: SchemaType =
  z
    .object({
      create: z
        .union([
          z.lazy(() => UserCreateWithoutProfilePictureInputObjectSchema),
          z.lazy(
            () => UserUncheckedCreateWithoutProfilePictureInputObjectSchema
          )
        ])
        .optional(),
      connectOrCreate: z
        .lazy(() => UserCreateOrConnectWithoutProfilePictureInputObjectSchema)
        .optional(),
      upsert: z
        .lazy(() => UserUpsertWithoutProfilePictureInputObjectSchema)
        .optional(),
      disconnect: z
        .union([z.boolean(), z.lazy(() => UserWhereInputObjectSchema)])
        .optional(),
      delete: z
        .union([z.boolean(), z.lazy(() => UserWhereInputObjectSchema)])
        .optional(),
      connect: z.lazy(() => UserWhereUniqueInputObjectSchema).optional(),
      update: z
        .union([
          z.lazy(
            () => UserUpdateToOneWithWhereWithoutProfilePictureInputObjectSchema
          ),
          z.lazy(() => UserUpdateWithoutProfilePictureInputObjectSchema),
          z.lazy(
            () => UserUncheckedUpdateWithoutProfilePictureInputObjectSchema
          )
        ])
        .optional()
    })
    .strict() as SchemaType;
