/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { UserCreateWithoutUserProfileInputObjectSchema } from './UserCreateWithoutUserProfileInput.schema';
import { UserUncheckedCreateWithoutUserProfileInputObjectSchema } from './UserUncheckedCreateWithoutUserProfileInput.schema';
import { UserCreateOrConnectWithoutUserProfileInputObjectSchema } from './UserCreateOrConnectWithoutUserProfileInput.schema';
import { UserUpsertWithoutUserProfileInputObjectSchema } from './UserUpsertWithoutUserProfileInput.schema';
import { UserWhereInputObjectSchema } from './UserWhereInput.schema';
import { UserWhereUniqueInputObjectSchema } from './UserWhereUniqueInput.schema';
import { UserUpdateToOneWithWhereWithoutUserProfileInputObjectSchema } from './UserUpdateToOneWithWhereWithoutUserProfileInput.schema';
import { UserUpdateWithoutUserProfileInputObjectSchema } from './UserUpdateWithoutUserProfileInput.schema';
import { UserUncheckedUpdateWithoutUserProfileInputObjectSchema } from './UserUncheckedUpdateWithoutUserProfileInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.UserUpdateOneWithoutUserProfileNestedInput>;
export const UserUpdateOneWithoutUserProfileNestedInputObjectSchema: SchemaType =
  z
    .object({
      create: z
        .union([
          z.lazy(() => UserCreateWithoutUserProfileInputObjectSchema),
          z.lazy(() => UserUncheckedCreateWithoutUserProfileInputObjectSchema)
        ])
        .optional(),
      connectOrCreate: z
        .lazy(() => UserCreateOrConnectWithoutUserProfileInputObjectSchema)
        .optional(),
      upsert: z
        .lazy(() => UserUpsertWithoutUserProfileInputObjectSchema)
        .optional(),
      disconnect: z
        .union([z.boolean(), z.lazy(() => UserWhereInputObjectSchema)])
        .optional(),
      delete: z
        .union([z.boolean(), z.lazy(() => UserWhereInputObjectSchema)])
        .optional(),
      connect: z.lazy(() => UserWhereUniqueInputObjectSchema).optional(),
      update: z
        .union([
          z.lazy(
            () => UserUpdateToOneWithWhereWithoutUserProfileInputObjectSchema
          ),
          z.lazy(() => UserUpdateWithoutUserProfileInputObjectSchema),
          z.lazy(() => UserUncheckedUpdateWithoutUserProfileInputObjectSchema)
        ])
        .optional()
    })
    .strict() as SchemaType;
