/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { UserProfileDefaultArgsObjectSchema } from './UserProfileDefaultArgs.schema';
import { VerificationTokenInputSchema } from '../input/VerificationTokenInput.schema';
import { AuthSessionInputSchema } from '../input/AuthSessionInput.schema';
import { WorkspaceInputSchema } from '../input/WorkspaceInput.schema';
import { ObjectStorageFileDefaultArgsObjectSchema } from './ObjectStorageFileDefaultArgs.schema';
import { ResourceMemberInputSchema } from '../input/ResourceMemberInput.schema';
import { OAuthAccountInputSchema } from '../input/OAuthAccountInput.schema';
import { UserCountOutputTypeDefaultArgsObjectSchema } from './UserCountOutputTypeDefaultArgs.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.UserInclude>;
export const UserIncludeObjectSchema: SchemaType = z
  .object({
    userProfile: z
      .union([z.boolean(), z.lazy(() => UserProfileDefaultArgsObjectSchema)])
      .optional(),
    verificationTokens: z
      .union([z.boolean(), z.lazy(() => VerificationTokenInputSchema.findMany)])
      .optional(),
    sessions: z
      .union([z.boolean(), z.lazy(() => AuthSessionInputSchema.findMany)])
      .optional(),
    ownedWorkspaces: z
      .union([z.boolean(), z.lazy(() => WorkspaceInputSchema.findMany)])
      .optional(),
    profilePicture: z
      .union([
        z.boolean(),
        z.lazy(() => ObjectStorageFileDefaultArgsObjectSchema)
      ])
      .optional(),
    memberships: z
      .union([z.boolean(), z.lazy(() => ResourceMemberInputSchema.findMany)])
      .optional(),
    oauthAccounts: z
      .union([z.boolean(), z.lazy(() => OAuthAccountInputSchema.findMany)])
      .optional(),
    _count: z
      .union([
        z.boolean(),
        z.lazy(() => UserCountOutputTypeDefaultArgsObjectSchema)
      ])
      .optional()
  })
  .strict() as SchemaType;
