/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { UserCreateWithoutOwnedWorkspacesInputObjectSchema } from './UserCreateWithoutOwnedWorkspacesInput.schema';
import { UserUncheckedCreateWithoutOwnedWorkspacesInputObjectSchema } from './UserUncheckedCreateWithoutOwnedWorkspacesInput.schema';
import { UserCreateOrConnectWithoutOwnedWorkspacesInputObjectSchema } from './UserCreateOrConnectWithoutOwnedWorkspacesInput.schema';
import { UserUpsertWithoutOwnedWorkspacesInputObjectSchema } from './UserUpsertWithoutOwnedWorkspacesInput.schema';
import { UserWhereInputObjectSchema } from './UserWhereInput.schema';
import { UserWhereUniqueInputObjectSchema } from './UserWhereUniqueInput.schema';
import { UserUpdateToOneWithWhereWithoutOwnedWorkspacesInputObjectSchema } from './UserUpdateToOneWithWhereWithoutOwnedWorkspacesInput.schema';
import { UserUpdateWithoutOwnedWorkspacesInputObjectSchema } from './UserUpdateWithoutOwnedWorkspacesInput.schema';
import { UserUncheckedUpdateWithoutOwnedWorkspacesInputObjectSchema } from './UserUncheckedUpdateWithoutOwnedWorkspacesInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.UserUpdateOneWithoutOwnedWorkspacesNestedInput>;
export const UserUpdateOneWithoutOwnedWorkspacesNestedInputObjectSchema: SchemaType =
  z
    .object({
      create: z
        .union([
          z.lazy(() => UserCreateWithoutOwnedWorkspacesInputObjectSchema),
          z.lazy(
            () => UserUncheckedCreateWithoutOwnedWorkspacesInputObjectSchema
          )
        ])
        .optional(),
      connectOrCreate: z
        .lazy(() => UserCreateOrConnectWithoutOwnedWorkspacesInputObjectSchema)
        .optional(),
      upsert: z
        .lazy(() => UserUpsertWithoutOwnedWorkspacesInputObjectSchema)
        .optional(),
      disconnect: z
        .union([z.boolean(), z.lazy(() => UserWhereInputObjectSchema)])
        .optional(),
      delete: z
        .union([z.boolean(), z.lazy(() => UserWhereInputObjectSchema)])
        .optional(),
      connect: z.lazy(() => UserWhereUniqueInputObjectSchema).optional(),
      update: z
        .union([
          z.lazy(
            () =>
              UserUpdateToOneWithWhereWithoutOwnedWorkspacesInputObjectSchema
          ),
          z.lazy(() => UserUpdateWithoutOwnedWorkspacesInputObjectSchema),
          z.lazy(
            () => UserUncheckedUpdateWithoutOwnedWorkspacesInputObjectSchema
          )
        ])
        .optional()
    })
    .strict() as SchemaType;
