/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { UserProfileCreateWithoutUserInputObjectSchema } from './UserProfileCreateWithoutUserInput.schema';
import { UserProfileUncheckedCreateWithoutUserInputObjectSchema } from './UserProfileUncheckedCreateWithoutUserInput.schema';
import { UserProfileCreateOrConnectWithoutUserInputObjectSchema } from './UserProfileCreateOrConnectWithoutUserInput.schema';
import { UserProfileUpsertWithoutUserInputObjectSchema } from './UserProfileUpsertWithoutUserInput.schema';
import { UserProfileWhereInputObjectSchema } from './UserProfileWhereInput.schema';
import { UserProfileWhereUniqueInputObjectSchema } from './UserProfileWhereUniqueInput.schema';
import { UserProfileUpdateToOneWithWhereWithoutUserInputObjectSchema } from './UserProfileUpdateToOneWithWhereWithoutUserInput.schema';
import { UserProfileUpdateWithoutUserInputObjectSchema } from './UserProfileUpdateWithoutUserInput.schema';
import { UserProfileUncheckedUpdateWithoutUserInputObjectSchema } from './UserProfileUncheckedUpdateWithoutUserInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.UserProfileUpdateOneWithoutUserNestedInput>;
export const UserProfileUpdateOneWithoutUserNestedInputObjectSchema: SchemaType =
  z
    .object({
      create: z
        .union([
          z.lazy(() => UserProfileCreateWithoutUserInputObjectSchema),
          z.lazy(() => UserProfileUncheckedCreateWithoutUserInputObjectSchema)
        ])
        .optional(),
      connectOrCreate: z
        .lazy(() => UserProfileCreateOrConnectWithoutUserInputObjectSchema)
        .optional(),
      upsert: z
        .lazy(() => UserProfileUpsertWithoutUserInputObjectSchema)
        .optional(),
      disconnect: z
        .union([z.boolean(), z.lazy(() => UserProfileWhereInputObjectSchema)])
        .optional(),
      delete: z
        .union([z.boolean(), z.lazy(() => UserProfileWhereInputObjectSchema)])
        .optional(),
      connect: z.lazy(() => UserProfileWhereUniqueInputObjectSchema).optional(),
      update: z
        .union([
          z.lazy(
            () => UserProfileUpdateToOneWithWhereWithoutUserInputObjectSchema
          ),
          z.lazy(() => UserProfileUpdateWithoutUserInputObjectSchema),
          z.lazy(() => UserProfileUncheckedUpdateWithoutUserInputObjectSchema)
        ])
        .optional()
    })
    .strict() as SchemaType;
