/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { UserWhereUniqueInputObjectSchema } from './UserWhereUniqueInput.schema';
import { UserCreateWithoutVerificationTokensInputObjectSchema } from './UserCreateWithoutVerificationTokensInput.schema';
import { UserUncheckedCreateWithoutVerificationTokensInputObjectSchema } from './UserUncheckedCreateWithoutVerificationTokensInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.UserCreateOrConnectWithoutVerificationTokensInput>;
export const UserCreateOrConnectWithoutVerificationTokensInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => UserWhereUniqueInputObjectSchema),
      create: z.union([
        z.lazy(() => UserCreateWithoutVerificationTokensInputObjectSchema),
        z.lazy(
          () => UserUncheckedCreateWithoutVerificationTokensInputObjectSchema
        )
      ])
    })
    .strict() as SchemaType;
