/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { UserWhereInputObjectSchema } from './UserWhereInput.schema';
import { UserUpdateWithoutUserProfileInputObjectSchema } from './UserUpdateWithoutUserProfileInput.schema';
import { UserUncheckedUpdateWithoutUserProfileInputObjectSchema } from './UserUncheckedUpdateWithoutUserProfileInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.UserUpdateToOneWithWhereWithoutUserProfileInput>;
export const UserUpdateToOneWithWhereWithoutUserProfileInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => UserWhereInputObjectSchema).optional(),
      data: z.union([
        z.lazy(() => UserUpdateWithoutUserProfileInputObjectSchema),
        z.lazy(() => UserUncheckedUpdateWithoutUserProfileInputObjectSchema)
      ])
    })
    .strict() as SchemaType;
