/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { UserCreateWithoutOauthAccountsInputObjectSchema } from './UserCreateWithoutOauthAccountsInput.schema';
import { UserUncheckedCreateWithoutOauthAccountsInputObjectSchema } from './UserUncheckedCreateWithoutOauthAccountsInput.schema';
import { UserCreateOrConnectWithoutOauthAccountsInputObjectSchema } from './UserCreateOrConnectWithoutOauthAccountsInput.schema';
import { UserWhereUniqueInputObjectSchema } from './UserWhereUniqueInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.UserCreateNestedOneWithoutOauthAccountsInput>;
export const UserCreateNestedOneWithoutOauthAccountsInputObjectSchema: SchemaType =
  z
    .object({
      create: z
        .union([
          z.lazy(() => UserCreateWithoutOauthAccountsInputObjectSchema),
          z.lazy(() => UserUncheckedCreateWithoutOauthAccountsInputObjectSchema)
        ])
        .optional(),
      connectOrCreate: z
        .lazy(() => UserCreateOrConnectWithoutOauthAccountsInputObjectSchema)
        .optional(),
      connect: z.lazy(() => UserWhereUniqueInputObjectSchema).optional()
    })
    .strict() as SchemaType;
