/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { DateTimeWithAggregatesFilterObjectSchema } from './DateTimeWithAggregatesFilter.schema';
import { StringNullableWithAggregatesFilterObjectSchema } from './StringNullableWithAggregatesFilter.schema';
import { StringWithAggregatesFilterObjectSchema } from './StringWithAggregatesFilter.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.UserProfileScalarWhereWithAggregatesInput>;
export const UserProfileScalarWhereWithAggregatesInputObjectSchema: SchemaType =
  z
    .object({
      AND: z
        .union([
          z.lazy(() => UserProfileScalarWhereWithAggregatesInputObjectSchema),
          z
            .lazy(() => UserProfileScalarWhereWithAggregatesInputObjectSchema)
            .array()
        ])
        .optional(),
      OR: z
        .lazy(() => UserProfileScalarWhereWithAggregatesInputObjectSchema)
        .array()
        .optional(),
      NOT: z
        .union([
          z.lazy(() => UserProfileScalarWhereWithAggregatesInputObjectSchema),
          z
            .lazy(() => UserProfileScalarWhereWithAggregatesInputObjectSchema)
            .array()
        ])
        .optional(),
      createdAt: z
        .union([
          z.lazy(() => DateTimeWithAggregatesFilterObjectSchema),
          z.union([z.date(), z.string().datetime().optional()])
        ])
        .optional(),
      updatedAt: z
        .union([
          z.lazy(() => DateTimeWithAggregatesFilterObjectSchema),
          z.union([z.date(), z.string().datetime().optional()])
        ])
        .optional(),
      createdBy: z
        .union([
          z.lazy(() => StringNullableWithAggregatesFilterObjectSchema),
          z.string(),
          z.null()
        ])
        .optional()
        .nullable(),
      updatedBy: z
        .union([
          z.lazy(() => StringNullableWithAggregatesFilterObjectSchema),
          z.string(),
          z.null()
        ])
        .optional()
        .nullable(),
      id: z
        .union([
          z.lazy(() => StringWithAggregatesFilterObjectSchema),
          z.string()
        ])
        .optional(),
      firstName: z
        .union([
          z.lazy(() => StringWithAggregatesFilterObjectSchema),
          z.string()
        ])
        .optional(),
      lastName: z
        .union([
          z.lazy(() => StringNullableWithAggregatesFilterObjectSchema),
          z.string(),
          z.null()
        ])
        .optional()
        .nullable(),
      userId: z
        .union([
          z.lazy(() => StringNullableWithAggregatesFilterObjectSchema),
          z.string(),
          z.null()
        ])
        .optional()
        .nullable()
    })
    .strict() as SchemaType;
