/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { UserProfileSelectObjectSchema } from './UserProfileSelect.schema';
import { UserProfileIncludeObjectSchema } from './UserProfileInclude.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.UserProfileDefaultArgs>;
export const UserProfileDefaultArgsObjectSchema: SchemaType = z
  .object({
    select: z.lazy(() => UserProfileSelectObjectSchema).optional(),
    include: z.lazy(() => UserProfileIncludeObjectSchema).optional()
  })
  .strict() as SchemaType;
