/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { UserUpdateWithoutUserProfileInputObjectSchema } from './UserUpdateWithoutUserProfileInput.schema';
import { UserUncheckedUpdateWithoutUserProfileInputObjectSchema } from './UserUncheckedUpdateWithoutUserProfileInput.schema';
import { UserCreateWithoutUserProfileInputObjectSchema } from './UserCreateWithoutUserProfileInput.schema';
import { UserUncheckedCreateWithoutUserProfileInputObjectSchema } from './UserUncheckedCreateWithoutUserProfileInput.schema';
import { UserWhereInputObjectSchema } from './UserWhereInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.UserUpsertWithoutUserProfileInput>;
export const UserUpsertWithoutUserProfileInputObjectSchema: SchemaType = z
  .object({
    update: z.union([
      z.lazy(() => UserUpdateWithoutUserProfileInputObjectSchema),
      z.lazy(() => UserUncheckedUpdateWithoutUserProfileInputObjectSchema)
    ]),
    create: z.union([
      z.lazy(() => UserCreateWithoutUserProfileInputObjectSchema),
      z.lazy(() => UserUncheckedCreateWithoutUserProfileInputObjectSchema)
    ]),
    where: z.lazy(() => UserWhereInputObjectSchema).optional()
  })
  .strict() as SchemaType;
