/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { VerificationTokenCreateWithoutUserInputObjectSchema } from './VerificationTokenCreateWithoutUserInput.schema';
import { VerificationTokenUncheckedCreateWithoutUserInputObjectSchema } from './VerificationTokenUncheckedCreateWithoutUserInput.schema';
import { VerificationTokenCreateOrConnectWithoutUserInputObjectSchema } from './VerificationTokenCreateOrConnectWithoutUserInput.schema';
import { VerificationTokenCreateManyUserInputEnvelopeObjectSchema } from './VerificationTokenCreateManyUserInputEnvelope.schema';
import { VerificationTokenWhereUniqueInputObjectSchema } from './VerificationTokenWhereUniqueInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.VerificationTokenUncheckedCreateNestedManyWithoutUserInput>;
export const VerificationTokenUncheckedCreateNestedManyWithoutUserInputObjectSchema: SchemaType =
  z
    .object({
      create: z
        .union([
          z.lazy(() => VerificationTokenCreateWithoutUserInputObjectSchema),
          z
            .lazy(() => VerificationTokenCreateWithoutUserInputObjectSchema)
            .array(),
          z.lazy(
            () => VerificationTokenUncheckedCreateWithoutUserInputObjectSchema
          ),
          z
            .lazy(
              () => VerificationTokenUncheckedCreateWithoutUserInputObjectSchema
            )
            .array()
        ])
        .optional(),
      connectOrCreate: z
        .union([
          z.lazy(
            () => VerificationTokenCreateOrConnectWithoutUserInputObjectSchema
          ),
          z
            .lazy(
              () => VerificationTokenCreateOrConnectWithoutUserInputObjectSchema
            )
            .array()
        ])
        .optional(),
      createMany: z
        .lazy(() => VerificationTokenCreateManyUserInputEnvelopeObjectSchema)
        .optional(),
      connect: z
        .union([
          z.lazy(() => VerificationTokenWhereUniqueInputObjectSchema),
          z.lazy(() => VerificationTokenWhereUniqueInputObjectSchema).array()
        ])
        .optional()
    })
    .strict() as SchemaType;
