/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { VerificationTokenTypeSchema } from '../enums/VerificationTokenType.schema';
import { UserCreateNestedOneWithoutVerificationTokensInputObjectSchema } from './UserCreateNestedOneWithoutVerificationTokensInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.VerificationTokenCreateInput>;
export const VerificationTokenCreateInputObjectSchema: SchemaType = z
  .object({
    createdAt: z.union([z.date().optional(), z.string().datetime().optional()]),
    updatedAt: z.union([z.date().optional(), z.string().datetime().optional()]),
    createdBy: z.union([z.string(), z.null()]).optional().nullable(),
    updatedBy: z.union([z.string(), z.null()]).optional().nullable(),
    id: z.string().optional(),
    identifier: z.string(),
    token: z.string(),
    type: z.lazy(() => VerificationTokenTypeSchema),
    expiresAt: z.union([z.date(), z.string().datetime()]),
    usedAt: z
      .union([z.union([z.date(), z.string().datetime().optional()]), z.null()])
      .optional()
      .nullable(),
    phoneNumber: z.union([z.string(), z.null()]).optional().nullable(),
    code: z.union([z.string(), z.null()]).optional().nullable(),
    attempts: z.number().optional(),
    user: z.lazy(
      () => UserCreateNestedOneWithoutVerificationTokensInputObjectSchema
    )
  })
  .strict() as SchemaType;
