/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { DateTimeFilterObjectSchema } from './DateTimeFilter.schema';
import { StringNullableFilterObjectSchema } from './StringNullableFilter.schema';
import { StringFilterObjectSchema } from './StringFilter.schema';
import { EnumVerificationTokenTypeFilterObjectSchema } from './EnumVerificationTokenTypeFilter.schema';
import { VerificationTokenTypeSchema } from '../enums/VerificationTokenType.schema';
import { DateTimeNullableFilterObjectSchema } from './DateTimeNullableFilter.schema';
import { IntFilterObjectSchema } from './IntFilter.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.VerificationTokenScalarWhereInput>;
export const VerificationTokenScalarWhereInputObjectSchema: SchemaType = z
  .object({
    AND: z
      .union([
        z.lazy(() => VerificationTokenScalarWhereInputObjectSchema),
        z.lazy(() => VerificationTokenScalarWhereInputObjectSchema).array()
      ])
      .optional(),
    OR: z
      .lazy(() => VerificationTokenScalarWhereInputObjectSchema)
      .array()
      .optional(),
    NOT: z
      .union([
        z.lazy(() => VerificationTokenScalarWhereInputObjectSchema),
        z.lazy(() => VerificationTokenScalarWhereInputObjectSchema).array()
      ])
      .optional(),
    createdAt: z
      .union([
        z.lazy(() => DateTimeFilterObjectSchema),
        z.union([z.date(), z.string().datetime().optional()])
      ])
      .optional(),
    updatedAt: z
      .union([
        z.lazy(() => DateTimeFilterObjectSchema),
        z.union([z.date(), z.string().datetime().optional()])
      ])
      .optional(),
    createdBy: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    updatedBy: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    id: z
      .union([z.lazy(() => StringFilterObjectSchema), z.string()])
      .optional(),
    identifier: z
      .union([z.lazy(() => StringFilterObjectSchema), z.string()])
      .optional(),
    token: z
      .union([z.lazy(() => StringFilterObjectSchema), z.string()])
      .optional(),
    type: z
      .union([
        z.lazy(() => EnumVerificationTokenTypeFilterObjectSchema),
        z.lazy(() => VerificationTokenTypeSchema)
      ])
      .optional(),
    expiresAt: z
      .union([
        z.lazy(() => DateTimeFilterObjectSchema),
        z.union([z.date(), z.string().datetime().optional()])
      ])
      .optional(),
    usedAt: z
      .union([
        z.lazy(() => DateTimeNullableFilterObjectSchema),
        z.union([z.date(), z.string().datetime().optional()]),
        z.null()
      ])
      .optional()
      .nullable(),
    phoneNumber: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    code: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    attempts: z
      .union([z.lazy(() => IntFilterObjectSchema), z.number()])
      .optional(),
    userId: z
      .union([z.lazy(() => StringFilterObjectSchema), z.string()])
      .optional()
  })
  .strict() as SchemaType;
