/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { VerificationTokenWhereUniqueInputObjectSchema } from './VerificationTokenWhereUniqueInput.schema';
import { VerificationTokenUpdateWithoutUserInputObjectSchema } from './VerificationTokenUpdateWithoutUserInput.schema';
import { VerificationTokenUncheckedUpdateWithoutUserInputObjectSchema } from './VerificationTokenUncheckedUpdateWithoutUserInput.schema';
import { VerificationTokenCreateWithoutUserInputObjectSchema } from './VerificationTokenCreateWithoutUserInput.schema';
import { VerificationTokenUncheckedCreateWithoutUserInputObjectSchema } from './VerificationTokenUncheckedCreateWithoutUserInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.VerificationTokenUpsertWithWhereUniqueWithoutUserInput>;
export const VerificationTokenUpsertWithWhereUniqueWithoutUserInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => VerificationTokenWhereUniqueInputObjectSchema),
      update: z.union([
        z.lazy(() => VerificationTokenUpdateWithoutUserInputObjectSchema),
        z.lazy(
          () => VerificationTokenUncheckedUpdateWithoutUserInputObjectSchema
        )
      ]),
      create: z.union([
        z.lazy(() => VerificationTokenCreateWithoutUserInputObjectSchema),
        z.lazy(
          () => VerificationTokenUncheckedCreateWithoutUserInputObjectSchema
        )
      ])
    })
    .strict() as SchemaType;
