/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.VerificationTokenMaxAggregateInputType>;
export const VerificationTokenMaxAggregateInputObjectSchema: SchemaType = z
  .object({
    createdAt: z.literal(true).optional(),
    updatedAt: z.literal(true).optional(),
    createdBy: z.literal(true).optional(),
    updatedBy: z.literal(true).optional(),
    id: z.literal(true).optional(),
    identifier: z.literal(true).optional(),
    token: z.literal(true).optional(),
    type: z.literal(true).optional(),
    expiresAt: z.literal(true).optional(),
    usedAt: z.literal(true).optional(),
    phoneNumber: z.literal(true).optional(),
    code: z.literal(true).optional(),
    attempts: z.literal(true).optional(),
    userId: z.literal(true).optional()
  })
  .strict() as SchemaType;
