/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { VerificationTokenSelectObjectSchema } from './VerificationTokenSelect.schema';
import { VerificationTokenIncludeObjectSchema } from './VerificationTokenInclude.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.VerificationTokenDefaultArgs>;
export const VerificationTokenDefaultArgsObjectSchema: SchemaType = z
  .object({
    select: z.lazy(() => VerificationTokenSelectObjectSchema).optional(),
    include: z.lazy(() => VerificationTokenIncludeObjectSchema).optional()
  })
  .strict() as SchemaType;
