/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { VerificationTokenWhereInputObjectSchema } from './VerificationTokenWhereInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.VerificationTokenListRelationFilter>;
export const VerificationTokenListRelationFilterObjectSchema: SchemaType = z
  .object({
    every: z.lazy(() => VerificationTokenWhereInputObjectSchema).optional(),
    some: z.lazy(() => VerificationTokenWhereInputObjectSchema).optional(),
    none: z.lazy(() => VerificationTokenWhereInputObjectSchema).optional()
  })
  .strict() as SchemaType;
