/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { UserDefaultArgsObjectSchema } from './UserDefaultArgs.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.VerificationTokenInclude>;
export const VerificationTokenIncludeObjectSchema: SchemaType = z
  .object({
    user: z
      .union([z.boolean(), z.lazy(() => UserDefaultArgsObjectSchema)])
      .optional()
  })
  .strict() as SchemaType;
