/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { VerificationTokenCreateWithoutUserInputObjectSchema } from './VerificationTokenCreateWithoutUserInput.schema';
import { VerificationTokenUncheckedCreateWithoutUserInputObjectSchema } from './VerificationTokenUncheckedCreateWithoutUserInput.schema';
import { VerificationTokenCreateOrConnectWithoutUserInputObjectSchema } from './VerificationTokenCreateOrConnectWithoutUserInput.schema';
import { VerificationTokenUpsertWithWhereUniqueWithoutUserInputObjectSchema } from './VerificationTokenUpsertWithWhereUniqueWithoutUserInput.schema';
import { VerificationTokenCreateManyUserInputEnvelopeObjectSchema } from './VerificationTokenCreateManyUserInputEnvelope.schema';
import { VerificationTokenWhereUniqueInputObjectSchema } from './VerificationTokenWhereUniqueInput.schema';
import { VerificationTokenUpdateWithWhereUniqueWithoutUserInputObjectSchema } from './VerificationTokenUpdateWithWhereUniqueWithoutUserInput.schema';
import { VerificationTokenUpdateManyWithWhereWithoutUserInputObjectSchema } from './VerificationTokenUpdateManyWithWhereWithoutUserInput.schema';
import { VerificationTokenScalarWhereInputObjectSchema } from './VerificationTokenScalarWhereInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.VerificationTokenUpdateManyWithoutUserNestedInput>;
export const VerificationTokenUpdateManyWithoutUserNestedInputObjectSchema: SchemaType =
  z
    .object({
      create: z
        .union([
          z.lazy(() => VerificationTokenCreateWithoutUserInputObjectSchema),
          z
            .lazy(() => VerificationTokenCreateWithoutUserInputObjectSchema)
            .array(),
          z.lazy(
            () => VerificationTokenUncheckedCreateWithoutUserInputObjectSchema
          ),
          z
            .lazy(
              () => VerificationTokenUncheckedCreateWithoutUserInputObjectSchema
            )
            .array()
        ])
        .optional(),
      connectOrCreate: z
        .union([
          z.lazy(
            () => VerificationTokenCreateOrConnectWithoutUserInputObjectSchema
          ),
          z
            .lazy(
              () => VerificationTokenCreateOrConnectWithoutUserInputObjectSchema
            )
            .array()
        ])
        .optional(),
      upsert: z
        .union([
          z.lazy(
            () =>
              VerificationTokenUpsertWithWhereUniqueWithoutUserInputObjectSchema
          ),
          z
            .lazy(
              () =>
                VerificationTokenUpsertWithWhereUniqueWithoutUserInputObjectSchema
            )
            .array()
        ])
        .optional(),
      createMany: z
        .lazy(() => VerificationTokenCreateManyUserInputEnvelopeObjectSchema)
        .optional(),
      set: z
        .union([
          z.lazy(() => VerificationTokenWhereUniqueInputObjectSchema),
          z.lazy(() => VerificationTokenWhereUniqueInputObjectSchema).array()
        ])
        .optional(),
      disconnect: z
        .union([
          z.lazy(() => VerificationTokenWhereUniqueInputObjectSchema),
          z.lazy(() => VerificationTokenWhereUniqueInputObjectSchema).array()
        ])
        .optional(),
      delete: z
        .union([
          z.lazy(() => VerificationTokenWhereUniqueInputObjectSchema),
          z.lazy(() => VerificationTokenWhereUniqueInputObjectSchema).array()
        ])
        .optional(),
      connect: z
        .union([
          z.lazy(() => VerificationTokenWhereUniqueInputObjectSchema),
          z.lazy(() => VerificationTokenWhereUniqueInputObjectSchema).array()
        ])
        .optional(),
      update: z
        .union([
          z.lazy(
            () =>
              VerificationTokenUpdateWithWhereUniqueWithoutUserInputObjectSchema
          ),
          z
            .lazy(
              () =>
                VerificationTokenUpdateWithWhereUniqueWithoutUserInputObjectSchema
            )
            .array()
        ])
        .optional(),
      updateMany: z
        .union([
          z.lazy(
            () =>
              VerificationTokenUpdateManyWithWhereWithoutUserInputObjectSchema
          ),
          z
            .lazy(
              () =>
                VerificationTokenUpdateManyWithWhereWithoutUserInputObjectSchema
            )
            .array()
        ])
        .optional(),
      deleteMany: z
        .union([
          z.lazy(() => VerificationTokenScalarWhereInputObjectSchema),
          z.lazy(() => VerificationTokenScalarWhereInputObjectSchema).array()
        ])
        .optional()
    })
    .strict() as SchemaType;
