/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { UserSettingsSchema } from '../models/UserSettings.schema';

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { WorkspaceCreateWithoutMembersInputObjectSchema } from './WorkspaceCreateWithoutMembersInput.schema';
import { WorkspaceUncheckedCreateWithoutMembersInputObjectSchema } from './WorkspaceUncheckedCreateWithoutMembersInput.schema';
import { WorkspaceCreateOrConnectWithoutMembersInputObjectSchema } from './WorkspaceCreateOrConnectWithoutMembersInput.schema';
import { WorkspaceWhereUniqueInputObjectSchema } from './WorkspaceWhereUniqueInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.WorkspaceCreateNestedOneWithoutMembersInput>;
export const WorkspaceCreateNestedOneWithoutMembersInputObjectSchema: SchemaType =
  z
    .object({
      create: z
        .union([
          z.lazy(() => WorkspaceCreateWithoutMembersInputObjectSchema),
          z.lazy(() => WorkspaceUncheckedCreateWithoutMembersInputObjectSchema)
        ])
        .optional(),
      connectOrCreate: z
        .lazy(() => WorkspaceCreateOrConnectWithoutMembersInputObjectSchema)
        .optional(),
      connect: z.lazy(() => WorkspaceWhereUniqueInputObjectSchema).optional()
    })
    .strict() as SchemaType;
