/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { WorkspaceSelectObjectSchema } from './WorkspaceSelect.schema';
import { WorkspaceIncludeObjectSchema } from './WorkspaceInclude.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.WorkspaceDefaultArgs>;
export const WorkspaceDefaultArgsObjectSchema: SchemaType = z
  .object({
    select: z.lazy(() => WorkspaceSelectObjectSchema).optional(),
    include: z.lazy(() => WorkspaceIncludeObjectSchema).optional()
  })
  .strict() as SchemaType;
