/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { UserSettingsSchema } from '../models/UserSettings.schema';

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { WorkspaceCreateWithoutMembersInputObjectSchema } from './WorkspaceCreateWithoutMembersInput.schema';
import { WorkspaceUncheckedCreateWithoutMembersInputObjectSchema } from './WorkspaceUncheckedCreateWithoutMembersInput.schema';
import { WorkspaceCreateOrConnectWithoutMembersInputObjectSchema } from './WorkspaceCreateOrConnectWithoutMembersInput.schema';
import { WorkspaceUpsertWithoutMembersInputObjectSchema } from './WorkspaceUpsertWithoutMembersInput.schema';
import { WorkspaceWhereInputObjectSchema } from './WorkspaceWhereInput.schema';
import { WorkspaceWhereUniqueInputObjectSchema } from './WorkspaceWhereUniqueInput.schema';
import { WorkspaceUpdateToOneWithWhereWithoutMembersInputObjectSchema } from './WorkspaceUpdateToOneWithWhereWithoutMembersInput.schema';
import { WorkspaceUpdateWithoutMembersInputObjectSchema } from './WorkspaceUpdateWithoutMembersInput.schema';
import { WorkspaceUncheckedUpdateWithoutMembersInputObjectSchema } from './WorkspaceUncheckedUpdateWithoutMembersInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.WorkspaceUpdateOneWithoutMembersNestedInput>;
export const WorkspaceUpdateOneWithoutMembersNestedInputObjectSchema: SchemaType =
  z
    .object({
      create: z
        .union([
          z.lazy(() => WorkspaceCreateWithoutMembersInputObjectSchema),
          z.lazy(() => WorkspaceUncheckedCreateWithoutMembersInputObjectSchema)
        ])
        .optional(),
      connectOrCreate: z
        .lazy(() => WorkspaceCreateOrConnectWithoutMembersInputObjectSchema)
        .optional(),
      upsert: z
        .lazy(() => WorkspaceUpsertWithoutMembersInputObjectSchema)
        .optional(),
      disconnect: z
        .union([z.boolean(), z.lazy(() => WorkspaceWhereInputObjectSchema)])
        .optional(),
      delete: z
        .union([z.boolean(), z.lazy(() => WorkspaceWhereInputObjectSchema)])
        .optional(),
      connect: z.lazy(() => WorkspaceWhereUniqueInputObjectSchema).optional(),
      update: z
        .union([
          z.lazy(
            () => WorkspaceUpdateToOneWithWhereWithoutMembersInputObjectSchema
          ),
          z.lazy(() => WorkspaceUpdateWithoutMembersInputObjectSchema),
          z.lazy(() => WorkspaceUncheckedUpdateWithoutMembersInputObjectSchema)
        ])
        .optional()
    })
    .strict() as SchemaType;
