/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { UserSettingsSchema } from '../models/UserSettings.schema';

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { WorkspaceCreateWithoutOwnerInputObjectSchema } from './WorkspaceCreateWithoutOwnerInput.schema';
import { WorkspaceUncheckedCreateWithoutOwnerInputObjectSchema } from './WorkspaceUncheckedCreateWithoutOwnerInput.schema';
import { WorkspaceCreateOrConnectWithoutOwnerInputObjectSchema } from './WorkspaceCreateOrConnectWithoutOwnerInput.schema';
import { WorkspaceCreateManyOwnerInputEnvelopeObjectSchema } from './WorkspaceCreateManyOwnerInputEnvelope.schema';
import { WorkspaceWhereUniqueInputObjectSchema } from './WorkspaceWhereUniqueInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.WorkspaceCreateNestedManyWithoutOwnerInput>;
export const WorkspaceCreateNestedManyWithoutOwnerInputObjectSchema: SchemaType =
  z
    .object({
      create: z
        .union([
          z.lazy(() => WorkspaceCreateWithoutOwnerInputObjectSchema),
          z.lazy(() => WorkspaceCreateWithoutOwnerInputObjectSchema).array(),
          z.lazy(() => WorkspaceUncheckedCreateWithoutOwnerInputObjectSchema),
          z
            .lazy(() => WorkspaceUncheckedCreateWithoutOwnerInputObjectSchema)
            .array()
        ])
        .optional(),
      connectOrCreate: z
        .union([
          z.lazy(() => WorkspaceCreateOrConnectWithoutOwnerInputObjectSchema),
          z
            .lazy(() => WorkspaceCreateOrConnectWithoutOwnerInputObjectSchema)
            .array()
        ])
        .optional(),
      createMany: z
        .lazy(() => WorkspaceCreateManyOwnerInputEnvelopeObjectSchema)
        .optional(),
      connect: z
        .union([
          z.lazy(() => WorkspaceWhereUniqueInputObjectSchema),
          z.lazy(() => WorkspaceWhereUniqueInputObjectSchema).array()
        ])
        .optional()
    })
    .strict() as SchemaType;
