/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { UserSettingsSchema } from '../models/UserSettings.schema';

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { WorkspaceWhereUniqueInputObjectSchema } from './WorkspaceWhereUniqueInput.schema';
import { WorkspaceUpdateWithoutOwnerInputObjectSchema } from './WorkspaceUpdateWithoutOwnerInput.schema';
import { WorkspaceUncheckedUpdateWithoutOwnerInputObjectSchema } from './WorkspaceUncheckedUpdateWithoutOwnerInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.WorkspaceUpdateWithWhereUniqueWithoutOwnerInput>;
export const WorkspaceUpdateWithWhereUniqueWithoutOwnerInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => WorkspaceWhereUniqueInputObjectSchema),
      data: z.union([
        z.lazy(() => WorkspaceUpdateWithoutOwnerInputObjectSchema),
        z.lazy(() => WorkspaceUncheckedUpdateWithoutOwnerInputObjectSchema)
      ])
    })
    .strict() as SchemaType;
