/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { UserSettingsSchema } from '../models/UserSettings.schema';

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { WorkspaceScalarWhereInputObjectSchema } from './WorkspaceScalarWhereInput.schema';
import { WorkspaceUpdateManyMutationInputObjectSchema } from './WorkspaceUpdateManyMutationInput.schema';
import { WorkspaceUncheckedUpdateManyWithoutOwnerInputObjectSchema } from './WorkspaceUncheckedUpdateManyWithoutOwnerInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.WorkspaceUpdateManyWithWhereWithoutOwnerInput>;
export const WorkspaceUpdateManyWithWhereWithoutOwnerInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => WorkspaceScalarWhereInputObjectSchema),
      data: z.union([
        z.lazy(() => WorkspaceUpdateManyMutationInputObjectSchema),
        z.lazy(() => WorkspaceUncheckedUpdateManyWithoutOwnerInputObjectSchema)
      ])
    })
    .strict() as SchemaType;
