/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { UserSettingsSchema } from '../models/UserSettings.schema';

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { WorkspaceCreateWithoutClientsInputObjectSchema } from './WorkspaceCreateWithoutClientsInput.schema';
import { WorkspaceUncheckedCreateWithoutClientsInputObjectSchema } from './WorkspaceUncheckedCreateWithoutClientsInput.schema';
import { WorkspaceCreateOrConnectWithoutClientsInputObjectSchema } from './WorkspaceCreateOrConnectWithoutClientsInput.schema';
import { WorkspaceUpsertWithoutClientsInputObjectSchema } from './WorkspaceUpsertWithoutClientsInput.schema';
import { WorkspaceWhereUniqueInputObjectSchema } from './WorkspaceWhereUniqueInput.schema';
import { WorkspaceUpdateToOneWithWhereWithoutClientsInputObjectSchema } from './WorkspaceUpdateToOneWithWhereWithoutClientsInput.schema';
import { WorkspaceUpdateWithoutClientsInputObjectSchema } from './WorkspaceUpdateWithoutClientsInput.schema';
import { WorkspaceUncheckedUpdateWithoutClientsInputObjectSchema } from './WorkspaceUncheckedUpdateWithoutClientsInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.WorkspaceUpdateOneRequiredWithoutClientsNestedInput>;
export const WorkspaceUpdateOneRequiredWithoutClientsNestedInputObjectSchema: SchemaType =
  z
    .object({
      create: z
        .union([
          z.lazy(() => WorkspaceCreateWithoutClientsInputObjectSchema),
          z.lazy(() => WorkspaceUncheckedCreateWithoutClientsInputObjectSchema)
        ])
        .optional(),
      connectOrCreate: z
        .lazy(() => WorkspaceCreateOrConnectWithoutClientsInputObjectSchema)
        .optional(),
      upsert: z
        .lazy(() => WorkspaceUpsertWithoutClientsInputObjectSchema)
        .optional(),
      connect: z.lazy(() => WorkspaceWhereUniqueInputObjectSchema).optional(),
      update: z
        .union([
          z.lazy(
            () => WorkspaceUpdateToOneWithWhereWithoutClientsInputObjectSchema
          ),
          z.lazy(() => WorkspaceUpdateWithoutClientsInputObjectSchema),
          z.lazy(() => WorkspaceUncheckedUpdateWithoutClientsInputObjectSchema)
        ])
        .optional()
    })
    .strict() as SchemaType;
