/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { UserSettingsSchema } from '../models/UserSettings.schema';

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { WorkspaceWhereInputObjectSchema } from './WorkspaceWhereInput.schema';
import { WorkspaceUpdateWithoutClientsInputObjectSchema } from './WorkspaceUpdateWithoutClientsInput.schema';
import { WorkspaceUncheckedUpdateWithoutClientsInputObjectSchema } from './WorkspaceUncheckedUpdateWithoutClientsInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.WorkspaceUpdateToOneWithWhereWithoutClientsInput>;
export const WorkspaceUpdateToOneWithWhereWithoutClientsInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => WorkspaceWhereInputObjectSchema).optional(),
      data: z.union([
        z.lazy(() => WorkspaceUpdateWithoutClientsInputObjectSchema),
        z.lazy(() => WorkspaceUncheckedUpdateWithoutClientsInputObjectSchema)
      ])
    })
    .strict() as SchemaType;
