/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.WorkspaceCountOutputTypeSelect>;
export const WorkspaceCountOutputTypeSelectObjectSchema: SchemaType = z
  .object({
    members: z.boolean().optional(),
    clients: z.boolean().optional()
  })
  .strict() as SchemaType;
