/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { DateTimeFilterObjectSchema } from './DateTimeFilter.schema';
import { StringNullableFilterObjectSchema } from './StringNullableFilter.schema';
import { StringFilterObjectSchema } from './StringFilter.schema';
import { EnumEntityStatusFilterObjectSchema } from './EnumEntityStatusFilter.schema';
import { EntityStatusSchema } from '../enums/EntityStatus.schema';
import { JsonNullableFilterObjectSchema } from './JsonNullableFilter.schema';
import { StringNullableListFilterObjectSchema } from './StringNullableListFilter.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.WorkspaceScalarWhereInput>;
export const WorkspaceScalarWhereInputObjectSchema: SchemaType = z
  .object({
    AND: z
      .union([
        z.lazy(() => WorkspaceScalarWhereInputObjectSchema),
        z.lazy(() => WorkspaceScalarWhereInputObjectSchema).array()
      ])
      .optional(),
    OR: z
      .lazy(() => WorkspaceScalarWhereInputObjectSchema)
      .array()
      .optional(),
    NOT: z
      .union([
        z.lazy(() => WorkspaceScalarWhereInputObjectSchema),
        z.lazy(() => WorkspaceScalarWhereInputObjectSchema).array()
      ])
      .optional(),
    createdAt: z
      .union([
        z.lazy(() => DateTimeFilterObjectSchema),
        z.union([z.date(), z.string().datetime().optional()])
      ])
      .optional(),
    updatedAt: z
      .union([
        z.lazy(() => DateTimeFilterObjectSchema),
        z.union([z.date(), z.string().datetime().optional()])
      ])
      .optional(),
    createdBy: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    updatedBy: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    id: z
      .union([z.lazy(() => StringFilterObjectSchema), z.string()])
      .optional(),
    name: z
      .union([z.lazy(() => StringFilterObjectSchema), z.string()])
      .optional(),
    slug: z
      .union([z.lazy(() => StringFilterObjectSchema), z.string()])
      .optional(),
    logoUrl: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    description: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    status: z
      .union([
        z.lazy(() => EnumEntityStatusFilterObjectSchema),
        z.lazy(() => EntityStatusSchema)
      ])
      .optional(),
    settings: z.lazy(() => JsonNullableFilterObjectSchema).optional(),
    address: z.lazy(() => JsonNullableFilterObjectSchema).optional(),
    features: z.lazy(() => StringNullableListFilterObjectSchema).optional(),
    ownerId: z
      .union([z.lazy(() => StringFilterObjectSchema), z.string()])
      .optional()
  })
  .strict() as SchemaType;
