/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { UserSettingsSchema } from '../models/UserSettings.schema';

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { EntityStatusSchema } from '../enums/EntityStatus.schema';
import { WorkspaceCreatefeaturesInputObjectSchema } from './WorkspaceCreatefeaturesInput.schema';
import { ResourceMemberCreateNestedManyWithoutWorkspaceInputObjectSchema } from './ResourceMemberCreateNestedManyWithoutWorkspaceInput.schema';
import { ClientCreateNestedManyWithoutWorkspaceInputObjectSchema } from './ClientCreateNestedManyWithoutWorkspaceInput.schema';
import { UserCreateNestedOneWithoutOwnedWorkspacesInputObjectSchema } from './UserCreateNestedOneWithoutOwnedWorkspacesInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.WorkspaceCreateInput>;
export const WorkspaceCreateInputObjectSchema: SchemaType = z
  .object({
    createdAt: z.union([z.date().optional(), z.string().datetime().optional()]),
    updatedAt: z.union([z.date().optional(), z.string().datetime().optional()]),
    createdBy: z.union([z.string(), z.null()]).optional().nullable(),
    updatedBy: z.union([z.string(), z.null()]).optional().nullable(),
    id: z.string().optional(),
    name: z.string(),
    slug: z.string(),
    logoUrl: z.union([z.string(), z.null()]).optional().nullable(),
    description: z.union([z.string(), z.null()]).optional().nullable(),
    status: z.lazy(() => EntityStatusSchema).optional(),
    settings: z.lazy(() => UserSettingsSchema),
    address: z.lazy(() => GooglePlacesAutocompleteSchema),
    features: z
      .union([
        z.lazy(() => WorkspaceCreatefeaturesInputObjectSchema),
        z.string().array()
      ])
      .optional(),
    members: z
      .lazy(
        () => ResourceMemberCreateNestedManyWithoutWorkspaceInputObjectSchema
      )
      .optional(),
    clients: z
      .lazy(() => ClientCreateNestedManyWithoutWorkspaceInputObjectSchema)
      .optional(),
    owner: z
      .lazy(() => UserCreateNestedOneWithoutOwnedWorkspacesInputObjectSchema)
      .optional()
  })
  .strict() as SchemaType;
