/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { WorkspaceWhereInputObjectSchema } from './WorkspaceWhereInput.schema';
import { DateTimeFilterObjectSchema } from './DateTimeFilter.schema';
import { StringNullableFilterObjectSchema } from './StringNullableFilter.schema';
import { StringFilterObjectSchema } from './StringFilter.schema';
import { EnumEntityStatusFilterObjectSchema } from './EnumEntityStatusFilter.schema';
import { EntityStatusSchema } from '../enums/EntityStatus.schema';
import { JsonNullableFilterObjectSchema } from './JsonNullableFilter.schema';
import { StringNullableListFilterObjectSchema } from './StringNullableListFilter.schema';
import { ResourceMemberListRelationFilterObjectSchema } from './ResourceMemberListRelationFilter.schema';
import { ClientListRelationFilterObjectSchema } from './ClientListRelationFilter.schema';
import { UserNullableScalarRelationFilterObjectSchema } from './UserNullableScalarRelationFilter.schema';
import { UserWhereInputObjectSchema } from './UserWhereInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.WorkspaceWhereUniqueInput>;
export const WorkspaceWhereUniqueInputObjectSchema: SchemaType = z
  .object({
    id: z.string().optional(),
    slug: z.string().optional(),
    AND: z
      .union([
        z.lazy(() => WorkspaceWhereInputObjectSchema),
        z.lazy(() => WorkspaceWhereInputObjectSchema).array()
      ])
      .optional(),
    OR: z
      .lazy(() => WorkspaceWhereInputObjectSchema)
      .array()
      .optional(),
    NOT: z
      .union([
        z.lazy(() => WorkspaceWhereInputObjectSchema),
        z.lazy(() => WorkspaceWhereInputObjectSchema).array()
      ])
      .optional(),
    createdAt: z
      .union([
        z.lazy(() => DateTimeFilterObjectSchema),
        z.union([z.date(), z.string().datetime().optional()])
      ])
      .optional(),
    updatedAt: z
      .union([
        z.lazy(() => DateTimeFilterObjectSchema),
        z.union([z.date(), z.string().datetime().optional()])
      ])
      .optional(),
    createdBy: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    updatedBy: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    name: z
      .union([z.lazy(() => StringFilterObjectSchema), z.string()])
      .optional(),
    logoUrl: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    description: z
      .union([
        z.lazy(() => StringNullableFilterObjectSchema),
        z.string(),
        z.null()
      ])
      .optional()
      .nullable(),
    status: z
      .union([
        z.lazy(() => EnumEntityStatusFilterObjectSchema),
        z.lazy(() => EntityStatusSchema)
      ])
      .optional(),
    settings: z.lazy(() => JsonNullableFilterObjectSchema).optional(),
    address: z.lazy(() => JsonNullableFilterObjectSchema).optional(),
    features: z.lazy(() => StringNullableListFilterObjectSchema).optional(),
    ownerId: z
      .union([z.lazy(() => StringFilterObjectSchema), z.string()])
      .optional(),
    members: z
      .lazy(() => ResourceMemberListRelationFilterObjectSchema)
      .optional(),
    clients: z.lazy(() => ClientListRelationFilterObjectSchema).optional(),
    owner: z
      .union([
        z.lazy(() => UserNullableScalarRelationFilterObjectSchema),
        z.lazy(() => UserWhereInputObjectSchema),
        z.null()
      ])
      .optional()
      .nullable()
  })
  .strict() as SchemaType;
