/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { UserSettingsSchema } from '../models/UserSettings.schema';

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { WorkspaceWhereUniqueInputObjectSchema } from './WorkspaceWhereUniqueInput.schema';
import { WorkspaceCreateWithoutMembersInputObjectSchema } from './WorkspaceCreateWithoutMembersInput.schema';
import { WorkspaceUncheckedCreateWithoutMembersInputObjectSchema } from './WorkspaceUncheckedCreateWithoutMembersInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.WorkspaceCreateOrConnectWithoutMembersInput>;
export const WorkspaceCreateOrConnectWithoutMembersInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => WorkspaceWhereUniqueInputObjectSchema),
      create: z.union([
        z.lazy(() => WorkspaceCreateWithoutMembersInputObjectSchema),
        z.lazy(() => WorkspaceUncheckedCreateWithoutMembersInputObjectSchema)
      ])
    })
    .strict() as SchemaType;
