/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { SortOrderSchema } from '../enums/SortOrder.schema';
import { SortOrderInputObjectSchema } from './SortOrderInput.schema';
import { WorkspaceCountOrderByAggregateInputObjectSchema } from './WorkspaceCountOrderByAggregateInput.schema';
import { WorkspaceMaxOrderByAggregateInputObjectSchema } from './WorkspaceMaxOrderByAggregateInput.schema';
import { WorkspaceMinOrderByAggregateInputObjectSchema } from './WorkspaceMinOrderByAggregateInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.WorkspaceOrderByWithAggregationInput>;
export const WorkspaceOrderByWithAggregationInputObjectSchema: SchemaType = z
  .object({
    createdAt: z.lazy(() => SortOrderSchema).optional(),
    updatedAt: z.lazy(() => SortOrderSchema).optional(),
    createdBy: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    updatedBy: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    id: z.lazy(() => SortOrderSchema).optional(),
    name: z.lazy(() => SortOrderSchema).optional(),
    slug: z.lazy(() => SortOrderSchema).optional(),
    logoUrl: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    description: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    status: z.lazy(() => SortOrderSchema).optional(),
    settings: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    address: z
      .union([
        z.lazy(() => SortOrderSchema),
        z.lazy(() => SortOrderInputObjectSchema)
      ])
      .optional(),
    features: z.lazy(() => SortOrderSchema).optional(),
    ownerId: z.lazy(() => SortOrderSchema).optional(),
    _count: z
      .lazy(() => WorkspaceCountOrderByAggregateInputObjectSchema)
      .optional(),
    _max: z
      .lazy(() => WorkspaceMaxOrderByAggregateInputObjectSchema)
      .optional(),
    _min: z.lazy(() => WorkspaceMinOrderByAggregateInputObjectSchema).optional()
  })
  .strict() as SchemaType;
