/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { UserSettingsSchema } from '../models/UserSettings.schema';

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { WorkspaceWhereUniqueInputObjectSchema } from './WorkspaceWhereUniqueInput.schema';
import { WorkspaceCreateWithoutOwnerInputObjectSchema } from './WorkspaceCreateWithoutOwnerInput.schema';
import { WorkspaceUncheckedCreateWithoutOwnerInputObjectSchema } from './WorkspaceUncheckedCreateWithoutOwnerInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.WorkspaceCreateOrConnectWithoutOwnerInput>;
export const WorkspaceCreateOrConnectWithoutOwnerInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => WorkspaceWhereUniqueInputObjectSchema),
      create: z.union([
        z.lazy(() => WorkspaceCreateWithoutOwnerInputObjectSchema),
        z.lazy(() => WorkspaceUncheckedCreateWithoutOwnerInputObjectSchema)
      ])
    })
    .strict() as SchemaType;
