/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { UserSettingsSchema } from '../models/UserSettings.schema';

import { GooglePlacesAutocompleteSchema } from '../models/GooglePlacesAutocomplete.schema';
import { z } from 'zod';
import { WorkspaceWhereInputObjectSchema } from './WorkspaceWhereInput.schema';
import { WorkspaceUpdateWithoutMembersInputObjectSchema } from './WorkspaceUpdateWithoutMembersInput.schema';
import { WorkspaceUncheckedUpdateWithoutMembersInputObjectSchema } from './WorkspaceUncheckedUpdateWithoutMembersInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType =
  z.ZodType<Prisma.WorkspaceUpdateToOneWithWhereWithoutMembersInput>;
export const WorkspaceUpdateToOneWithWhereWithoutMembersInputObjectSchema: SchemaType =
  z
    .object({
      where: z.lazy(() => WorkspaceWhereInputObjectSchema).optional(),
      data: z.union([
        z.lazy(() => WorkspaceUpdateWithoutMembersInputObjectSchema),
        z.lazy(() => WorkspaceUncheckedUpdateWithoutMembersInputObjectSchema)
      ])
    })
    .strict() as SchemaType;
