/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { WorkspaceWhereInputObjectSchema } from './WorkspaceWhereInput.schema';

import type { Prisma } from '@zenstackhq/runtime/models';

type SchemaType = z.ZodType<Prisma.WorkspaceListRelationFilter>;
export const WorkspaceListRelationFilterObjectSchema: SchemaType = z
  .object({
    every: z.lazy(() => WorkspaceWhereInputObjectSchema).optional(),
    some: z.lazy(() => WorkspaceWhereInputObjectSchema).optional(),
    none: z.lazy(() => WorkspaceWhereInputObjectSchema).optional()
  })
  .strict() as SchemaType;
